nordic-institute/X-Road

- doc/Manuals/ug-syspar_x-road_v6_system_parameters.md
- src/common-util/src/main/java/ee/ria/xroad/common/SystemProperties.java
- src/signer/src/main/java/ee/ria/xroad/signer/OcspClientJob.java
- Change Fibonacci based recovery schedule to fixed schedule.
- Add new signer system property `ocsp-retry-delay` that defines a fixed delay that `signer` waits after failing to fetch OCSP responses before trying again.
- Set `ocsp-retry-delay` default value to 60 seconds.
- Add `ocsp-retry-delay` parameter description to System Parameters User Guide.
> XRDDEV-51 Update OCSP response recovery schedule

- doc/Manuals/ig-cs_x-road_6_central_server_installation_guide.md
- doc/Manuals/ig-ss_x-road_v6_security_server_installation_guide.md
- doc/Manuals/ug-cp_x-road_v6_configuration_proxy_manual.md
Update Security Server and Central Server installation guides and Configuration Proxy user guide:
- Remove references to x-road.eu package repository
- Add references to NIIS's package repository
- Update installation instructions (commands)
- Update document's version number
Additional changes to Security Server installation guide:
- Add RHEL7 to supported platforms
- Add note about `xroad-securityserver-fi` metapackage
- Replace X-tee specific instructions with generic instructions
> XRDDEV-162

- src/packages/src/xroad/default-configuration/override-securityserver-fi.ini
Update default authentication and signing key length to 3072 bits (Finnish national settings only)
> XRDDEV-229

- CHANGELOG.md
- doc/OperationalMonitoring/Protocols/pr-opmon_x-road_operational_monitoring_protocol_Y-1096-2.md
- src/addons/op-monitoring/src/test/java/ee/ria/xroad/proxy/opmonitoring/OpMonitoringBufferMemoryUsage.java
- src/common-op-monitoring/src/main/java/ee/ria/xroad/common/opmonitoring/OpMonitoringData.java
- src/op-monitor-daemon/src/main/resources/query_operational_data_response_payload_schema.yaml
- src/op-monitor-daemon/src/main/resources/store_operational_data_request_schema.yaml
- src/proxy/src/main/java/ee/ria/xroad/proxy/clientproxy/AbstractClientProxyHandler.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/clientproxy/ClientMessageProcessor.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/serverproxy/ServerMessageProcessor.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/serverproxy/ServerProxyHandler.java
XTE-427 / XRDDEV-108: Operational monitoring timestamp 'responseOutTs' is taken just before payload byte array is sent out with HTTP response.
> estonian-6.20.0-2

- src/common-ui/app/views/application/_activate_token_dialog.html.erb
Ensure that token activation form can not be submitted (can reveal the pin code on the URL bar).
> XRDDEV-368: Fix XRDDEV-368

- doc/Manuals/ug-syspar_x-road_v6_system_parameters.md
- src/addons/messagelog/src/main/java/ee/ria/xroad/proxy/messagelog/LogArchiver.java
- src/addons/messagelog/src/main/java/ee/ria/xroad/proxy/messagelog/LogCleaner.java
- src/addons/messagelog/src/main/resources/messagelog.hbm.xml
- src/addons/messagelog/src/test/java/ee/ria/xroad/proxy/messagelog/TestLogCleaner.java
- src/common-messagelog/src/main/java/ee/ria/xroad/common/messagelog/MessageLogProperties.java
- src/packages/src/xroad/default-configuration/addons/message-log.ini
Message log cleaning can fail with 'out of shared memory' if there are
tens of thousands of REST messages to clean. This is due to PostgreSQL
acquiring a lock when a LOB is deleted.
Clean records in configurable batches, avoiding too many locks in
one transaction.
> XRDDEV-439

- doc/Manuals/ug-syspar_x-road_v6_system_parameters.md
- src/addons/messagelog/src/main/java/ee/ria/xroad/proxy/messagelog/LogManager.java
- src/addons/messagelog/src/main/java/ee/ria/xroad/proxy/messagelog/TaskQueue.java
- src/common-messagelog/src/main/java/ee/ria/xroad/common/messagelog/MessageLogProperties.java
Implement time-stamping recovery mode when time-stamping fails.
- Add `timestamp-retry-delay` property that defines recovery interval when batch time-stamping fails.
- Time-stamping is tried using the recovery interval until a time-stamp is successfully fetched.
- After a successful time-stamp, the time-stamper returns to use the value of the central server system parameter `timeStampingIntervalSeconds`.
- Update System Parameters document.
- Time-stamping recovery mode tries to time-stamp one message only.
- Once time-stamping a single message succeeds, the time-stamper tries to time-stamp maximum number of messages defined by the timestamp-records-limit property.
- The time-stamper does not wait for `timestamp-retry-delay` or `timeStampingIntervalSeconds` - all queued messages are …
> XRDDEV-474

- src/proxy-ui/app/controllers/clients/services.rb
- Fix incorrect property name referencing WSDL in service object.
- New property name is `serviceDescription`.
> Fix undefined method error when WSDL is refreshed

- doc/Manuals/ig-ss_x-road_v6_security_server_installation_guide.md
- src/packages/src/xroad/redhat/SPECS/xroad-securityserver-fi.spec
- src/packages/src/xroad/ubuntu/generic/control
- Added xroad-addon-opmonitoring package as required for installation of meta-package of X-Road security server with Finnish settings, xroad-securityserver-fi.
- Updated security server installation instructions to indicate that xroad-securityserver-fi meta-package installs xroad-addon-opmonitoring module.
> WIP XRDDEV-580

- doc/Manuals/ug-cs_x-road_6_central_server_user_guide.md
- doc/Manuals/ug-syspar_x-road_v6_system_parameters.md
- src/center-common/app/models/invalid_owner_change_request_exception.rb
- src/center-common/app/models/owner_change_request.rb
- src/center-common/app/models/owner_change_request_processing.rb
- src/center-common/app/models/security_server.rb
- src/center-common/config/locales/en.yml
- src/center-service/app/controllers/registration_management_controller.rb
- src/center-service/src/main/java/ee/ria/xroad/common/request/ManagementRequestHandler.java
- src/center-service/src/main/java/ee/ria/xroad/common/request/ManagementRequestParser.java
- src/center-ui/app/controllers/requests_controller.rb
- src/center-ui/app/views/requests/index.html.erb
- src/center-ui/app/views/shared/_member_edit_dialog.html.erb
- src/center-ui/app/views/shared/_owner_change_request_edit_dialog.html.erb
- src/center-ui/config/locales/views_en.yml
- src/center-ui/public/javascripts/centerui_common.js
- src/center-ui/public/javascripts/request_edit.js
- src/center-ui/public/javascripts/requests.js
- src/common-util/src/main/java/ee/ria/xroad/common/SystemProperties.java
- src/common-util/src/main/java/ee/ria/xroad/common/request/ManagementRequests.java
- src/common-util/src/main/resources/request.xsd
- src/packages/src/xroad/default-configuration/managementservices.wsdl
Implement Security Server `ownerChange` management service:
- Add `ownerChange` management service.
- Update CS UI so that requests can be approved / declined.
- UI does not provide features for creating `ownerChange` requests manually - a complementary request is created automatically from a request from Security Server is received.
- Implement automatic approval of `ownerChange` management requests.
- Update documentation.
- Update `managementservices.wsdl ` and  `request.xsd`
> XRDDEV-560

- src/packages/src/xroad/ubuntu/generic/xroad-center.postinst
- src/packages/src/xroad/ubuntu/generic/xroad-proxy.postinst
Check if the X-Road admin user already belongs to a group.
Do not fail installation if modifying X-Road admin user groups fails.
> XRDDEV-540

- src/center-service/app/controllers/auth_cert_registration_controller.rb
- src/center-ui/app/controllers/securityservers_controller.rb
- src/center-ui/app/helpers/cert_transformation_helper.rb
- src/center-ui/public/javascripts/securityserver_edit.js
- src/common-ui/lib/common-ui/validation_utils.rb
- src/proxy/src/main/java/ee/ria/xroad/proxy/clientproxy/AbstractClientMessageProcessor.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/clientproxy/ClientMessageProcessor.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/clientproxy/ClientRestMessageProcessor.java
- src/proxy/src/test/java/ee/ria/xroad/proxy/RestProxyTest.java
- src/proxy/src/test/java/ee/ria/xroad/proxy/testsuite/testcases/SslSelectFastestProxy.java
- src/proxy/src/test/java/ee/ria/xroad/proxy/testsuite/testcases/SslSelectFastestProxyNoConnections.java
Reject invalid host names in security server and central server
configuration (fixes also XRDDEV-732).
For additional robustness, fix service provider host selection fails to
select a host if some of the host addresses are syntactically invalid.
> XRDDEV-730: Validate security server addresses

- src/packages/src/xroad/redhat/SOURCES/proxy/xroad-proxy-setup.sh
Enables nginx binding to port 5000 in machines where SELinux is used and port 5000 is associated with "commplex_main_port_t"
jenkins build: https://jenkins.niis.org/view/build/job/xroad-build-packages-pipeline/1137/
packages were installed to dev-rh1 and dev-rh2 (rh1 "vanilla", rh2 had manual semanage modify 5000 done earlier)
> XRDDEV-724 fix SELinux rhel packages port 5000

- src/signer/src/main/java/ee/ria/xroad/signer/protocol/handler/GetTokenInfoForKeyIdRequestHandler.java
was broken due to bad RequestHandler name.
> XRDDEV-806 fix broken GetTokenInfoForKeyId

- src/proxy-ui-api/frontend/audit-resolve.json
This adds ignore for the new node-sass vulnerability.  
It is low level and in the "devDependencies" so this is not dangerous, but it fails the build.
https://npmjs.com/advisories/961
> Add one month ignore for node-sass low level vulnerability

- src/common-util/src/test/java/ee/ria/xroad/common/util/filewatcher/FileWatcherRunnerTest.java
Add some javadoc comments hopefully helping someone who runs into the "out of inode watchers" problem and wonders why FileWatcherRunnerTest fails.
https://jenkins.niis.org/job/xroad-pull-request-test/59/ (success)
> XRDDEV-602 add note about inode exhaustion to tests

- src/common-util/src/main/java/ee/ria/xroad/common/util/HandlerBase.java
- src/common-util/src/main/java/ee/ria/xroad/common/util/XmlUtils.java
- src/op-monitor-daemon/src/main/java/ee/ria/xroad/opmonitordaemon/OpMonitorDaemonRequestHandler.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/clientproxy/AbstractClientProxyHandler.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/clientproxy/ClientRestMessageHandler.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/serverproxy/ServerProxyHandler.java
- src/proxy/src/test/java/ee/ria/xroad/proxy/RestProxyTest.java
- Security Server respects Accept-header from client when providing error responses
- Application/json, application/xml, text/xml are supported, where application/json is the default
- Added automatic tests for the feature
> XRDDEV-591

- src/packages/src/xroad/ubuntu/generic/xroad-center.preinst
When upgrading from pre-6.23 version to 6.23 or later, detect if the central server is using a HA setup with PostgreSQL BDR and configure center.ha-node-name using the BDR node name if it has not been set.
> XRDDEV-813

- src/proxy-ui-api/frontend/vue.config.js
Parameterize proxy-ui-api frontend devServer proxy address so that developers don't need to customize it in order to get frontend working
> Parametrize proxy ui api proxy address

- src/addons/wsdlvalidator/build.gradle
- src/build.gradle
- src/common-util/build.gradle
Updates include fixes to the following vulnerabilities in dependencies:
* Quarz scheduler 2.3.1 to 2.3.2 (CVE-2019-13990)
* Apache CXF wsdlvalidator 3.2.6 to 3.2.12 (CVE-2019-12491)
* FasterXML jackson-databind 2.9.10.1 to 2.9.20.2 (CVE-2019-20330)
> XRDDEV-856: Update dependencies

- src/proxy-ui-api/frontend/src/components/ui/StatusIcon.vue
- src/proxy-ui-api/frontend/src/global.ts
- src/proxy-ui-api/frontend/src/views/Clients/ClientStatus.vue
- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/SignAndAuthKeys/CertificateStatus.vue
A small update
- Status icon of sign & auth keys table is now functional in all cases
- Added a new shared "icon component" that also replaces the old implementation in clients list
> Fix status icons with a shared component

- src/proxy-ui-api/frontend/src/locales/en.json
- src/proxy-ui-api/frontend/src/views/CertificateDetails/CertificateDetails.vue
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/openapi/TokenCertificatesApiController.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/PossibleActionsRuleEngine.java
- src/proxy-ui-api/src/main/resources/openapi-definition.yaml
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/service/PossibleActionsRuleEngineTest.java
Small updates for already-closed https://jira.niis.org/browse/XRDDEV-776, based on comments from demo:
- key delete is not a possible action if token is not active (would fail if attempted)
- certificate action is now "disable" in the API endpoint, instead of old "deactivate" (in line with other actions such as token/login which also use UI terms, and with possible action "DISABLE")
> XRDDEV-776 updates from demo comments

- src/proxy-ui-api/frontend/audit-resolve.json
- src/proxy-ui-api/frontend/package-lock.json
Fix for failing npm audit checks, that were caused by https://www.npmjs.com/advisories/1468
> Fix npm audit issue https://www.npmjs.com/advisories/1468

- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/cache/SecurityServerOwner.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/cache/SecurityServerOwnerConfig.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/converter/ClientConverter.java
- src/proxy-ui-api/src/main/resources/openapi-definition.yaml
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/converter/ClientConverterTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/converter/LocalGroupConverterTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/ClientsApiControllerIntegrationTest.java
https://jira.niis.org/browse/XRDDEV-812
ClientConverter populates all Client objects with owner (true/false) property which tells if the client is security server's owner member. This is based on a request scoped bean in a new `org.niis.xroad.restapi.cache` package.
> XRDDEV-812 implement client.owner true/false property

- src/proxy-ui-api/frontend/src/App.vue
- src/proxy-ui-api/frontend/src/components/layout/AppFooter.vue
- src/proxy-ui-api/frontend/src/components/layout/AppToolbar.vue
- src/proxy-ui-api/frontend/src/views/AppBase.vue
This fix involved changing the layout structure. In summary:
- The components app-toolbar and app-footer were moved from AppBase.vue to App.vue so they can be immediately under v-app (seems to be required for vuetify-s structure to work correctly)
- Changed the wrapper div around content under App.vue to be v-content instead (again, seems to be a requirement for vuetify-s layout)
- Changed AppToolbar.vue to use v-app-bar instead of v-toolbar (was recommended under console)
- Removed the "absolute" attribute from AppFooter.vue v-footer component
I manually tested as much as I knew how to and there seem to be no side-effects to these changes.
> XRDDEV-952: fixed issue with footer covering elements if the page needs to scroll

- src/proxy-ui-api/frontend/audit-resolve.json
- src/proxy-ui-api/frontend/package-lock.json
There is a vulnerability warning coming from acorn library that is used by vue cli-plugin and that causes the build to fail.
Added acorn vulnerability to ignore list for a one month with resolve-audit.
https://confluence.niis.org/display/XRDDEV/Front-end+build+process#Frontendbuildprocess-npm-audit-resolver
> Add vulnerabilities to resolve audit list

- src/proxy-ui-api/frontend/audit-resolve.json
- src/proxy-ui-api/frontend/package-lock.json
There are some minor warnings in dev dependencies.
Those are added to the audit resolver ignore list for a month.
https://confluence.niis.org/display/XRDDEV/Front-end+build+process#Frontendbuildprocess-npm-audit-resolver
> Ignore new audit warnings for a month

- src/proxy-ui-api/frontend/src/views/Settings/Settings.vue
There was a scss class "content" that was probably accidentally set as global. 
This caused other parts of the UI to break which were also using a class with same name.
Class is now scoped and issue fixed.
> UI layout quickfix for content class

- src/packages/src/xroad/default-configuration/proxy.ini
- src/packages/src/xroad/redhat/SPECS/xroad-proxy.spec
- src/packages/src/xroad/ubuntu/generic/xroad-proxy.preinst
- Remove `allow-get-wsdl-request` from `proxy.ini`.
- Remove refences to `allow-get-wsdl-request` from Ubuntu and RHEL installation scripts.
> XRDDEV-1028 Remove references to allow-get-wsdl-request property

- src/packages/src/xroad/common/proxy/usr/share/xroad/db/serverconf-changelog.xml
- src/packages/src/xroad/common/proxy/usr/share/xroad/db/serverconf-legacy-changelog.xml
- src/packages/src/xroad/common/proxy/usr/share/xroad/db/serverconf/001-apikeys.xml
- src/packages/src/xroad/redhat/SOURCES/proxy/xroad-proxy-setup.sh
- src/packages/src/xroad/ubuntu/generic/xroad-proxy.postinst
Make it simpler to manually fix a security server install in case migration
fails due to insufficient database rights.
> XRDDEV-972: Refactor security server db migrations

- src/proxy-ui-api/frontend/audit-resolve.json
- src/proxy-ui-api/frontend/package-lock.json
Adds yargs-parser to accepted vulnerabilities for one month.
Removes minimalist which has been fixed.
Updated the confluence accordingly
https://confluence.niis.org/display/XRDDEV/Accepted+npm+audit+vulnerabilities
> Fix npm audit build issue

- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/ServicesApiControllerIntegrationTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/service/ServiceDescriptionServiceIntegrationTest.java
This was actually done already in a refactoring, but I added a couple of tests just for this.
https://jira.niis.org/browse/XRDDEV-1027
> XRDDEV-1027 adding duplicate access rights for a localgroup is prevented.

- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/config/JacksonConfiguration.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/config/StringDeserializerModifier.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/controller/ControllerConfiguration.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/StringTrimmerRestTemplateTest.java
- Adds a Jackson deserializer modifier to trim strings after deserialization of JSON requests.
- Adds a binder to trim other input strings such as query params.
JIRA: https://jira.niis.org/browse/XRDDEV-1003
> XRDDEV-1003 Trim spaces

- src/proxy-ui-api/frontend/src/components/client/DeleteClientButton.vue
- src/proxy-ui-api/frontend/src/locales/en.json
Redirect user to clients list when client is deleted:
- Redirect user to clients list when client is deleted and orphans are not deleted.
- Change confirmOrphans dialog's cancel button's label to No.
JIRA issue:  https://jira.niis.org/browse/XRDDEV-1142
> XRDDEV-1142

- src/proxy-ui-api/frontend/src/store/modules/addClient.ts
- src/proxy-ui-api/frontend/src/views/AddSubsystem/AddSubsystem.vue
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/util/ClientUtils.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/service/ClientServiceIntegrationTest.java
- Fix Add subsystem query
- Add missing query parameter: `internal_search=false`
- Fix Add client query
- Filter out all clients that have local relatives.
- If the member owning the client or another subsystem of the same member is already present locally, the client is excluded.
- Fix bug in client search with `local_valid_sign_cert` param
- Compare only the member part of the client identifier to member identifiers in the certificates.
JIRA issues: https://jira.niis.org/browse/XRDDEV-1122
> XRDDEV-1122

- src/proxy-ui-api/build.gradle
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/util/FormatUtils.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/DiagnosticsApiControllerTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/util/TestUtils.java
Fix timezone issue in diagnostics timestamps:
- Convert local time returned by admin APIs to OffsetDateTime using default system timezone as source timezone.
- Set UTC timezone for tests since otherwise default timezone of JVM is used.
JIRA issue: https://jira.niis.org/browse/XRDDEV-1132
> XRDDEV-1132

- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/config/MvcConfig.java
Enabled caching (maximum of 365 days) for static assets. Frontend build already implements a cache busting mechanism by appending a hash (based on file contents) to all transpiled bundle files.
`index.html` is not cached on purpose because we want to reload the static assets everytime when they have changed (== `index.html` will provide the changed names of the new static assets)
JIRA: https://jira.niis.org/browse/XRDDEV-339
> XRDDEV-339 Enable caching for static resources

- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/ServiceDescriptionService.java
Bug fixes for refresh and update WSDL and OpenAPI3 features:
- Do no overwrite timeout and SSL authentication values when WSDL is refreshed or updated.
- Do not overwrite service URL value when OpenAPI3 service description is refreshed or updated.
- Reload and parse OpenAPI3 service description on update so that implementation is consistent with WSDLs.
JIRA issue: https://jira.niis.org/browse/XRDDEV-1158
> XRDDEV-1158

- src/proxy-ui-api/frontend/src/components/ui/Snackbar.vue
- src/proxy-ui-api/frontend/src/global.ts
- src/proxy-ui-api/frontend/src/store/modules/user.ts
- src/proxy-ui-api/frontend/src/ui-types.ts
- src/proxy-ui-api/frontend/src/views/Clients/Client.vue
- src/proxy-ui-api/frontend/src/views/Clients/Subsystem.vue
- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/KeysAndCertificates.vue
- src/proxy-ui-api/frontend/src/views/Settings/Settings.vue
https://jira.niis.org/browse/XRDDEV-1171
Changed the tab interface so that it has a permissions array instead of a permission string. Now a tab can have multiple permissions and if even one of them exists the tab visible. This fixes the "problem" that the Settings view doesn't have its own permission.
> XRDDEV-1171 Fix service tab permission bug

- src/autologin/source/common/xroad-autologin-retry.sh
- src/common-util/src/main/resources/akka-global.conf
- src/gradle.properties
- src/packages/src/xroad/default-configuration/signer.ini
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/config/StartStopListener.java
- src/signer-protocol/src/main/java/ee/ria/xroad/signer/protocol/SignerClient.java
- src/signer/src/main/java/ee/ria/xroad/signer/Signer.java
- src/signer/src/main/java/ee/ria/xroad/signer/SignerMain.java
- src/signer/src/main/java/ee/ria/xroad/signer/protocol/AbstractRequestHandler.java
- src/signer/src/main/resources/application.conf
In certain conditions, SignerClient can observe timeout when Signer is restarted while a request is being made. Make SignerClient
to watch Signer's RequestProcessor actor, and in case of termination, try to re-establish connection as soon as possible. Alter the Signer startup to remove unnecessary delays.
Also update Akka to the latest patch version (2.6.6).
> XRDDEV-1017: Make SignerClient more robust

- src/proxy-ui-api/frontend/src/components/ui/Snackbar.vue
- src/proxy-ui-api/frontend/src/store/modules/notifications.ts
- src/proxy-ui-api/frontend/src/ui-types.ts
https://jira.niis.org/browse/XRDDEV-1206
https://jira.niis.org/browse/XRDDEV-1196
- Errors are now stored in an array
- Snackbars open on top of each other, but the user can see all the errors by closing the topmost
- Not a perfect solution because in some cases the errors can accumulate. How to handle that should be decided later.
> XRDDEV-1206 & XRDDEV-1196 Snackbar error modifications

- src/common-util/src/main/java/ee/ria/xroad/common/certificateprofile/impl/IsSignCertificateProfileInfo.java
Changing IsSignCertificateProfileInfo to use getClientId instead of getServerId for O, OU, CN
> Update Certificate profile to support clientID

- src/proxy-ui-api/frontend/src/locales/en.json
- src/proxy-ui-api/frontend/src/plugins/vee-validate.ts
- src/proxy-ui-api/frontend/src/views/Service/Parameters/ServiceParameters.vue
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/openapi/ServicesApiController.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/InternalServerTestService.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/InvalidHttpsUrlException.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/ServiceService.java
- src/proxy-ui-api/src/main/resources/openapi-definition.yaml
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/AbstractApiControllerTestContext.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/ServicesApiControllerIntegrationTest.java
Verify SSL auth on service update and show a warning dialog to the user:
- Verify SSL authentication with IS when service is updated and `sslAuth` is true.
- Show warning dialog if verification of SSL auth with IS fails on service update.
- Validate that URL is HTTPS when `sslAuth` is true.
- Add `ignoreWarnings` param to `updateService` endpoint.
- Copy `InternalServerTestService` implementation from the old UI module.
- The old UI module (`proxy-ui`) code will be removed at a later point.
- Update OpenAPI description.
- Update unit tests and new tests for the additions.
JIRA issues:
- https://jira.niis.org/browse/XRDDEV-1239 (backend)
- https://jira.niis.org/browse/XRDDEV-1240 (frontend)
> XRDDEV-1239/XRDDEV-1240

- src/proxy-ui-api/frontend/src/store/modules/certificateSignRequest.ts
- src/proxy-ui-api/src/main/resources/openapi-definition.yaml
The old UI used an empty string, so we will allow the same to keep it optional.
JIRA issue: https://jira.niis.org/browse/XRDDEV-1210
> XRDDEV-1210: key label can't be null, as this causes a NPE in HardwareTokenWorker

- src/packages/src/xroad/redhat/SOURCES/proxy-ui-api/xroad-proxy-ui-api-setup.sh
- src/packages/src/xroad/redhat/SOURCES/proxy/xroad-proxy-setup.sh
- src/packages/src/xroad/redhat/SPECS/xroad-base.spec
- src/packages/src/xroad/ubuntu/generic/control
https://jira.niis.org/browse/XRDDEV-1254
- fix broken installation on systems without openssl
- improve error handling when generate_certificates fails
> XRDDEV-1254 

- src/packages/src/xroad/common/proxy/usr/share/xroad/scripts/restore_db.sh
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/EvictConnectionsService.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/RestoreService.java
https://jira.niis.org/browse/XRDDEV-1267
- restore script kills open serverconf database connections before restoring
- application clears connection pool after restore
> XRDDEV-1267

- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/scheduling/GlobalConfChecker.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/BackupRestoreEvent.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/NotificationService.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/RestoreService.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/util/PersistenceUtils.java
* Refactor RestoreService to publish an restore start/stop event,
decoupling it from listeners (GlobalConfChecker, NotificationService).
* Clean up EvictConnectionsService (no need for a transaction when
evicting connections)
> XRDDEV-1271: Avoid GlobalConf update during backup restore

- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/openapi/ClientsApiController.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/openapi/ServiceDescriptionsApiController.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/InvalidServiceUrlException.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/ServiceDescriptionService.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/wsdl/WsdlParser.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/ClientsApiControllerIntegrationTest.java
- src/proxy-ui-api/src/test/resources/wsdl/invalid-serviceurl.wsdl
Adds a validation for WSDL service URLs when adding a new WSDL. Forces the service URLs to start with `http://` or `https://`. The faulty URLs will be returned in the error response's metadata field
JIRA: https://jira.niis.org/browse/XRDDEV-408
> XRDDEV-408 Validate wsdl service urls

- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/converter/ServiceConverter.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/ServicesApiControllerIntegrationTest.java
On converter layer sslAuth is set false for services whose url starts with http:// 
https://jira.niis.org/browse/XRDDEV-1320
> XRDDEV-1320: sslAuth is returned as false for services whose url starts with http://

- src/proxy-ui-api/frontend/src/assets/functions.scss
- src/proxy-ui-api/frontend/src/components/ui/SimpleDialog.vue
- src/proxy-ui-api/frontend/src/components/ui/SubViewTitle.vue
Adds a function to prevent Sass compiler from decoding unicode escape sequences. The function is used in dialogs' close buttons.
More info in JIRA: https://jira.niis.org/browse/XRDDEV-1354
> XRDDEV-1354 Dialog close button bug

- src/proxy-ui-api/frontend/src/views/KeyDetails/KeyDetails.vue
- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/SignAndAuthKeys/KeyRow.vue
In the UI, use key id to identify auth and sign keys if label and friendly name are missing:
- Show key id (`id`) in the Keys and certificates list if the key does not have a label (`label`) and a friendly name (`name`).
- Show key id (`id`) in the Key details view in the Friendly name field if the key does not have a friendly name (`name`).
Changes are implemented on the frontend side to make the UI more user friendly. The API returns empty `label` and `name` fields if the values have not been set.
JIRA issue: https://jira.niis.org/browse/XRDDEV-1353
> XRDDEV-1353

- src/proxy-ui-api/frontend/src/store/modules/addClient.ts
- src/proxy-ui-api/frontend/src/views/AddClient/ClientDetailsPage.vue
- src/proxy-ui-api/frontend/src/views/AddMember/MemberDetailsPage.vue
Add instance parameter to client and member searches so that results contain only clients / members that belong to the Security Server's home instance:
- Add instance parameter to client search in Add client flow.
- Add instance parameter to member search in Add member flow.
- Search results contain only clients/members that belong to the same instance with the Security Server.
JIRA issue: https://jira.niis.org/browse/XRDDEV-1362
> XRDDEV-1362

- src/proxy-ui-api/frontend/license-check-and-add-config.json
https://jira.niis.org/browse/XRDDEV-1424
Add new type files created from openapi specifications to the ignore list of the frontend license check
> XRDDEV-1424 Update the ignore list of the frontend license check

- Docker/centralserver/Dockerfile
- Docker/securityserver/files/ss-xroad.conf
When running on Linux kernel 5.8+, xroad-proxy process in docker container does
not start due to an error: setpriv: libcap-ng is too old for "all" caps
> XRDDEV-1448

- src/proxy-ui-api/frontend/src/views/Clients/Services/Services.vue
Switches the permissions used for "add WSDL" and "add REST" buttons.
Doesn't affect UI functionality.
> Switch the add wsdl and add rest permissions

- src/proxy-ui-api/frontend/src/components/wizard/WizardPageGenerateCsr.vue
- src/proxy-ui-api/frontend/tests/e2e/pages/common/addSubjectsPopup.js
- src/proxy-ui-api/frontend/tests/e2e/pages/ssMainPage.js
- src/proxy-ui-api/frontend/tests/e2e/pages/tabs/keysTab.js
- src/proxy-ui-api/frontend/tests/e2e/pages/tabs/settingsTab.js
- src/proxy-ui-api/frontend/tests/e2e/specs/ss-backupandrestore.js
- src/proxy-ui-api/frontend/tests/e2e/specs/ss-clients-openapiservices.js
- src/proxy-ui-api/frontend/tests/e2e/specs/ss-clients-restservices.js
- src/proxy-ui-api/frontend/tests/e2e/specs/ss-clients-wsdlservices.js
- src/proxy-ui-api/frontend/tests/e2e/specs/ss-keyscerts-authsignkeys.js
- src/proxy-ui-api/frontend/tests/e2e/specs/ss-logout.js
e2e environment was upgraded from X-Road 6.24 to 6.26. This upgrade introduced frontend changes that broke some of the e2e tests. This PR fixes those tests. 
This PR also changes Add Key and CSR wizard's `Done` buttons `disabled` status behavior: the button will be enabled after the API request returns success (instead of being enabled right after the request is sent)
> e2e test fixes v6.26

- src/addons/metaservice/build.gradle
- src/addons/wsdlvalidator/build.gradle
- src/build.gradle
- src/buildSrc/build.gradle
- src/center-common/Gemfile.lock
- src/center-service/Gemfile.lock
- src/center-ui/Gemfile.lock
- src/common-test/build.gradle
- src/common-ui/Gemfile.lock
- src/common-ui/build.gradle
- src/common-util/build.gradle
- src/gradle.properties
- src/monitor-common/build.gradle
- src/monitor-test/build.gradle
- src/monitor/build.gradle
- src/packages/src/xroad/common/center/etc/xroad/services/jetty.conf
- src/proxy-ui-api/build.gradle
- upgrade dependencies to latest bugfix releases
- increase central server jetty MaxMetaspace to 200m to prevent OutOfMemoryErrors
> 6.26 beta update dependencies

- src/addons/messagelog/src/main/java/ee/ria/xroad/proxy/messagelog/TaskQueue.java
Define explicit ordering for timestamped records, so that a clustered
setup that shares the messagelog database, all nodes update records
in the same order.
The query returning to-be-timestamped records uses an index that includes
the record id. The "order by id" added by this fix is virtually free
because the index is already sorted by id. Therefore it is also likely
that the records were already returned in the same order and a deadlock
could not occur in practice.
> XRDDEV-1544: Define ordering for timestamped records

- src/proxy-ui-api/frontend/src/components/ui/ContextualAlerts.vue
- src/proxy-ui-api/frontend/src/views/TokenDetails/TokenDetails.vue
* Pin change is only shown for software tokens
* `weak_pin` error is now handled so that the metadata fields have translations
As background info: the weak pin error is formed in the backend as follows
```java
List<String> metadata = new ArrayList<>();
metadata.add(ERROR_METADATA_PIN_MIN_LENGTH);
metadata.add(String.valueOf(TokenPinPolicy.MIN_PASSWORD_LENGTH));
metadata.add(ERROR_METADATA_PIN_MIN_CHAR_CLASSES);
metadata.add(String.valueOf(TokenPinPolicy.MIN_CHARACTER_CLASS_COUNT));
```
> XRDDEV-1226 token pin change frontend part2

- ansible/roles/xroad-base/tasks/main.yml
- ansible/ss_cluster/roles/master/tasks/main.yml
- ansible/ss_cluster/roles/slave/tasks/main.yml
* In the xroad-base role, when creating xroad user, add it to xroad group
* In the ss_cluster master and slave role, when creating node.ini it's owner to xroad
These changes will also fix the problem with slave nodes not being able to create conf backups since xroad user cannot read node.ini
> Ansible improvements

- src/proxy-ui-api/frontend/nightwatch.json
Seems that screenshots were missconfigured, settings were placed under `test_settings` where they do get overridden by non-default test settings.
Change seems to work fine also headlless execution. in such case it won't generate screenshots but doesn't fail on it either.
> XRDDEV-1662 config for screenshots moved to test settings

- ansible/ss_cluster/roles/slave/templates/xroad-sync.conf.j2
- ansible/ss_cluster/roles/slave/templates/xroad-sync.service.j2
- doc/Manuals/LoadBalancing/ig-xlb_x-road_external_load_balancer_installation_guide.md
Fixes cluster rsync fails due to filesystem permissions.
> XRDDEV-1721: Exclude /etc/xroad/gpghome from cluster rsync

- src/asic-util/src/main/java/ee/ria/xroad/common/asic/AsicContainer.java
OpenDocument manifest lacked a reference to "attachment1" if one was
present in the container (applies only to REST messages)
> XRDDEV-1722: Fix file reference missing from manifest

- src/addons/messagelog/messagelog-addon/src/test/java/ee/ria/xroad/proxy/messagelog/AbstractMessageLogTest.java
- src/common-messagelog/src/test/java/ee/ria/xroad/common/messagelog/archive/LogArchiveCacheTest.java
- src/common-messagelog/src/test/java/ee/ria/xroad/common/messagelog/archive/LogArchiveTest.java
- src/proxy-ui-api/frontend/package.json
- src/proxy-ui-api/frontend/tests/e2e/pages/tabs/settingsTab.js
- src/proxy-ui-api/frontend/tests/e2e/specs/ss-settings-timestamping.js
Fixed timestamping tests:
https://jenkins.niis.org/job/rest-ui-e2e-tests/731/
Two obvious issues:
- There was little misunderstanding of what is initial state in test environment after a reset, causing tests to fail because of already existing service. I changed order of tests so it starts from deletion test and continues to creating service afterwards. It seems to work in both local envs and in jenkins.
- When creating tests, there was an assumption that urls are same everywhere. This is not the case, value changes between environments, so assertion is modified in a way that it just checks that value starts with `http`. It should realiable enough for this purpose and will catch both http and https.
> Xrddev 1733 fix timestamping tests

- ansible/README.md
- ansible/hosts/lxd_hosts.txt
- ansible/roles/init-lxd/tasks/main.yml
- ansible/roles/restart-lxd/tasks/main.yml
This patch fixes the above problem by changing the host names in the LXD example inventory and making the path to the socket for connecting to LXD configurable.
> Issue #1054: fix compatibility issues with LXD4 and Fedora.

- src/packages/src/xroad/common/addon/proxy/setup_messagelog_db.sh
- src/packages/src/xroad/common/base/usr/share/xroad/scripts/_backup_xroad.sh
- src/packages/src/xroad/common/base/usr/share/xroad/scripts/_setup_db.sh
- src/packages/src/xroad/common/op-monitor/usr/share/xroad/scripts/setup_opmonitor_db.sh
- src/packages/src/xroad/common/proxy/usr/share/xroad/scripts/backup_db.sh
- src/packages/src/xroad/common/proxy/usr/share/xroad/scripts/get_security_server_id.sh
- src/packages/src/xroad/common/proxy/usr/share/xroad/scripts/restore_db.sh
- src/packages/src/xroad/common/proxy/usr/share/xroad/scripts/setup_serverconf_db.sh
- src/packages/src/xroad/redhat/SOURCES/proxy/xroad-initdb.sh
- src/packages/src/xroad/ubuntu/generic/xroad-addon-messagelog.postinst
- src/packages/src/xroad/ubuntu/generic/xroad-proxy.config
- src/packages/src/xroad/ubuntu/generic/xroad-proxy.postinst
* Refactor installer to better support building a sidecar image (make it
possible to skip database installation).
* Take into account that xroad.properties in a docker container can be a
mounted file (needs to be modifid in-place).
* Make it possible to locate xroad.propeties in /etc/xroad
> XRDDEV-1809: Enhance sidecar support

- src/proxy/src/main/java/ee/ria/xroad/common/util/healthcheck/HealthChecks.java
- src/proxy/src/test/java/ee/ria/xroad/common/util/healthcheck/HealthChecksTest.java
- src/serverconf/src/main/java/ee/ria/xroad/common/conf/serverconf/ServerConf.java
- src/serverconf/src/main/java/ee/ria/xroad/common/conf/serverconf/ServerConfImpl.java
- src/serverconf/src/main/java/ee/ria/xroad/common/conf/serverconf/ServerConfProvider.java
The healthcheck used a cached value that does not react to database
availability.
> XRDDEV-1843: Fix serverconf database healthcheck

- src/packages/src/xroad/common/base/usr/share/xroad/scripts/generate_certificate.sh
CN is limited to 64 characters, and generating a certificate fails
if a fully qualified hostname exceeds that limit. Use the
hostname part as a fallback.
> Fix certificate generation script

- src/proxy-ui-api/frontend/tests/e2e/pages/common/addSubjectsPopup.js
- src/proxy-ui-api/frontend/tests/e2e/pages/endpoints/accessRightsPage.js
- src/proxy-ui-api/frontend/tests/e2e/pages/serviceClients/addSubjectMemberStepPage.js
- src/proxy-ui-api/frontend/tests/e2e/pages/serviceClients/addSubjectServiceStepPage.js
- src/proxy-ui-api/frontend/tests/e2e/pages/serviceClients/serviceClientDetails.js
- src/proxy-ui-api/frontend/tests/e2e/pages/serviceClients/serviceClientsPage.js
- src/proxy-ui-api/frontend/tests/e2e/pages/ssFrontPage.js
- src/proxy-ui-api/frontend/tests/e2e/pages/ssMainPage.js
- src/proxy-ui-api/frontend/tests/e2e/pages/tabs/clientsTab.js
- src/proxy-ui-api/frontend/tests/e2e/pages/tabs/diagnosticsTab.js
- src/proxy-ui-api/frontend/tests/e2e/pages/tabs/keysTab.js
- src/proxy-ui-api/frontend/tests/e2e/pages/tabs/settingsTab.js
This is to remove all unnecessary locateStrategy-object from securityServer -tests. Since we do have default locateStrategy of xpath, it doesn't need to be defined unless different strategy is explicitly used and elements can be saved in shorter format of `locatorAlias : locatorString`instead of 
``` 
locatorAlias: {
selector: locatorString,
locateStrategy: 'xpath'
},
``` 
This saves almost over thousand lines of code from pageobjects.
This is now done and all tests are passing:
https://jenkins.niis.org/view/api-based-ui/job/rest-ui-e2e-tests/900/
> Xrddev 1838 remove unnecessary locate strategies

- ansible/roles/xroad-ca/templates/init.sh
TSA key generate command `openssl genrsa -aes256 -out private/tsa.key.pem 4096` wants user input for passphrase. This stops init.sh.
Removing `-aes256` also makes TSA key consistent with CA and OCSP keys.
> XRDDEV-1716 remove -aes256 parameter

- doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md
- doc/Manuals/ug-syspar_x-road_v6_system_parameters.md
Updated incorrect parameter name `max-loggable-body-size` to `max-loggable-message-body-size`.
> XRDSD-262: Update parameter name to correct one

- src/proxy-ui-api/frontend/src/components/ui/ContextualAlerts.vue
Fixes a but in error notification. 
E2E test didn't catch this so it's probably quite rare use case, but in code the bug is obvious.
> XRDDEV-1950 Fix bug in notification object handling Security Server

- src/common-test/build.gradle
- src/common-util/build.gradle
Related to CVE-2022-25647 vulnerability which doesn't concern X-Road source code as it doesn't utilize any of the following structures:
- com.google.gson.internal.LazilyParsedNumber
- com.google.gson.internal.LinkedHashTreeMap
- com.google.gson.internal.LinkedTreeMap
> XRDDEV-2021 - Update GSON to 2.9.0

- src/packages/src/xroad/ubuntu/generic/control
`libpkcs11wrapper.so` was moved from `xroad-signer` to `xroad-addon-hwtokens`
> XRDDEV-2014 - Fix an issue caused by a dependency diversion introduced by XRDDEV-2014

- src/centralserver/admin-ui/tests/e2e/specs/070-trust-services.js
Extend pause time for trust services test case, so that the element calculation would be correct
> Extend pause time for trust services test case

- src/addons/messagelog/messagelog-addon/src/test/java/ee/ria/xroad/proxy/messagelog/AsicContainerClientRequestProcessorTest.java
- src/common-util/src/test/java/ee/ria/xroad/common/util/filewatcher/FileWatcherRunnerTest.java
- src/monitor/src/main/java/ee/ria/xroad/monitor/executablelister/AbstractExecLister.java
- src/monitor/src/test/java/ee/ria/xroad/monitor/executablelister/PackageListerTest.java
- src/monitor/src/test/java/ee/ria/xroad/monitor/executablelister/ProcessListerTest.java
- src/proxy/src/test/java/ee/ria/xroad/proxy/clientproxy/FastestConnectionSelectingSSLSocketFactoryIntegrationTest.java
Skipping tests which depend on linux native functionality when executing on different os.
Additional TODOs were added to mark places where we could eventually introduce MacOS support
> MacOS compatability improvements

- src/proxy/src/main/java/ee/ria/xroad/proxy/serverproxy/ServerRestMessageProcessor.java
- src/proxy/src/test/java/ee/ria/xroad/proxy/RestProxyTest.java
- Add content-length header based on message body size to the requests that are sent to service provider information system by server proxy.
- Update integrations tests.
JIRA: https://nordic-institute.atlassian.net/browse/XRDDEV-2022
> XRDDEV-2022 Add content-length header by server proxy

- ansible/roles/build-packages/tasks/main.yml
Ansible doesn't have a default source of a docker image. This PR set it. 
Removed `force: yes` as it is a not valid parameter.
> Fix to 1078 issue

- src/common-util/src/main/java/ee/ria/xroad/common/conf/globalconf/ConfigurationDirectory.java
- src/common-util/src/main/java/ee/ria/xroad/common/conf/globalconf/ConfigurationDirectoryV2.java
- src/common-util/src/test/java/ee/ria/xroad/common/conf/globalconf/ConfigurationDirectoryTest.java
- src/packages/src/xroad/redhat/SPECS/xroad-confclient.spec
- src/packages/src/xroad/ubuntu/generic/xroad-confclient.postinst
- Fix the file 'files' is missing from global configuration by generating the file list dynamically when requested.
- Remove the existing `/etc/xroad/globalconf/files` file on configuration client upgrade.
- Update unit tests.
- The bug was originally created by the refactoring task implemented in commit e3e5312e4ad4a5083ab3aae3e84bbeb732b0e193.
- The logic to generate the file list dynamically was taken from [here](https://github.com/nordic-institute/X-Road/blob/d07dfeb774a50c60d7dee1523afd5efefbdd3930/src/configuration-client/src/main/java/ee/ria/xroad/common/conf/globalconf/DownloadedFiles.java#L79-L84).
JIRA: https://nordic-institute.atlassian.net/browse/XRDDEV-2117
> XRDDEV-2117 Fix file missing from global conf bug

- src/e2e-tests/src/intTest/java/org/niis/xroad/test/ui/glue/CommonUiStepDefs.java
- src/e2e-tests/src/intTest/java/org/niis/xroad/test/ui/glue/FrontPageStepDefs.java
- src/e2e-tests/src/intTest/resources/behavior/ui/ssLogin.feature
- src/e2e-tests/src/intTest/resources/behavior/ui/ssLogout.feature
I am trying to recreate tests from Nightwatch to new stack and here are results regarding login and logout suites.
Most obvious issues:
-  I made steps to file `CommonUIStepDefs.java`, I see that naming scheme refers it as "commonUI", which in my understanding refers to pages before login. Now issue is that in logout case, functionalities refering to elements after login (namely session timeout popup and logout-button) are also inside of CommonUIsteps, which is bit incorrrect location-wise, although they seem to work.
- I have understanding that ```@Given("Something is done)```  in step definitions should match usecase in feature-files, eg. if we use it as "Given" then it's created with "Given" step definitions. However, this doesn't seem work, if I use "Then" tests fail on error. 
- …
> Xrddev 2130

- doc/Manuals/ug-syspar_x-road_v6_system_parameters.md
- src/packages/src/xroad/default-configuration/override-securityserver-ee.ini
- Set auth and sign key length to 3072 in EE meta package.
- Update System Parameters User Guide.
JIRA: https://nordic-institute.atlassian.net/browse/XRDDEV-2132
> XRDDEV-2132 Add signer.key-length property to EE meta package

- src/common-util/build.gradle
Update commons-text version from 1.9 to 1.10.0 due to CVE-2022-42889
> Update commons-text version from 1.9 to 1.10.0 due to CVE-2022-42889

- src/common-util/src/main/java/ee/ria/xroad/common/certificateprofile/impl/SkEsteIdCertificateProfileInfoProvider.java
- src/common-util/src/test/java/ee/ria/xroad/common/certificateprofile/impl/SkEsteidCertificateProfileInfoProviderTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/securityserver/restapi/service/CertificateAuthorityServiceTest.java
Marking anything related to the SkEsteIdCertificateProfileInfoProvider as deprecated.
> XRDDEV-2160: Deprecate SkEsteIdCertificateProfileInfoProvider and related tests

- src/central-server/admin-service/ui/src/components/configurationParts/ConfigurationPartDownloadButton.vue
- src/central-server/admin-service/ui/src/locales/en.json
- src/central-server/admin-service/ui/src/store/modules/configuration-sources.ts
- src/central-server/admin-service/ui/src/util/helpers.ts
- src/central-server/admin-service/ui/src/views/GlobalConfiguration/shared/ConfigurationAnchor.vue
https://nordic-institute.atlassian.net/browse/XRDDEV-2227
also added a reusable frontend file download helper function to central server ui based on equivalent security server ui function.
> XRDDEV-2227 re-create and download configuration anchor UI buttons logic

- doc/Manuals/LoadBalancing/ig-xlb_x-road_external_load_balancer_installation_guide.md
- src/proxy/src/main/java/ee/ria/xroad/common/util/healthcheck/HealthCheckPort.java
https://nordic-institute.atlassian.net/browse/XRDDEV-2217
Also removed socket linger time from the connector since it's deprecated at not used anymore in jetty 9
> Xrddev 2217 Make healthcheck endpoint not return jetty version in header

- src/packages/src/xroad/common/base/usr/share/xroad/db/liquibase.sh
- src/packages/src/xroad/redhat/SPECS/xroad-base.spec
- src/packages/src/xroad/ubuntu/generic/xroad-base.links
liquibase.sh was capable of selecting multiple jars to use. This is not intended behavior as single jar is sufficient. This simplifies selection process and makes it safer.
Refs: XRDDEV-2283
> fix: add strict liquibase jar selector

- src/central-server/admin-service/infra-api-rest/src/main/java/org/niis/xroad/cs/admin/rest/api/openapi/SecurityServersApiController.java
- src/central-server/openapi-model/src/main/resources/openapi-definition.yaml
Removed the get security server authentication certificate detail endpoint as this was not needed. The list query already returned all the required information.
Refs: XRDDEV-2260
> feat: API for getting the details of an authentication certificate related to a Security Server

- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/CentralServerConfigurationRestorationService.java
- src/central-server/admin-service/core/src/test/java/org/niis/xroad/cs/admin/core/service/CentralServerConfigurationRestorationServiceTest.java
- src/central-server/admin-service/ui/src/locales/en.json
https://nordic-institute.atlassian.net/browse/XRDDEV-2318
> fix: During restoration take instance identifier from DB instead of Globalconf as the latter might not be initialized

- src/central-server/admin-service/ui/src/views/InitialConfiguration/InitialConfiguration.vue
Fixes e2e tests
Refs: XRDDEV-2321
> chore: success icon for software token pin on CS initialization page wasn't showing

- src/center-common/Gemfile
- src/center-common/Gemfile.lock
- src/center-ui/Gemfile.lock
- src/common-ui/Gemfile
- src/common-ui/Gemfile.lock
http endpoint is unreliable and during dependency api deprecation it throws network errors.
> fix: change rubygems to https address

- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/entity/GlobalGroupMemberEntity.java
- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/GlobalGroupServiceImpl.java
- src/central-server/admin-service/infra-jpa/src/main/java/org/niis/xroad/cs/admin/jpa/repository/JpaFlattenedSecurityServerClientRepository.java
create copy of identifier when adding new member to group, filter possible members by instance/class/member[/subsystem] of already added members
Refs: XRDDEV-2342
> fix(cs:api): fixes for member adding to global group to be consistent with old version

- src/central-server/admin-service/core-api/src/main/java/org/niis/xroad/cs/admin/api/dto/ConfigurationAnchorWithFile.java
- src/central-server/admin-service/core-api/src/main/java/org/niis/xroad/cs/admin/api/service/ConfigurationAnchorService.java
- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/ConfigurationAnchorServiceImpl.java
- src/central-server/admin-service/core/src/test/java/org/niis/xroad/cs/admin/core/service/ConfigurationAnchorServiceImplTest.java
- src/central-server/admin-service/infra-api-rest/src/main/java/org/niis/xroad/cs/admin/rest/api/openapi/ConfigurationSourceAnchorsController.java
- src/central-server/admin-service/int-test/src/intTest/java/org/niis/xroad/cs/test/glue/ConfigurationInfoApiStepDefs.java
- src/central-server/admin-service/int-test/src/intTest/java/org/niis/xroad/cs/test/glue/ConfigurationSourceAnchorApiStepDefs.java
- src/central-server/admin-service/int-test/src/intTest/resources/behavior/api/configurationInfoApis.feature
https://nordic-institute.atlassian.net/browse/XRDDEV-2367
Configuration anchor file name generated by the Central Server is missing instance identifier and configuration anchor type (internal/external)
> fix: incorrect central server anchor filename

- doc/Manuals/ig-cs_x-road_6_central_server_installation_guide.md
- doc/Manuals/ig-csha_x-road_6_ha_installation_guide.md
- doc/Manuals/ug-cs_x-road_6_central_server_user_guide.md
Updates database properties in Central Server manuals to correspond with the new style set in [XRDDEV-2422](https://nordic-institute.atlassian.net/browse/XRDDEV-2422).
[XRDDEV-2422]: https://nordic-institute.atlassian.net/browse/XRDDEV-2422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: update database properties in manuals

- src/packages/src/xroad/redhat/SPECS/xroad-base.spec
- src/packages/src/xroad/ubuntu/generic/xroad-base.preinst
X-Road version < 6.26 had JAVA_HOME pointing to Java 8 set in global.conf, install scripts in version 6.26 migrated it to local.conf. X-Road 7.3 does not support Java 8 any more, therefore JAVA_HOME setting needs to be removed.
Refs: XRDDEV-2442
> fix: remove JAVA_HOME from local.conf if it's pointing to java < 11

- ansible/ss_cluster/roles/master/tasks/serverconf_master_db.yml
- ansible/ss_cluster/roles/slave/tasks/serverconf_slave_db.yml
Starting from Postgresql 13, there has been a parameter rename and value change. 
https://www.postgresql.org/docs/13/release-13.html
wal_keep_size = wal_keep_segments * wal_segment_size (typically 16MB)
Latest X-Road is using Postgresql 14 and also needs to rename this parameter.
> Fix: Rename configuration parameter wal_keep_segments to wal_keep_size

- ansible/roles/xroad-base/tasks/rhel.yml
tzdata-java dependency is missing in this particular version, until this is fixed we can just install it through ansible.
> chore: Workaround for rhel java 11.0.20.0.8-2

- src/packages/src/xroad/redhat/SPECS/xroad-base.spec
tzdata-java is no longer a dependency for java-11-openjdk-11.0.20.0.8-2 rpm package, but it is still required to run java. As a workaround, tzdata-java is added as dependency to xroad-base package. See https://access.redhat.com/solutions/7025428
refs: XRDDEV-2458
> fix: add tzdata-java dependency for rpm packages

- .github/workflows/run_tests.yaml
- src/build.gradle
- src/gradle.properties
Added support for running SonarQube tests in the SonarCloud environment, which required defining the related properties inside `gradle.properties` instead of `build.gradle`. This allows us to override them via the command line. The defaults were left to our internal SonarQube so that Jenkins pipelines would continue to work for now.
Also introduced scanning with SonarCloud to the X-Road testing workflow on GitHub.
> Add SonarCloud support

- CONTRIBUTING.md
- sidecar/SIDECAR.md
I changed the descriptions so that most service desk reports should go to either GitHub's issues or discussions.
Security reports should still go to the private service desk on JIRA.
Also did some minor formatting changes to the documents I touched and removed some portions from the Sidecar main readme that didn't seem relevant to be there now that it is a part of the core repository.
> chore: change community issue and change request reporting practices

- doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md
This change will replace command in documentation regarding finding the X-Road Securityserver ID for command line restore section.
It's necessary since ID cannot be extracted from backup(gpg) files anymore.
> Fix documentation for finding xroad id for cmd conf restore

- src/addons/messagelog/messagelog-addon/src/main/java/ee/ria/xroad/proxy/messagelog/TaskQueue.java
Security server never recovered from timestamping service outage in case there were no messages timestamp in database.
Refs: XRDDEV-2398
> fix: allow recovering from timestamping service failure

- src/proxy/src/main/java/ee/ria/xroad/proxy/antidos/AntiDosConnectionManager.java
- src/security-server/admin-service/ui/package-lock.json
- src/security-server/admin-service/ui/package.json
- src/shared-ui/package-lock.json
- src/shared-ui/package.json
fix an issue where cpuLoad returns NaN which leads to AntiDos protection being triggerred.
This behavior was noted in JDK17 on MacOS.
> chore: fix an issue where cpuLoad returns NaN

- doc/Manuals/ug-syspar_x-road_v6_system_parameters.md
- Add missing command line argument to the supported command line arguments list.
> docs: Update system parameters guide

- src/common/common-verifier/src/main/java/ee/ria/xroad/common/conf/globalconf/GlobalConfImpl.java
- src/common/common-verifier/src/test/java/ee/ria/xroad/common/conf/globalconf/GlobalConfTest.java
> fix: Avoid throwing exception when target shared parameters non existent during global group check

- src/packages/src/xroad/common/center-management-service/etc/xroad/nginx/management-service.conf
- src/packages/src/xroad/common/center-registration-service/etc/xroad/nginx/registration-service.conf
Spring Boot 3 (Spring 6) changed the way trailing slashes are treated in in URL-s. Before, URL with trailing slash was treated as equal to one without it.
Refs: XRDDEV-2491
> fix: nginx forward management requests without trailing slash in URL

- src/common/common-util/src/main/java/ee/ria/xroad/common/conf/globalconf/VersionedConfigurationDirectory.java
- src/common/common-util/src/main/java/ee/ria/xroad/common/util/CertHashBasedOcspResponderClient.java
- src/common/common-util/src/main/java/ee/ria/xroad/common/util/CertUtils.java
- src/common/common-util/src/main/java/ee/ria/xroad/common/util/CryptoUtils.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/clientproxy/AuthTrustVerifier.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/conf/KeyConfImpl.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/util/CertHashBasedOcspResponder.java
- src/security-server/admin-service/application/src/main/java/org/niis/xroad/securityserver/restapi/service/CertificateAuthorityService.java
- src/signer/src/intTest/java/org/niis/xroad/signer/test/glue/SignerStepDefs.java
- src/signer/src/main/java/ee/ria/xroad/signer/certmanager/OcspClientWorker.java
- src/signer/src/main/java/ee/ria/xroad/signer/certmanager/OcspResponseManager.java
- src/signer/src/main/java/ee/ria/xroad/signer/model/Cert.java
- src/signer/src/main/java/ee/ria/xroad/signer/protocol/handler/ImportCertReqHandler.java
- src/signer/src/main/java/ee/ria/xroad/signer/tokenmanager/TokenManager.java
- src/signer/src/main/java/ee/ria/xroad/signer/tokenmanager/module/AbstractModuleManager.java
- src/signer/src/main/java/ee/ria/xroad/signer/util/SignerUtil.java
- src/signer/src/test/java/ee/ria/xroad/signer/tokenmanager/TokenManagerMergeTest.java
> fix: restore OCSP responses to work with sha1 cert hashes for backwards compatibility

- src/packages/src/xroad/ubuntu/generic/xroad-proxy.postinst
- src/packages/src/xroad/ubuntu/generic/xroad-proxy.preinst
- src/packages/src/xroad/ubuntu/generic/xroad-securityserver-ee.postinst
> fix: wrong proxy client http ports value is read  during initial startup after 7.4 install or upgrade because of race conditions in maintainer scripts

- src/central-server/admin-service/ui/package.json
- src/central-server/admin-service/ui/yarn.lock
- src/security-server/admin-service/ui/package.json
- src/security-server/admin-service/ui/yarn.lock
- src/serverconf/build.gradle
As discovered by an analysis with ORT [1], the `hibernate-tools` dependency does not exist in the currently set version "6.2.9.Final", making the `:serverconf:schemaExport` Gradle task fail. It was only available until version "5.6.15.Final", see [2]. The successor providing `org.hibernate.tool.ant.HibernateToolTask` seems to be `hibernate-tools-ant` [3], so use that instead.
However, this does not fully fix running `:serverconf:schemaExport` as it still fails with
* What went wrong:
Execution failed for task ':serverconf:schemaExport'.
> java.lang.NoClassDefFoundError: ee/ria/xroad/common/identifier/ClientId$Conf
which is something that needs to be investigated separately.
[1]: https://github.com/oss-review-toolkit/ort
[2]: https://mvnrepository.com/artifact/org.hibernate/hibernate-tools …
> fix(serverconf): Correct the `hibernate-tools` dependency

- sidecar/files/balancer-secondary-entrypoint.sh
> fix: generating internal gRPC keys in Sidecar secondary images

- src/packages/src/xroad/ubuntu/generic/xroad-center.postinst
- src/packages/src/xroad/ubuntu/generic/xroad-centralserver.postinst
internal.crt file was migrated to management-service.crt in xroad-center.postinst, but related ngingx configurations were in management-service and registration-service packages. This caused nginx failing to restart because of invalid configuration.
Refs: XRDDEV-2553
> fix: nginx fails to restart after upgrade

- src/central-server/admin-service/core-api/src/main/java/org/niis/xroad/cs/admin/api/domain/ConfigurationSigningKey.java
- src/central-server/admin-service/core-api/src/main/java/org/niis/xroad/cs/admin/api/service/ConfigurationService.java
- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/ConfigurationServiceImpl.java
- src/central-server/admin-service/core/src/test/java/org/niis/xroad/cs/admin/core/service/ConfigurationServiceImplTest.java
- src/central-server/admin-service/globalconf-generator/src/main/java/org/niis/xroad/cs/admin/globalconf/generator/SharedParametersLoader.java
- src/central-server/admin-service/globalconf-generator/src/test/java/org/niis/xroad/cs/admin/globalconf/generator/SharedParametersLoaderTest.java
> fix: Ensure consistent order for configuration signing keys in shared params to prevent its hash dynamism

- src/addons/hwtoken/src/main/java/ee/ria/xroad/signer/tokenmanager/module/HardwareModuleWorker.java
- src/central-server/admin-service/ui-system-test/src/intTest/resources/application-override.yml
- src/security-server/system-test/src/intTest/resources/application-override.yml
- src/signer/src/main/java/ee/ria/xroad/signer/tokenmanager/module/AbstractModuleManager.java
- src/signer/src/main/java/ee/ria/xroad/signer/tokenmanager/module/AbstractModuleWorker.java
> fix: improved error handling in signer module loading

- src/build.gradle
- src/gradle.properties
This adds a dependency to run the coverage report to the `sonar` task and updates the path to the correct one. Additionally, I updated the default sonar host to `sonarcloud.io` since we no longer have an internal instance.
Fixes issue where `sonarcloud.io` always reports coverage as 0%.
> chore: fix missing code coverage issue for SonarQube

- .github/dependabot.yml
Noticed that I had added the grouping rules for javascript under the wrong block.
> chore: fix dependabot grouping rules, update github-actions update rules

- doc/Manuals/ug-syspar_x-road_v6_system_parameters.md
- src/packages/src/xroad/default-configuration/override-securityserver-fi.ini
For FI package
Closes: XRDDEV-2621
> chore: update default value for acceptable-timestamp-failure-period

- src/central-server/admin-service/globalconf-generator/src/main/java/org/niis/xroad/cs/admin/globalconf/generator/SharedParametersLoader.java
- src/central-server/admin-service/globalconf-generator/src/test/java/org/niis/xroad/cs/admin/globalconf/generator/SharedParametersLoaderTest.java
- src/common/common-globalconf/build.gradle
- src/common/common-globalconf/src/main/java/ee/ria/xroad/common/conf/globalconf/CertHash.java
- src/common/common-globalconf/src/main/java/ee/ria/xroad/common/conf/globalconf/SharedParameters.java
- src/common/common-globalconf/src/main/java/ee/ria/xroad/common/conf/globalconf/SharedParametersCache.java
- src/common/common-globalconf/src/main/java/ee/ria/xroad/common/conf/globalconf/SharedParametersV2Converter.java
- src/common/common-globalconf/src/main/java/ee/ria/xroad/common/conf/globalconf/SharedParametersV2ToXmlConverter.java
- src/common/common-globalconf/src/main/java/ee/ria/xroad/common/conf/globalconf/SharedParametersV3Converter.java
- src/common/common-globalconf/src/main/java/ee/ria/xroad/common/conf/globalconf/SharedParametersV3ToXmlConverter.java
- src/common/common-globalconf/src/main/java/ee/ria/xroad/common/conf/globalconf/SharedParametersV4Converter.java
- src/common/common-globalconf/src/main/java/ee/ria/xroad/common/conf/globalconf/SharedParametersV4ToXmlConverter.java
- src/common/common-globalconf/src/test/java/ee/ria/xroad/common/conf/globalconf/CertHashTest.java
- src/common/common-globalconf/src/test/java/ee/ria/xroad/common/conf/globalconf/SharedParametersMarshallRoundTripTest.java
- src/common/common-globalconf/src/test/java/ee/ria/xroad/common/conf/globalconf/SharedParametersV2ToXmlConverterTest.java
- src/common/common-globalconf/src/test/java/ee/ria/xroad/common/conf/globalconf/SharedParametersV3ToXmlConverterTest.java
- src/common/common-globalconf/src/test/java/ee/ria/xroad/common/conf/globalconf/SharedParametersV4ToXmlConverterTest.java
- src/gradle/libs.versions.toml
Security server authentication cert hashes were hashed again when global configuration was rewritten to disk. Bug appeared in configuration proxy federated setup.
Refs: XRDDEV-2534
> fix: ensure that auth cert hashes are not hashed again

- src/packages/src/xroad/common/center/usr/share/xroad/scripts/backup_db.sh
> fix: do not print out DB user password on backup

- usage_scenario.yml
Updates `usage_scenarios.yml` to point to correct path the Hurl Dockerfile.
> chore: fix hurl Dockerfile path in GMT usage_scenarios.yml broke with PR #2234

- doc/Sidecar/security_server_sidecar_user_guide.md
- src/common/common-core/src/main/java/ee/ria/xroad/common/SystemProperties.java
- src/security-server/admin-service/application/src/main/java/org/niis/xroad/securityserver/restapi/config/AcmeConfig.java
- src/security-server/admin-service/application/src/main/java/org/niis/xroad/securityserver/restapi/config/AcmeProperties.java
- src/security-server/admin-service/application/src/test/java/org/niis/xroad/securityserver/restapi/config/AcmeConfigTest.java
> XRDDEV-2689: Ignore unknown ACME properties and adding ACME enabling info to sidecar documentation

- src/shared-ui/audit-ci-shared.json
Ignoring the following CVEs for release 7.3:
* https://github.com/advisories/GHSA-qwcr-r2fm-qrc7
* https://github.com/advisories/GHSA-9wv6-86v2-598j
To fix pipeline for release-7.3 (e.g., https://jenkins.niis.org/job/xroad-build-packages-pipeline/7250/)
> fix: Ignore latest security  issues to enable build

- src/build.gradle
- src/central-server/admin-service/infra-api-rest/src/main/java/org/niis/xroad/cs/admin/rest/api/security/TargetTypeResolver.java
- src/common/common-core/src/main/java/ee/ria/xroad/common/util/MimeUtils.java
- src/proxy/application/src/intTest/java/org/niis/xroad/proxy/test/glue/ProxyStepDefs.java
- src/proxy/application/src/main/java/ee/ria/xroad/proxy/clientproxy/ClientRestMessageProcessor.java
- src/proxy/application/src/main/java/ee/ria/xroad/proxy/clientproxy/FastestConnectionSelectingSSLSocketFactory.java
- src/proxy/application/src/main/java/ee/ria/xroad/proxy/protocol/ProxyMessageDecoder.java
- src/security-server/admin-service/application/src/main/java/org/niis/xroad/securityserver/restapi/openapi/EndpointsApiController.java
- src/security-server/admin-service/application/src/main/java/org/niis/xroad/securityserver/restapi/openapi/MemberClassesApiController.java
- src/security-server/admin-service/application/src/main/java/org/niis/xroad/securityserver/restapi/service/AccessRightService.java
- src/security-server/admin-service/application/src/test/java/org/niis/xroad/securityserver/restapi/converter/PossibleActionConverterTest.java
- src/security-server/admin-service/application/src/test/java/org/niis/xroad/securityserver/restapi/openapi/ApiValidationRestTemplateTest.java
- src/security-server/admin-service/application/src/test/java/org/niis/xroad/securityserver/restapi/openapi/KeysApiControllerTest.java
- src/security-server/admin-service/application/src/test/java/org/niis/xroad/securityserver/restapi/openapi/MemberClassesApiControllerIntegrationTest.java
- src/security-server/admin-service/application/src/test/java/org/niis/xroad/securityserver/restapi/openapi/TokenCertificatesApiControllerIntegrationTest.java
- src/security-server/admin-service/application/src/test/java/org/niis/xroad/securityserver/restapi/service/ClientServiceIntegrationTest.java
- src/security-server/admin-service/application/src/test/java/org/niis/xroad/securityserver/restapi/service/OrphanRemovalServiceTest.java
- src/security-server/admin-service/application/src/test/java/org/niis/xroad/securityserver/restapi/service/TokenCertificateServiceTest.java
- src/security-server/admin-service/application/src/test/java/org/niis/xroad/securityserver/restapi/util/TestUtils.java
- src/security-server/admin-service/application/src/test/java/org/niis/xroad/securityserver/restapi/wsdl/WsdlValidatorTest.java
* Add compilerArgument to the JavaTask in Gradle to enable different compilation warnings. e.g., `unchecked`, `deprecation`, etc.
* Fix minor warnings that does not affect the behavior
* Comment out some of the warnings to reduce logs until proper fix is applied
> chore: Enable compiler warnings and apply minor fixes

- src/packages/src/xroad/ubuntu/generic/control
acme2certifier used by Test CA uses nginx module that is missing from nginx-light, but present in nginx-core. But on some of our testservers Test CA and CS sit on the same server and CS install adds nginx-light, since it is it's dependency. It does that even when nginx-core is already present. Nginx-light installation removes nginx-core and vice versa. 
This change adds nginx-core as an alternative dependency so that when it is present on the server, it doesn't add nginx-light, which makes sense, because nginx-core already has all the functionality that nginx-light has. 
When installing CS without neither nginx versions present, it installed nginx-light like before (Tested on local docker container with Noble.)
> fix: Test CA and CS nginx mismatch causes testservers to fail when setup

- src/common/common-domain/src/main/java/org/niis/xroad/common/exception/util/CommonDeviationMessage.java
- src/security-server/admin-service/application/src/main/java/org/niis/xroad/securityserver/restapi/config/AcmeChallangeFilter.java
- src/security-server/admin-service/application/src/main/java/org/niis/xroad/securityserver/restapi/controller/AcmeChallengeController.java
As a Developer I want to disable port 4000 for ACME challenges so that we don't expose it needlessly;
As a Developer I want to harden the way we handle use input in ACME challenges so that we don't leave a potential opening in the future
refs: XRDDEV-2732, XRDDEV-2733
> feat: Acme challenge improvements based on security audit

- src/security-server/admin-service/ui/src/components/ui/HelpButton.vue
- src/security-server/admin-service/ui/src/locales/en.json
- src/security-server/admin-service/ui/src/views/Diagnostics/DiagnosticsMailNotificationCard.vue
- src/security-server/admin-service/ui/src/views/KeysAndCertificates/ApiKey/ApiKey.vue
- src/security-server/admin-service/ui/src/views/KeysAndCertificates/SecurityServerTlsCertificate/SecurityServerTlsCertificate.vue
- src/security-server/admin-service/ui/src/views/KeysAndCertificates/SignAndAuthKeys/SignAndAuthKeys.vue
- Moved HelpButton to `components/ui/HelpButton.vue` from the original Keys and Certificates subview since it is a common component
- Made the help image optional since it is not required for all cases of help text
- Added help text to the mail notifications block to make it clearer which cases it will be used for
> chore: update diagnostic group title to add help text for clarity

- doc/DataModels/dm-cs_x-road_central_server_configuration_data_model.md
- doc/DataModels/dm-ml_x-road_message_log_data_model.md
- doc/Manuals/ug-cs_x-road_6_central_server_user_guide.md
- doc/Manuals/ug-sec_x_road_security_hardening.md
- doc/OperationalMonitoring/Architecture/arc-opmond_x-road_operational_monitoring_daemon_architecture_Y-1096-1.md
- doc/OperationalMonitoring/Protocols/pr-opmon_x-road_operational_monitoring_protocol_Y-1096-2.md
- doc/OperationalMonitoring/Protocols/pr-opmonjmx_x-road_operational_monitoring_jmx_protocol_Y-1096-3.md
Resolves the issue with heading levels being incorrect in various documents.
Also changed how the image is included in OpMon daemons architecture document so that it is properly included.
> chore: fix issues in X-Road documentation

- src/lib/globalconf-core/src/main/java/org/niis/xroad/globalconf/extension/OcspFetchInterval.java
- src/lib/globalconf-core/src/main/java/org/niis/xroad/globalconf/extension/OcspNextUpdate.java
Found `java.lang.IllegalAccessException: class org.niis.xroad.globalconf.impl.extension.GlobalConfExtensionLoaderImpl cannot access a member of class org.niis.xroad.globalconf.extension.OcspFetchInterval with package access` error from ec2 dev env signer logs while doing janitor things.
> fix: global conf extension loader gets a reflection error because of package access

- src/packages/src/xroad/common/op-monitor/etc/xroad/services/opmonitor.conf
> fix: xroad-opmonitor runs into Out-Of-Memory exceptions

- .github/CODEOWNERS
- .github/dependabot.yml
Making the change due to https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/.
Info on the CODEOWNERS file: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
If I understand correctly, this should also mean that all PR-s will automatically get the `xrd-developers` reviewer added to them.
Additionally made it so markdown files need to be also reviewed by me and @petkivim, as those are documentation changes.
Any changes to `CODEOWNERS` itself must always be reviewed by me or @petkivim.
> feat: switch to using CODEOWNERS due to reviewers deprecation in dependaboy.yml

- src/central-server/admin-service/ui/src/locales/pt-BR.json
- src/security-server/admin-service/ui/src/locales/pt-BR.json
- src/shared-ui/src/locales/pt-BR.json
Hi @ovidijusnortal,
I have reviewed and updated all `pt-BR.json` translation files, aligning them with both `develop` and `en.json`. This PR includes:
- Full translation and update of technical and notification fields (`ACME_FAILURE`, `ACME_SUCCESS`, etc.)
- Corrections for missing or inconsistent fields (`forbiddenDisable`, maintenance mode keys, etc.)
- Restoration of missing error blocks (`403`, `404`)
- Standardization, deduplication, and structure alignment with `en.json`
- Final review and sync for production readiness
Let me know if any further adjustments are needed.  
Thanks for your support!
> feat(i18n): revisão e sincronização dos arquivos de tradução pt-BR.json
