nordic-institute/X-Road

- src/build.gradle
- Update SonarQube Gradle plugin version
- Update SonarQube properties in `build.gradle`
> XRDDEV-32 Update SonarQube properties

- src/center-ui/config/locales/controllers_en.yml
- src/proxy-ui/config/locales/controllers_en.yml
https://jira.niis.org/browse/XRDDEV-53
> XRDDEV-53 Fixed error message

- doc/Manuals/ug-cs_x-road_6_central_server_user_guide.md
https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ug-cs_x-road_6_central_server_user_guide.md#162-ocsp-fetch-interval
> Fix incorrect ocspFetchInterval default value in CS User Guide.

- src/center-ui/build.gradle
- src/center-ui/public/javascripts/securityserver_edit.js
- src/common-ui/build.gradle
- src/proxy-ui/build.gradle
- src/proxy-ui/public/javascripts/groups.js
https://jira.niis.org/browse/XRDDEV-116
> XRDDEV-116 Add javascript sources for sonarqube analysis

- src/proxy/src/main/java/ee/ria/xroad/proxy/ProxyMain.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/util/GlobalConfUpdater.java
- Periodic update of global configuration
> XRDDEV-105

- src/addons/messagelog/src/test/java/ee/ria/xroad/proxy/messagelog/SoapMessageBodyManipulatorTest.java
- src/addons/metaservice/src/main/java/ee/ria/xroad/proxy/serverproxy/MetadataServiceHandlerImpl.java
- src/addons/proxymonitor/metaservice/src/main/java/ee/ria/xroad/proxy/serverproxy/ProxyMonitorServiceHandlerImpl.java
- src/common-util/src/main/java/ee/ria/xroad/common/hashchain/HashChainVerifier.java
- src/common-util/src/main/java/ee/ria/xroad/common/message/SaxSoapParserImpl.java
- src/common-util/src/main/java/ee/ria/xroad/common/signature/Helper.java
- src/common-util/src/main/java/ee/ria/xroad/common/util/XmlUtils.java
- src/common-util/src/test/java/ee/ria/xroad/common/identifier/IdentifierTypeConverterTest.java
- src/common-util/src/test/java/ee/ria/xroad/common/util/XmlUtilsTest.java
- src/proxy/src/test/java/ee/ria/xroad/proxy/util/MetaserviceTestUtil.java
https://jira.niis.org/browse/XRDDEV-117
> XRDDEV-117

- src/proxy/src/main/java/ee/ria/xroad/proxy/clientproxy/ClientMessageProcessor.java
- src/proxy/src/test/java/ee/ria/xroad/proxy/testsuite/testcases/SslSelectFastestProxy.java
- src/proxy/src/test/java/ee/ria/xroad/proxy/testsuite/testcases/SslSelectFastestProxyNoConnections.java
Fix fastest host selection can fail if some of the hostnames fails to
resolve.
> XRDDEV-141: Fix host selection failure

- ansible/roles/xroad-base/tasks/ubuntu.yml
- ansible/vars_files/local_repo.yml
- ansible/vars_files/remote_repo.yml
- Add bionic support for Ansible script `xroad_init.yml`
> XRDDEV-160

- src/proxy/src/main/java/ee/ria/xroad/proxy/clientproxy/ClientProxy.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/clientproxy/FastestConnectionSelectingSSLSocketFactory.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/serverproxy/ServerProxy.java
- src/proxy/src/test/java/ee/ria/xroad/proxy/clientproxy/FastestConnectionSelectingSSLSocketFactoryIntegrationTest.java
- src/proxy/src/test/java/ee/ria/xroad/proxy/testsuite/testcases/SslClientCipherSuiteSetupError.java
https://jira.niis.org/browse/XRDDEV-165
> XRDDEV-165

- doc/Protocols/pr-meta_x-road_service_metadata_protocol.md
Update X-Road Service Metadata Protocol:
- Update targetNamespace in Annex B.
- Update Annex B's ToC link.
- Update document's version number.
> XRDDEV-138

- src/proxy/src/main/java/ee/ria/xroad/proxy/clientproxy/FastestSocketSelector.java
* Do not try to connect to hosts with an unresolvable address
* Fix potential resource leak in FastestSocketSelector
> XRDDEV-220: Fix intermittent connection timeout in proxy tests.

- ansible/README.md
- ansible/roles/xroad-base/tasks/ubuntu.yml
- ansible/roles/xroad-ca/tasks/main.yml
- src/packages/src/xroad/redhat/SPECS/xroad-base.spec
- src/packages/src/xroad/redhat/SPECS/xroad-confclient.spec
- src/packages/src/xroad/redhat/SPECS/xroad-signer.spec
- Automatically detect the Ubuntu version to be installed on the target servers
- Add documentation
- Fix xroad-monitor not autostarting on RHEL
> XRDDEV-160 Autodetect Ubuntu version

- src/asicverifier/src/main/java/ee/ria/xroad/asicverifier/AsicVerifierMain.java
Add extract message prompt to asicverifier when message signature cannot be verified.
- Add new extractMessage method.
- Invoke extractMessage method despite the result of verification.
> XRDDEV-192

- ansible/ss_cluster/roles/node/tasks/ubuntu.yml
- ansible/ss_cluster/roles/slave/tasks/main.yml
- ansible/ss_cluster/roles/slave/tasks/ubuntu.yml
- doc/Manuals/LoadBalancing/ig-xlb_x-road_external_load_balancer_installation_guide.md
Support creating a Ubuntu 18.04 security server cluster
> XRDDEV-170

- src/center-ui/app/controllers/feedback_controller.rb
- src/center-ui/app/helpers/application_helper.rb
- src/center-ui/config/locales/controllers_en.yml
- src/center-ui/config/locales/controllers_et.yml
- src/center-ui/config/locales/views_en.yml
- src/center-ui/config/locales/views_et.yml
- src/common-ui/app/views/feedback/index.html.erb
- src/proxy-ui/app/controllers/feedback_controller.rb
- src/proxy-ui/app/helpers/application_helper.rb
- src/proxy-ui/config/locales/controllers_en.yml
- src/proxy-ui/config/locales/views_en.yml
* feedback menu item
* page content (text and links)
> XRDDEV-232 Feedback page

- src/common-ui/app/helpers/base_helper.rb
- src/common-ui/app/views/layouts/partials/_header_actions.html.erb
* remove unnecessary wrapper method when rendering page heading
> XRDDEV-168 SonarQube Ruby issue

- doc/Manuals/ug-sigdoc_x-road_signed_document_download_and_verification_manual.md
- src/asicverifier/build.gradle
- src/asicverifier/src/main/java/ee/ria/xroad/asicverifier/AsicVerifierMain.java
- src/packages/src/xroad/redhat/SPECS/xroad-addon-messagelog.spec
- src/packages/src/xroad/ubuntu/generic/xroad-addon-messagelog.install
- src/packages/src/xroad/ubuntu/generic/xroad-addon-messagelog.links
* check AsicVerifier version with the version arg
* version string removed from AsicVerifier.jar
> XRDDEV-256

- doc/Manuals/LoadBalancing/ig-xlb_x-road_external_load_balancer_installation_guide.md
Update cluster rolling upgrade instructions
> XRDDEV-222

- src/packages/src/xroad/common/proxy/usr/share/xroad/db/serverconf/7-servicedescription.xml
- use liquibase command for adding the column
> XRDDEV-263

- src/common-db/build.gradle
- src/common-db/src/main/java/ee/ria/xroad/common/db/DatabaseCtx.java
- src/common-db/src/main/java/ee/ria/xroad/common/db/HibernateUtil.java
- src/packages/src/xroad/redhat/SPECS/xroad-base.spec
- src/packages/src/xroad/ubuntu/generic/xroad-base.install
- src/packages/src/xroad/ubuntu/generic/xroad-base.links
- src/proxy-ui/app/controllers/application_controller.rb
- src/serverconf/build.gradle
* Update Hibernate to version 5.1.17
* Update PostgreSQL JDBC driver to 42.2.5
> XRDDEV-341: Update Hibernate

- src/addons/proxymonitor/metaservice/src/main/java/ee/ria/xroad/proxy/serverproxy/ProxyMonitorServiceHandlerImpl.java
- Log environmental monitoring request message on the provider security server
> XRDDEV-380

- CHANGELOG.md
- src/common-util/src/main/java/ee/ria/xroad/common/util/CertHashBasedOcspResponderClient.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/clientproxy/FastestConnectionSelectingSSLSocketFactory.java
XTE-432: Fix resource leak - close discarded socket.
> Estonian-6.21.0-1

- doc/Protocols/pr-rest_x-road_message_protocol_for_rest.md
- src/common-util/src/main/java/ee/ria/xroad/common/ErrorCodes.java
- src/common-util/src/main/java/ee/ria/xroad/common/message/RestRequest.java
- src/common-util/src/main/java/ee/ria/xroad/common/message/RestResponse.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/clientproxy/ClientRestMessageProcessor.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/serverproxy/ServerRestMessageProcessor.java
Add x-request-id (unique id for each rest request) to x-road message protocol
> XRDDEV-419

- src/common-util/src/main/java/ee/ria/xroad/common/message/RestMessage.java
- src/common-util/src/main/java/ee/ria/xroad/common/message/RestRequest.java
- src/common-util/src/test/java/ee/ria/xroad/common/message/RestRequestTest.java
- src/common-util/src/test/java/ee/ria/xroad/common/message/RestResponseTest.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/clientproxy/ClientRestMessageProcessor.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/protocol/ProxyMessageDecoder.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/protocol/ProxyMessageEncoder.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/serverproxy/HttpClientCreator.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/serverproxy/ServerRestMessageProcessor.java
- src/proxy/src/test/java/ee/ria/xroad/proxy/RestProxyTest.java
Fix differences from specification
> XRDDEV-418

- src/packages/src/xroad/redhat/SOURCES/opmonitor/xroad-opmonitor-initdb.sh
- src/packages/src/xroad/redhat/SPECS/xroad-opmonitor.spec
Fix op-monitor DB migrations not run on upgrade or reinstall
> XRDDEV-423

- src/common-util/src/main/java/ee/ria/xroad/common/util/HttpSender.java
Changes made according to sonarcube suggestions
> XRDDEV-411: Prevent duplication

- doc/Architecture/arc-g_x-road_arhitecture.md
- doc/Architecture/arc-ss_x-road_security_server_architecture.md
- doc/Architecture/arc-tec_x-road_technologies.md
- doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md
- doc/terms_x-road_docs.md
Documentation updates regarding REST support to the following documents:
- Security Server User Guide
- Architecture documents
> Beta 6.21.0 documentation updates

- src/addons/messagelog/src/main/java/ee/ria/xroad/proxy/messagelog/LogArchiver.java
- src/addons/messagelog/src/main/java/ee/ria/xroad/proxy/messagelog/LogCleaner.java
- src/addons/messagelog/src/main/java/ee/ria/xroad/proxy/messagelog/LogRecordManager.java
- src/addons/messagelog/src/test/java/ee/ria/xroad/proxy/messagelog/MessageLogTest.java
- src/addons/messagelog/src/test/java/ee/ria/xroad/proxy/messagelog/TestUtil.java
- src/addons/messagelog/src/test/resources/logback.xml
- src/build.gradle
- src/common-db/build.gradle
- src/common-db/src/main/java/ee/ria/xroad/common/db/HibernateUtil.java
- src/gradle.properties
- src/op-monitor-daemon/src/main/java/ee/ria/xroad/opmonitordaemon/OperationalDataRecord.java
- src/op-monitor-daemon/src/main/java/ee/ria/xroad/opmonitordaemon/OperationalDataRecordManager.java
- src/op-monitor-daemon/src/main/java/ee/ria/xroad/opmonitordaemon/OperationalDataRecordQuery.java
- src/op-monitor-daemon/src/test/java/ee/ria/xroad/opmonitordaemon/OperationalDataTestUtil.java
- src/proxy/src/test/java/ee/ria/xroad/proxy/util/MetaserviceTestUtil.java
- src/serverconf/build.gradle
- src/serverconf/src/main/java/ee/ria/xroad/common/conf/serverconf/dao/AbstractDAOImpl.java
- src/serverconf/src/main/java/ee/ria/xroad/common/conf/serverconf/dao/ClientDAOImpl.java
- src/serverconf/src/main/java/ee/ria/xroad/common/conf/serverconf/dao/IdentifierDAOImpl.java
- src/serverconf/src/main/java/ee/ria/xroad/common/conf/serverconf/dao/ServerConfDAOImpl.java
- src/serverconf/src/main/java/ee/ria/xroad/common/conf/serverconf/dao/ServiceDAOImpl.java
- src/serverconf/src/main/java/ee/ria/xroad/common/conf/serverconf/dao/UiUserDAOImpl.java
- src/serverconf/src/test/java/ee/ria/xroad/proxy/conf/TestUtil.java
Update Hibernate to version 5.3
> XRDDEV-384

- src/op-monitor-daemon/src/main/java/ee/ria/xroad/opmonitordaemon/HealthDataMetrics.java
- src/packages/src/xroad/ubuntu/generic/xroad-opmonitor.postinst
Fix updating health data metrics
> XRDDEV-506

- doc/Protocols/pr-mserv_x-road_protocol_for_management_services.md
- Add ownerChange management service description to documentation
> XRDDEV-516

- doc/Protocols/pr-meta_x-road_service_metadata_protocol.md
- src/addons/metaservice/src/main/java/ee/ria/xroad/proxy/clientproxy/MetadataClientRequestProcessor.java
- src/addons/metaservice/src/test/java/ee/ria/xroad/proxy/clientproxy/MetadataClientRequestProcessorTest.java
- src/common-util/build.gradle
- src/common-util/src/main/java/ee/ria/xroad/common/identifier/ServiceId.java
- src/common-util/src/main/java/ee/ria/xroad/common/identifier/XRoadId.java
Support JSON response for listClients metadata service
> XRDDEV-462

- src/packages/src/xroad/common/proxy/etc/xroad/services/proxy.conf
- Increase proxy component default metaspace memory to 128MB
> WIP XRDDEV-538

- doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md
- src/center-service/src/main/java/ee/ria/xroad/common/request/ManagementRequestHandler.java
- src/proxy-ui/app/controllers/clients_controller.rb
- src/proxy-ui/config/locales/controllers_en.yml
- Enable adding and registering another member on Security Server.
- Update new service client's default connection type (XRDDEV-428).
> XRDDEV-593

- src/build.gradle
Updates dependency check plugin to a newer version. Fix to https://jira.niis.org/browse/XRDDEV-600
Build: https://jenkins.niis.org/view/build/job/xroad-build-packages-pipeline/883/
> XRDDEV-600 update dependency-check-gradle

- src/addons/messagelog/build.gradle
- src/addons/op-monitoring/build.gradle
- src/addons/proxymonitor/metaservice/build.gradle
- src/build.gradle
- src/common-db/build.gradle
- src/common-messagelog/build.gradle
- src/common-test/build.gradle
- src/common-ui/build.gradle
- src/common-util/build.gradle
- src/common-verifier/build.gradle
- src/configuration-client/build.gradle
- src/configuration-proxy/build.gradle
- src/gradle.properties
- src/monitor-common/build.gradle
- src/op-monitor-daemon/build.gradle
- src/proxy/build.gradle
- src/serverconf/build.gradle
- src/signer-console/build.gradle
- src/signer/build.gradle
List of dependency updates on https://jira.niis.org/browse/XRDDEV-517
> XRDDEV-517

- src/addons/messagelog/src/test/java/ee/ria/xroad/proxy/messagelog/EmptyServerConf.java
- src/common-util/src/main/java/ee/ria/xroad/common/util/UriUtils.java
- src/common-util/src/test/java/ee/ria/xroad/common/util/UriUtilsTest.java
- src/monitor/src/test/java/ee/ria/xroad/monitor/EmptyServerConf.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/serverproxy/ServerRestMessageProcessor.java
- src/proxy/src/test/java/ee/ria/xroad/proxy/RestProxyTest.java
- src/proxy/src/test/java/ee/ria/xroad/proxy/testsuite/EmptyServerConf.java
- src/proxy/src/test/java/ee/ria/xroad/proxy/testsuite/TestSuiteServerConf.java
- src/proxy/src/test/java/ee/ria/xroad/proxy/testutil/TestServerConf.java
- src/serverconf/src/main/java/ee/ria/xroad/common/conf/serverconf/PathGlob.java
- src/serverconf/src/main/java/ee/ria/xroad/common/conf/serverconf/ServerConf.java
- src/serverconf/src/main/java/ee/ria/xroad/common/conf/serverconf/ServerConfImpl.java
- src/serverconf/src/main/java/ee/ria/xroad/common/conf/serverconf/ServerConfProvider.java
- src/serverconf/src/test/java/ee/ria/xroad/proxy/conf/DAOImplTest.java
- src/serverconf/src/test/java/ee/ria/xroad/proxy/conf/PathGlobTest.java
- src/serverconf/src/test/java/ee/ria/xroad/proxy/conf/ServerConfTest.java
- src/serverconf/src/test/java/ee/ria/xroad/proxy/conf/TestUtil.java
- src/serverconf/src/test/resources/serverconf.hbm.xml
Initial implementation of REST service access control rules.
> XRDDEV-586

- doc/Protocols/pr-meta_x-road_service_metadata_protocol.md
- doc/Protocols/pr-mrest_x-road_service_metadata_protocol_for_rest.md
- src/addons/messagelog/src/test/java/ee/ria/xroad/proxy/messagelog/EmptyServerConf.java
- src/addons/metaservice/src/main/java/ee/ria/xroad/proxy/serverproxy/MetadataServiceHandlerImpl.java
- src/addons/metaservice/src/main/java/ee/ria/xroad/proxy/serverproxy/RestMetadataServiceHandlerImpl.java
- src/addons/metaservice/src/test/java/ee/ria/xroad/proxy/serverproxy/MetadataServiceHandlerTest.java
- src/addons/metaservice/src/test/java/ee/ria/xroad/proxy/serverproxy/RestMetadataServiceHandlerTest.java
- src/addons/metaservice/src/test/java/ee/ria/xroad/proxy/testsuite/testcases/AllowedMethodsMessage.java
- src/addons/metaservice/src/test/java/ee/ria/xroad/proxy/testsuite/testcases/ListMethodsMessage.java
- src/monitor/src/test/java/ee/ria/xroad/monitor/EmptyServerConf.java
- src/packages/src/xroad/common/addon/proxy/metaservices.conf
- src/packages/src/xroad/common/proxy/etc/xroad/services/proxy.conf
- src/proxy/src/main/java/ee/ria/xroad/proxy/clientproxy/ClientRestMessageProcessor.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/serverproxy/RestServiceHandler.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/serverproxy/RestServiceHandlerLoader.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/serverproxy/ServerRestMessageProcessor.java
- src/proxy/src/test/java/ee/ria/xroad/proxy/testsuite/EmptyServerConf.java
- src/proxy/src/test/java/ee/ria/xroad/proxy/testsuite/TestSuiteServerConf.java
- src/serverconf/src/main/java/ee/ria/xroad/common/conf/serverconf/ServerConf.java
- src/serverconf/src/main/java/ee/ria/xroad/common/conf/serverconf/ServerConfImpl.java
- src/serverconf/src/main/java/ee/ria/xroad/common/conf/serverconf/ServerConfProvider.java
- src/serverconf/src/main/java/ee/ria/xroad/common/conf/serverconf/dao/ServiceDAOImpl.java
- src/serverconf/src/test/java/ee/ria/xroad/proxy/conf/TestUtil.java
- Add plugin mechanism for adding serverproxy service handlers
- Add REST metaservices listMethods and allowedMethods
- Modify SOAP metaservices listMethods and allowedMethods so that they return only SOAP services
- Add tests and documentation
> XRDDEV-463, XRDDEV-464

- src/packages/src/xroad/common/proxy/usr/share/xroad/db/serverconf-changelog.xml
- src/packages/src/xroad/common/proxy/usr/share/xroad/db/serverconf/9-rest-auth-refactoring.xml
- src/proxy-ui/app/controllers/clients/acl_subjects.rb
- src/proxy-ui/app/controllers/clients/services.rb
- src/serverconf/src/main/java/ee/ria/xroad/common/conf/serverconf/ServerConfImpl.java
- src/serverconf/src/main/java/ee/ria/xroad/common/conf/serverconf/model/AccessRightType.java
- src/serverconf/src/main/java/ee/ria/xroad/common/conf/serverconf/model/EndpointType.java
- src/serverconf/src/main/resources/serverconf.hbm.xml
- src/serverconf/src/test/java/ee/ria/xroad/proxy/conf/TestUtil.java
- src/serverconf/src/test/resources/serverconf.hbm.xml
Refactor REST authorization. Split accessright table in serverconf into accessright and endpoint.
Refactor existing code to work with the new structure.
> XRDDEV-612

- src/packages/src/xroad/common/proxy/usr/share/xroad/db/serverconf/9-rest-auth-refactoring.xml
- src/proxy-ui/app/controllers/clients/acl_subjects.rb
- src/proxy-ui/app/controllers/clients/services.rb
- src/proxy-ui/src/main/java/ee/ria/xroad/proxyui/OpenApiParser.java
- src/proxy-ui/src/test/java/ee/ria/xroad/proxyui/OpenApiParserTest.java
- src/proxy-ui/src/test/resources/warnings.yml
- src/serverconf/src/main/java/ee/ria/xroad/common/conf/serverconf/ServerConfImpl.java
- src/serverconf/src/main/java/ee/ria/xroad/common/conf/serverconf/model/EndpointType.java
- src/serverconf/src/main/resources/serverconf.hbm.xml
- src/serverconf/src/test/java/ee/ria/xroad/proxy/conf/TestUtil.java
- src/serverconf/src/test/resources/serverconf.hbm.xml
When adding a service with OpenAPI description, parse and store the
operations as endpoints.
> XRDDEV-615

- src/packages/src/xroad-jetty9/ubuntu/trusty/debian/xroad-jetty9.xroad-jetty.upstart
- src/packages/src/xroad/common/base/etc/xroad/services/global.conf
- src/packages/src/xroad/common/base/usr/share/xroad/scripts/_backup_restore_common.sh
- src/packages/src/xroad/redhat/SPECS/xroad-base.spec
- src/packages/src/xroad/redhat/SPECS/xroad-confclient.spec
- src/packages/src/xroad/redhat/SPECS/xroad-signer.spec
- src/packages/src/xroad/ubuntu/generic/xroad-base.postinst
- src/packages/src/xroad/ubuntu/generic/xroad-confclient.postinst
- src/packages/src/xroad/ubuntu/generic/xroad-nginx.postinst
- src/packages/src/xroad/ubuntu/generic/xroad-signer.postinst
- src/packages/src/xroad/ubuntu/trusty/debian/xroad-confclient.upstart
- src/packages/src/xroad/ubuntu/trusty/debian/xroad-monitor.upstart
- src/packages/src/xroad/ubuntu/trusty/debian/xroad-opmonitor.upstart
- src/packages/src/xroad/ubuntu/trusty/debian/xroad-proxy.upstart
- src/packages/src/xroad/ubuntu/trusty/debian/xroad-signer.upstart
Remove write rights from admin log-files and messagelog archives
> XRDDEV-592

- src/common-util/src/main/java/ee/ria/xroad/common/certificateprofile/impl/IsAuthCertificateProfileInfo.java
- src/common-util/src/main/java/ee/ria/xroad/common/certificateprofile/impl/IsCertificateProfileInfoProvider.java
- src/common-util/src/main/java/ee/ria/xroad/common/certificateprofile/impl/IsSignCertificateProfileInfo.java
- src/common-util/src/main/java/ee/ria/xroad/common/util/IsSubjectClientIdDecoder.java
This PR adds the following files that implements the Certificate profile for the Icelandic state  
IsAuthCertificateProfileInfo.java
IsCertificateProfileInfoProvider.java
IsSignCertificateProfileInfo.java
IsSubjectClientIdDecoder.java
The code successfully builds through the building process documented in https://github.com/nordic-institute/X-Road/blob/develop/src/BUILD.md
> Initial Certificate Profile for Iceland

- src/packages/src/xroad/common/addon/proxy/messagelog/6-rest-message.xml
- src/packages/src/xroad/redhat/SPECS/xroad-addon-messagelog.spec
- src/packages/src/xroad/ubuntu/generic/xroad-addon-messagelog.postinst
Do not use PostgreSQL 'lo' extension. Fixes xroad-addon-messagelog does not work in AWS RDS.
> XRDDEV-571

- Jenkinsfile
- src/addons/messagelog/src/main/java/ee/ria/xroad/proxy/messagelog/TimestamperUtil.java
- src/build.gradle
- src/common-db/build.gradle
- src/common-util/build.gradle
- src/config/checkstyle/checkstyle.xml
- src/config/checkstyle/suppressions.xml
- src/gradle.properties
- src/packages/src/xroad-jetty9/jetty.url
- src/packages/src/xroad/redhat/SPECS/xroad-base.spec
- src/packages/src/xroad/ubuntu/generic/xroad-base.install
- src/packages/src/xroad/ubuntu/generic/xroad-base.links
- src/proxy/src/main/java/ee/ria/xroad/proxy/clientproxy/ClientProxy.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/serverproxy/ServerProxy.java
- src/proxy/src/test/java/ee/ria/xroad/proxy/testsuite/DummyService.java
- src/proxy/src/test/java/ee/ria/xroad/proxy/testsuite/DummySslServerProxy.java
* Fix OWASP Dependency Check warnings
* Fix usage of deprecated or changed API
> XRDDEV-636: Update dependencies

- ansible/hosts/example_xroad_hosts.txt
- ansible/roles/xroad-base/tasks/ubuntu.yml
Add Ansible configuration option for extra locales
> XRDDEV-652

- src/proxy-ui/app/controllers/clients/services.rb
- src/proxy-ui/config/locales/views_en.yml
- src/proxy-ui/public/javascripts/services.js
- src/proxy-ui/public/stylesheets/application.css
- src/proxy-ui/public/stylesheets/scss/application.scss
Fixes for the fine-grained REST service management UI
> XRDDEV-682

- ansible/README.md
- ansible/roles/xroad-ss/tasks/main.yml
- ansible/roles/xroad-ss/tasks/rhel.yml
- ansible/roles/xroad-ss/tasks/ubuntu.yml
- ansible/roles/xroad-ss/templates/db.properties
- ansible/roles/xroad-ss/templates/xroad.properties
- ansible/vars_files/ss_database.yml
- ansible/xroad_dev.yml
- ansible/xroad_init.yml
- Update Ansible scripts to support installing Security Server with remote database
- Update documention
> XRDDEV-666

- src/addons/metaservice/src/main/java/ee/ria/xroad/proxy/serverproxy/RestMetadataServiceHandlerImpl.java
- src/proxy/src/test/java/ee/ria/xroad/proxy/testsuite/TestSuiteServerConf.java
- Fix services of type `OPENAPI3_DESCRIPTION` missing from listMethods and allowedMethods response
> XRDDEV-694 & XRDDEV-695

- src/addons/metaservice/src/main/java/ee/ria/xroad/proxy/serverproxy/RestMetadataServiceHandlerImpl.java
- src/addons/metaservice/src/test/java/ee/ria/xroad/proxy/serverproxy/MetadataServiceHandlerTest.java
- src/addons/metaservice/src/test/java/ee/ria/xroad/proxy/serverproxy/RestMetadataServiceHandlerTest.java
- src/packages/src/xroad/common/proxy/usr/share/xroad/db/serverconf-changelog.xml
- src/packages/src/xroad/common/proxy/usr/share/xroad/db/serverconf/10-rest-service-type-rename.xml
- src/proxy-ui/app/controllers/clients/services.rb
- src/proxy-ui/app/views/clients/_client_services_tab.html.erb
- src/proxy-ui/public/javascripts/services.js
- src/proxy/src/main/java/ee/ria/xroad/proxy/serverproxy/ServerRestMessageProcessor.java
- src/proxy/src/test/java/ee/ria/xroad/proxy/RestProxyTest.java
- src/proxy/src/test/java/ee/ria/xroad/proxy/testsuite/TestSuiteServerConf.java
- src/proxy/src/test/java/ee/ria/xroad/proxy/testutil/TestServerConf.java
- src/serverconf/src/main/java/ee/ria/xroad/common/conf/serverconf/model/DescriptionType.java
- src/serverconf/src/test/java/ee/ria/xroad/proxy/conf/TestUtil.java
Change servicedescription types 
OPENAPI3 -> REST
OPENAPI_DESCRIPTION -> OPENAPI3
> XRDDEV-696

- doc/Manuals/ig-ss_x-road_v6_security_server_installation_guide_for_rhel7.md
- src/packages/src/xroad/redhat/SOURCES/proxy/xroad-proxy.service
* Make it possible to bind xroad-proxy to privileged ports (80,443) on RHEL
* Update installation documentation.
> XRDDEV-648

- src/packages/src/xroad/common/monitor/etc/xroad/services/monitor.conf
Extend maximum metaspace size for xroad-monitoring
> XRDDEV-610

- src/packages/src/xroad/common/proxy/etc/sudoers.d/xroad-proxy
- src/proxy-ui/app/controllers/application_controller.rb
Fixed restarting xroad-proxy fails during internal key generation and
certificate import.
> XRDDEV-717

- src/addons/messagelog/src/main/java/ee/ria/xroad/proxy/messagelog/LogArchiver.java
- src/common-messagelog/src/main/java/ee/ria/xroad/common/messagelog/archive/LogArchiveCache.java
- src/common-messagelog/src/main/java/ee/ria/xroad/common/messagelog/archive/LogArchiveWriter.java
- src/common-messagelog/src/test/java/ee/ria/xroad/common/messagelog/archive/LogArchiveCacheTest.java
- src/common-messagelog/src/test/java/ee/ria/xroad/common/messagelog/archive/LogArchiveTest.java
Optimize message log archiving by reducing the number of queries
(updates) and using scrollable result set (streaming) when fetching
records from the database.
Optimize log archive writing by reducing copying and directory listing
operations.
> XRDDEV-113: Optimize message log archiving

- src/proxy-ui-api/frontend/package-lock.json
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/openapi/TokensApiController.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/TokenService.java
- src/proxy-ui-api/src/main/resources/openapi-definition.yaml
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/service/TokenServiceTest.java
Update token's friendly name.
Jenkins build: https://jenkins.niis.org/view/api-based-ui/job/rest-ui-build-pull-request/132/
JIRA: https://jira.niis.org/browse/XRDDEV-660
> XRDDEV-660 Update token's friendly name

- doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md
Replaces https://github.com/nordic-institute/X-Road-REST-UI/pull/82 from X-Road-REST-UI repo
> XRDDEV-504 Updated User Guides: description of Add Member + Change Owner Member

- src/proxy/src/main/java/ee/ria/xroad/proxy/clientproxy/AuthTrustVerifier.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/clientproxy/FastestConnectionSelectingSSLSocketFactory.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/clientproxy/FastestSocketSelector.java
- src/proxy/src/test/java/ee/ria/xroad/proxy/clientproxy/FastestConnectionSelectingSSLSocketFactoryConnectionCacheTest.java
- src/proxy/src/test/java/ee/ria/xroad/proxy/clientproxy/FastestConnectionSelectingSSLSocketFactoryIntegrationTest.java
- src/proxy/src/test/java/ee/ria/xroad/proxy/testsuite/DummySslServerProxy.java
- src/proxy/src/test/java/ee/ria/xroad/proxy/testsuite/testcases/SslSelectFastestProxy.java
Make "fastest wins" host selection more robust. If the TLS handshake with the selected (fastest) host fails, continue trying with other available hosts.
> XRDDEV-261

- src/proxy-ui-api/frontend/package-lock.json
- src/proxy-ui-api/frontend/src/global.ts
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/openapi/KeysApiController.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/KeyService.java
- src/proxy-ui-api/src/main/resources/openapi-definition.yaml
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/service/KeyServiceTest.java
Add api for updating friendly name of a key
> XRDDEV-661

- src/proxy-ui-api/build.gradle
https://jira.niis.org/browse/XRDDEV-349
Adds gradle task e2eTest for executing Nightwatch tests on CI
> XRDDEV-349 CI pipeline

- ansible/README.md
- ansible/roles/xroad-cs/tasks/main.yml
- ansible/roles/xroad-cs/tasks/ubuntu.yml
- ansible/vars_files/cs_database.yml
- ansible/xroad_dev.yml
- ansible/xroad_init.yml
- Add Ansible scripts for installing Central Server with remote database
- Update Ansible scripts related documentation with usage instructions
> XRDDEV-773

- doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md
- src/addons/messagelog/src/main/java/ee/ria/xroad/proxy/messagelog/AbstractTimestampRequest.java
- src/addons/messagelog/src/main/java/ee/ria/xroad/proxy/messagelog/TimestamperUtil.java
- src/addons/messagelog/src/test/java/ee/ria/xroad/proxy/messagelog/TestTimestamperWorker.java
- Implement TSA failover in application level issues.
- Continue timestamping with other available TSAs in case TSA response verification fails.
- Update Security Server user guide.
> XRDDEV-377

- src/proxy-ui-api/frontend/src/locales/en.json
- src/proxy-ui-api/frontend/src/views/Clients/ClientStatus.vue
- src/proxy-ui-api/frontend/src/views/Clients/ClientsDataTable.vue
- Fix the row limit bug in clients data table
- Split client status to it's own component
- Add proper localised strings for client status texts
> Clients table bugfix

- doc/Manuals/ig-csha_x-road_6_ha_installation_guide.md
Add instructions about creating a replicated PostgreSQL database in
central server HA installation guide.
> XRDDEV-780

- src/proxy-ui-api/build.gradle
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/openapi/ClientsApiController.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/MissingParameterException.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/ServiceDescriptionService.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/wsdl/HttpUrlConnectionConfig.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/wsdl/OpenApiParser.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/service/ServiceDescriptionServiceIntegrationTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/wsdl/OpenApiParserTest.java
- src/proxy-ui-api/src/test/resources/openapiparser/valid.json
- src/proxy-ui-api/src/test/resources/openapiparser/valid.yaml
- src/proxy-ui-api/src/test/resources/openapiparser/warnings.yml
Implements apis for adding REST services with:
- REST API base path
- OpenAPI 3 description URL
> XRDDEV-794

- src/proxy-ui-api/frontend/src/locales/en.json
- src/proxy-ui-api/frontend/src/views/KeyDetails/KeyDetails.vue
https://jira.niis.org/browse/XRDDEV-790
User can delete a key
> XRDDEV-790 Add delete function

- doc/EnvironmentalMonitoring/Monitoring-architecture.md
- src/monitor/src/main/java/ee/ria/xroad/monitor/executablelister/XroadProcessLister.java
Fix environmental monitoring does not list X-Road processes on Ubuntu.
> XRDDEV-853

- src/proxy-ui-api/src/main/resources/common-application.yml
> XRDDEV-870

- src/proxy-ui-api/frontend/tests/e2e/pages/ssMainPage.js
- src/proxy-ui-api/frontend/tests/e2e/specs/ss-clients-list.js
Added clients list test
Added clients tab content to page object
Some locator fixes
> Xrddev 459 clientlist e2etests

- src/proxy-ui-api/frontend/src/views/Clients/LocalGroups/LocalGroups.vue
https://jira.niis.org/browse/XRDDEV-872
Localgroups are now sorted alphabetically by the local group code.
> XRDDEV-872 Fix sorting of localgroups

- src/packages/src/xroad/redhat/SPECS/xroad-proxy.spec
Restart rsyslog and nginx (if running) on fresh install so that configuration changes are applied (RHEL)
> XRDDEV-745

- src/proxy-ui-api/frontend/src/components/layout/AppToolbar.vue
- src/proxy-ui-api/frontend/src/store/modules/user.ts
https://jira.niis.org/browse/XRDDEV-816
Username is visible in the app toolbar. 
Currently backend presents only a "placeholder" text as the username.
> XRDDEV-816 show username

- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/openapi/SystemApiController.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/SystemApiControllerTest.java
Add a new permission to an existing controller method
Add test
> XRDDEV-836 View Security Server Internal TLS cert

- src/proxy-ui-api/frontend/src/views/KeyDetails/KeyDetails.vue
https://jira.niis.org/browse/XRDDEV-877
Add missing user permission check for delete key action
> XRDDEV-877 delete key permission bugfix

- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/ClientService.java
When getting a client by it's ClientId the client was only fetched from the global conf. No also the local server conf is checked
JIRA: https://jira.niis.org/browse/XRDDEV-876
> XRDDEV-876 Adding member to localgroup bugfix

- src/.editorconfig
- src/proxy-ui-api/frontend/package-lock.json
- src/proxy-ui-api/frontend/package.json
- src/proxy-ui-api/frontend/scripts/dtsgen-wrapper.ts
- src/proxy-ui-api/frontend/src/store/modules/services.ts
- src/proxy-ui-api/frontend/src/types.ts
- src/proxy-ui-api/frontend/src/views/Service/Endpoints/Endpoints.vue
https://jira.niis.org/browse/XRDDEV-759
- **npm run generate-types** generates new types based on the OpenAPI definition file in backend resources
- Fixed two locations where Service.Endpoints nullability caused issues
> OpenAPI to ts generator from techday

- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/SignAndAuthKeys/TokenExpandable.vue
- When an auth CSR is successfully deleted, refresh the auth CSRs list in the UI.
> XRDDEV-920 Fix update CSRs list when an auth CSR is deleted

- src/packages/src/xroad/common/center/etc/xroad/services/jetty.conf
- src/packages/src/xroad/common/monitor/etc/xroad/services/monitor.conf
- src/packages/src/xroad/common/op-monitor/etc/xroad/services/opmonitor.conf
- src/packages/src/xroad/common/proxy/etc/xroad/services/jetty.conf
- src/packages/src/xroad/common/signer/etc/xroad/services/signer.conf
- Update CS and SS metaspace memory parameters based on measurements
> XRDDEV-820

- src/packages/src/xroad/ubuntu/generic/xroad-opmonitor.postinst
- Fix xroad-opmonitor standalone installation for Ubuntu 18
> XRDDEV-913

- src/proxy-ui-api/frontend/src/components/layout/AppToolbar.vue
- src/proxy-ui-api/frontend/src/locales/en.json
- src/proxy-ui-api/frontend/src/store/modules/user.ts
- src/proxy-ui-api/frontend/src/types.ts
- src/proxy-ui-api/frontend/src/views/AppLogin.vue
Added the server name to the header. The server address is shown on hover.
> Xrddev 817

- src/proxy-ui-api/frontend/.prettierrc
- src/proxy-ui-api/frontend/src/locales/en.json
- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/SecurityServerTlsCertificate/GenerateTlsAndCertificateDialog.vue
- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/SecurityServerTlsCertificate/SecurityServerTlsCertificate.vue
Implemented the dialog functionality, also made it so saving refreshes the certificate in the parent view.
One small change also to .prettierrc to set tab width to 2.
> XRDDEV-831

- src/signer/src/main/java/ee/ria/xroad/signer/tokenmanager/TokenManager.java
- Delete only the selected CSR instead of all authentication CSRs.
> XRDDEV-846 Update delete authentication CSR behaviour

- src/.editorconfig
- src/proxy-ui-api/frontend/src/util/api.ts
- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/SecurityServerTlsCertificate/SecurityServerTlsCertificate.vue
Implemented functionality.
Also added *.vue tab settings to .editorconf.
> XRDDEV-832: Export certificate

- src/proxy-ui-api/frontend/src/locales/en.json
- src/proxy-ui-api/frontend/src/util/api.ts
- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/SecurityServerTlsCertificate/SecurityServerTlsCertificate.vue
Task: https://jira.niis.org/browse/XRDDEV-834
> XRDDEV-834: import certificate functionality implementation

- src/proxy-ui-api/frontend/src/views/Service/Parameters/ServiceParameters.vue
JIRA issue: https://jira.niis.org/browse/XRDDEV-914
> XRDDEV-914: vuex getter, need to update via vuex action

- src/proxy-ui-api/frontend/src/global.ts
- src/proxy-ui-api/frontend/src/locales/en.json
- src/proxy-ui-api/frontend/src/router.ts
- src/proxy-ui-api/frontend/src/util/api.ts
- src/proxy-ui-api/frontend/src/util/helpers.ts
- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/SecurityServerTlsCertificate/GenerateInternalCsr.vue
- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/SecurityServerTlsCertificate/SecurityServerTlsCertificate.vue
JIRA task: https://jira.niis.org/browse/XRDDEV-835
> XRDDEV-835: implemented internal CSR generation view on frontend

- src/common-test/src/main/java/ee/ria/xroad/common/conf/globalconf/EmptyGlobalConf.java
- src/common-ui/src/main/java/ee/ria/xroad/commonui/SignerProxy.java
- src/common-util/src/main/java/ee/ria/xroad/common/conf/globalconf/SharedParametersV2.java
- src/common-verifier/src/main/java/ee/ria/xroad/common/conf/globalconf/GlobalConf.java
- src/common-verifier/src/main/java/ee/ria/xroad/common/conf/globalconf/GlobalConfImpl.java
- src/common-verifier/src/main/java/ee/ria/xroad/common/conf/globalconf/GlobalConfProvider.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/RestApiApplication.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/converter/CertificateAuthorityConverter.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/converter/CertificateAuthorityOcspResponseMapping.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/converter/TokenCertificateConverter.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/dto/ApprovedCaDto.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/facade/GlobalConfFacade.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/facade/SignerProxyFacade.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/openapi/CertificateAuthoritiesApiController.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/CertificateAuthorityService.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/GlobalConfService.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/util/OcspUtils.java
- src/proxy-ui-api/src/main/resources/openapi-definition.yaml
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/CertificateAuthoritiesApiControllerTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/service/BackupServiceTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/service/CertificateAuthorityServiceTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/util/CertificateTestUtils.java
https://jira.niis.org/browse/XRDDEV-885
> XRDDEV-885 list approved cas

- src/proxy-ui-api/frontend/src/views/Settings/SystemParameters/SystemParameters.vue
JIRA ticket: https://jira.niis.org/browse/XRDDEV-887
> XRDDEV-887: Download configuration anchor functionality

- src/proxy-ui-api/frontend/src/locales/en.json
- src/proxy-ui-api/frontend/src/views/Settings/SystemParameters/SystemParameters.vue
- src/proxy-ui-api/frontend/src/views/Settings/SystemParameters/UploadConfigurationAnchorDialog.vue
JIRA ticket: https://jira.niis.org/browse/XRDDEV-888
> XRDDEV-888: Upload configuration anchor functionality

- src/proxy-ui-api/frontend/src/components/ui/LargeButton.vue
- src/proxy-ui-api/frontend/src/locales/en.json
- src/proxy-ui-api/frontend/src/views/Settings/SystemParameters/AddTimestampingServiceDialog.vue
- src/proxy-ui-api/frontend/src/views/Settings/SystemParameters/SystemParameters.vue
JIRA ticket: https://jira.niis.org/browse/XRDDEV-889
Also made a change to the @click handler on LargeButton to propagate the event correctly.
> XRDDEV-889: Add timestamping service

- doc/Manuals/ig-csha_x-road_6_ha_installation_guide.md
- doc/Manuals/ug-cs_x-road_6_central_server_user_guide.md
- Add instructions to migrate standalone Central Server to use an external database
- Add instructions to migrate standalone Central Server to HA cluster setup
> XRDDEV-874

- src/proxy-ui-api/frontend/src/locales/en.json
- src/proxy-ui-api/frontend/src/views/Settings/SystemParameters/SystemParameters.vue
JIRA ticket: https://jira.niis.org/browse/XRDDEV-1004
> XRDDEV-1004: fixes configuration anchor table label and hash formatting

- src/proxy-ui-api/frontend/src/components/layout/AppToolbar.vue
- src/proxy-ui-api/frontend/src/views/AppLogin.vue
JIRA ticket: https://jira.niis.org/browse/XRDDEV-1005
> XRDDEV-1005: fix double toolbar on login page

- src/proxy-ui-api/frontend/src/views/GenerateCertificateSignRequest/GenerateCertificateSignRequest.vue
Bugfix for CSR wizard that shows an empty page. 
Jira issue: https://jira.niis.org/browse/XRDDEV-1006
> XRDDEV-1006 Fix CSR wizard

- doc/Manuals/ug-cs_x-road_6_central_server_user_guide.md
- doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md
- src/packages/src/xroad/common/base/usr/share/xroad/scripts/_restore_xroad.sh
- src/packages/src/xroad/common/proxy/usr/share/xroad/scripts/restore_xroad_proxy_configuration.sh
- add possibility to skip existing file removal when restoring backup
- update SS and CS user guides to describe how to use the pre-restore backups
> XRDDEV-855

- src/proxy-ui-api/frontend/src/locales/en.json
- src/proxy-ui-api/frontend/src/views/Settings/BackupAndRestore/BackupAndRestore.vue
JIRA ticket: https://jira.niis.org/browse/XRDDEV-935
> XRDDEV-935: frontend upload backup functionality

- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/auth/ApiKeyAuthenticationHelper.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/auth/ApiKeyAuthenticationManager.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/repository/ApiKeyRepository.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/ApiKeyService.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/TransactionHandlingRestTemplateTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/UserApiControllerRestTemplateTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/service/ApiKeyServiceCachingIntegrationTest.java
Fix API key based authentication error:
- Update ApiKeyService to use method level authentication instead of class level authentication.
- Do not authenticate methods used by ApiKeyAuthenticationManager.
- Update tests.
> XRDDEV-1015

- src/proxy-ui-api/frontend/package.json
- src/proxy-ui-api/frontend/tests/e2e/pages/ssMainPage.js
- src/proxy-ui-api/frontend/tests/e2e/specs/ss-clients-localgroups.js
Fixes to various e2e test issues and ui interaction changes
> Fix e2etest notifications

- src/common-util/build.gradle
- src/gradle.properties
https://jira.niis.org/browse/XRDDEV-1021
> XRDDEV-1021 Upgrade to jackson databind 2.10.3

- src/proxy-ui-api/frontend/src/locales/en.json
- src/proxy-ui-api/frontend/src/views/Settings/BackupAndRestore/BackupsDataTable.vue
- src/proxy-ui-api/frontend/src/views/Settings/BackupAndRestore/RestoreBackupButton.vue
JIRA ticket: https://jira.niis.org/browse/XRDDEV-932
> XRDDEV-932: restore backup frontend implementation

- src/proxy-ui-api/frontend/src/router.ts
- src/proxy-ui-api/frontend/src/store/modules/clients.ts
- src/proxy-ui-api/frontend/src/views/LocalGroup/LocalGroup.vue
Fixes for two bugs
https://jira.niis.org/browse/XRDDEV-1038
https://jira.niis.org/browse/XRDDEV-1039
Also removes an unused vuex action.
> XRDDEV-1038, XRDDEV-1039 Fix permission related bugs

- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/ApiKey/ApiKeyRow.vue
Ticket: https://jira.niis.org/browse/XRDDEV-1051
> XRDDEV-1051: fix error where you can save an api key without any roles

- src/proxy-ui-api/frontend/nightwatch.json
- src/proxy-ui-api/frontend/tests/e2e/pages/ssMainPage.js
- src/proxy-ui-api/frontend/tests/e2e/specs/ss-clients-details.js
- src/proxy-ui-api/frontend/tests/e2e/specs/ss-permissions-clientslist.js
- src/proxy-ui-api/frontend/tests/e2e/specs/ss-permissions-localgroups.js
Added e2e tests for role based permissions of the clients list, client details, local groups list and local group details views.
Fixed some locators and a test name.
> Xrddev 966 clientslist localgroups permissiontests

- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/converter/ClientConverter.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/ClientService.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/util/ClientUtils.java
- Update error handling when status of a sign cert is resolved.
- Catch errors and set sign cert status to false.
> XRDDEV-1058

- src/proxy-ui-api/frontend/src/store/modules/user.ts
Ticket: https://jira.niis.org/browse/XRDDEV-1056
Fixes a bug with allowed tabs.
> XRDDEV-1056 Fix allowed tabs method

- src/proxy-ui-api/frontend/src/store/modules/addClient.ts
JIRA: https://jira.niis.org/browse/XRDDEV-1078
> XRDDEV-1078: Fix query parameters in add client wizard 

- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/ServiceDescriptionService.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/service/ServiceDescriptionServiceIntegrationTest.java
Prevent adding/updating REST/OPENAPI3 service with duplicate service code or full service code (servicecode + version).
> XRDDEV-981 

- src/build.gradle
- src/proxy-ui-api/build.gradle
Upgraded the minor version of most dependecies. Also removed Springfox Swagger 2 and Springfox Swagger UI since they were not used.
Upgrades documented in more details in here: https://confluence.niis.org/pages/viewpage.action?pageId=37355771
JIRA: https://jira.niis.org/browse/XRDDEV-954
> XRDDEV-954 Update dependencies

- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/service/ServiceDescriptionServiceIntegrationTest.java
* test was not in sync with test db data
> XRDDEV-981 Fix failing test: addRestEndpointServiceDescriptionSuccess

- src/proxy-ui-api/frontend/audit-resolve.json
- src/proxy-ui-api/frontend/package-lock.json
Add one month ignore for dev dependency related audit issue
@vue/cli-service [dev] 
@vue/cli-service > webpack-dev-server > http-proxy-middleware > http-proxy      
https://github.com/vuejs/vue-cli/issues/5489#issuecomment-629326414
https://www.npmjs.com/advisories/1486
> Add ignore for vue-cli related audit error

- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/openapi/InitializationApiController.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/InitializationService.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/InitializationApiControllerTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/service/InitializationServiceTest.java
An upgrade to the already merged initial configuration feature.
* error if server has been fully initialized already before
* better error metadata depending on if a parameter is required or not allowed
> XRDDEV-904 Initial configuration upgrade

- src/proxy-ui-api/frontend/src/components/service/WarningDialog.vue
- src/proxy-ui-api/frontend/src/locales/en.json
- src/proxy-ui-api/frontend/src/views/Clients/Services/Services.vue
Improved layout for warnings when adding wsdl service
Jira: https://jira.niis.org/browse/XRDDEV-1041
> XRDDEV-1041

- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/InitializationService.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/IdentifierValidationRestTemplateTest.java
* mock SystemService in test
* add comment on Sonar suppress warning line
> XRDDEV-904 Initial configuration test fix

- src/proxy-ui-api/build.gradle
* omit npm configurations -> will use the npm version that is bundled with the selected node version
* fix node_modules dir config
JIRA: https://jira.niis.org/browse/XRDDEV-1106
> XRDDEV-1106 Gradle node bug

- src/proxy-ui-api/frontend/src/util/api.ts
- src/proxy-ui-api/frontend/src/views/Settings/SystemParameters/UploadConfigurationAnchorDialog.vue
Bug ticket: https://jira.niis.org/browse/XRDDEV-1102
> XRDDEV-1102: fix anchor preview and upload to use new API endpoints

- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/openapi/LocalGroupsApiController.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/repository/ClientRepository.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/AccessRightService.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/LocalGroupService.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/LocalGroupsApiControllerIntegrationTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/service/LocalGroupServiceIntegrationTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/util/TestUtils.java
- src/serverconf/src/main/java/ee/ria/xroad/common/conf/serverconf/dao/ClientDAOImpl.java
Deleting local group removes also access rights granted to the local group.
https://jira.niis.org/browse/XRDDEV-1040
> XRDDEV-1040: remove access rights of removed local group

- src/proxy-ui-api/frontend/src/views/Settings/SystemParameters/SystemParameters.vue
Bug ticket: https://jira.niis.org/browse/XRDDEV-1057
> XRDDEV-1057: fixed system parameters view permission checks

- ansible/ss_cluster/roles/node/tasks/redhat.yml
- ansible/ss_cluster/xroad_ss_cluster.yml
* Fix database initialization on RHEL 8.
* Fix cluster setup playbook does not work with latest stable Ansible.
> XRDDEV-980: Support security server cluster setup for RHEL 8

- src/proxy-ui-api/frontend/audit-resolve.json
- src/proxy-ui-api/frontend/package-lock.json
- src/proxy-ui-api/frontend/package.json
Add one month ignore for dev dependency related audit issue
https://npmjs.com/advisories/1500
Updated confluence list:
https://confluence.niis.org/display/XRDDEV/Accepted+npm+audit+vulnerabilities
> Update npm audit error ignores

- src/proxy-ui-api/frontend/src/components/ui/Snackbar.vue
- src/proxy-ui-api/frontend/src/locales/en.json
- src/proxy-ui-api/frontend/src/views/Clients/InternalServers/InternalServers.vue
- src/proxy-ui-api/frontend/src/views/Clients/Services/AddRestDialog.vue
- src/proxy-ui-api/frontend/src/views/Clients/Services/Services.vue
https://jira.niis.org/browse/XRDDEV-1020
- Snackbar shows the metadata if it exists
- Error code is used to pull localised text from en.json with error_code. prefix. Currently only a few exists and adding the localisations for rest of the error codes should be done later.
> XRDDEV-1020 Error snackbar update

- src/proxy-ui-api/frontend/src/store/modules/certificateSignRequest.ts
- src/proxy-ui-api/frontend/src/views/AddClient/AddClient.vue
- src/proxy-ui-api/frontend/src/views/AddMember/AddMember.vue
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/openapi/CertificateAuthoritiesApiController.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/CertificateAuthorityService.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/TokenCertificateService.java
- src/proxy-ui-api/src/main/resources/openapi-definition.yaml
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/CertificateAuthoritiesApiControllerTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/service/CertificateAuthorityServiceTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/service/TokenCertificateServiceTest.java
* add query parameter for checking whether the selected member exists when getting cert profile
> XRDDEV-1120 Fix cert profile field description bug

- src/proxy-ui-api/frontend/src/filters.ts
- src/proxy-ui-api/frontend/src/views/Clients/ClientsDataTable.vue
Small bug fixes:
- Fix clients search https://jira.niis.org/browse/XRDDEV-1121
- Also fixes the getMonth bug in date filters which is mentioned in here https://github.com/nordic-institute/X-Road/pull/496
- Some typings are improved
> XRDDEV-1121 Clients search bug + date filter bug

- src/proxy-ui-api/frontend/src/store/modules/certificateSignRequest.ts
- src/proxy-ui-api/frontend/src/util/helpers.ts
- src/proxy-ui-api/frontend/src/views/Service/Endpoints/EndpointDetails.vue
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/PossibleActionsRuleEngine.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/service/PossibleActionsRuleEngineTest.java
- Creating csrs is fixed
- Fix attaching labels to keys on creation
- Enable key friendly name editing at any time even when it does not have a certificate attached
> XRDDEV-1100: Fixes to keys and certificates view

- src/proxy-ui-api/frontend/src/locales/en.json
- src/proxy-ui-api/frontend/src/views/AddSubsystem/AddSubsystem.vue
- src/proxy-ui-api/frontend/src/views/Clients/ClientsDataTable.vue
https://jira.niis.org/browse/XRDDEV-1079
- Add confirm dialog to add subsystem register phase
- Add spinner to submit button
- Add success snackbar
> XRDEV-1079 subsystem spinner

- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/controller/NotificationsApiController.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/NotificationService.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/controller/NotificationsApiControllerTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/service/NotificationServiceTest.java
JIRA: https://jira.niis.org/browse/XRDDEV-1035
> XRDDEV-1035 Check init status before checking alerts

- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/ServiceDescriptionService.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/service/ServiceDescriptionServiceIntegrationTest.java
* set the service url from the parsed service description
* add assertion to test
> XRDDEV-1135 OAS3 Service URL bugfix

- src/proxy-ui-api/frontend/src/components/ui/ServiceIcon.vue
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/converter/ServiceConverter.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/ServicesApiControllerIntegrationTest.java
JIRA: https://jira.niis.org/browse/XRDDEV-1136
> XRDDEV-1136 WSDL Service SSL auth status bug fix

- src/proxy-ui-api/frontend/src/store/modules/clients.ts
https://jira.niis.org/browse/XRDDEV-1144
- Members without real name have now "unknown member"  as a name in the UI
- Simplified the way how unknown members are named
> XRDDEV-1144 Fix the unnamed members

- src/proxy-ui-api/frontend/src/views/Service/Service.vue
JIRA ticket: https://jira.niis.org/browse/XRDDEV-1150
> XRDDEV-1150: fix service title missing in service view

- src/proxy-ui-api/frontend/package-lock.json
- src/proxy-ui-api/frontend/src/views/Clients/ClientsDataTable.vue
Show Add subsystem button for the second member.
JIRA issue: https://jira.niis.org/browse/XRDDEV-1130
> XRDDEV-1130

- src/proxy-ui-api/frontend/src/store/modules/certificateSignRequest.ts
- src/proxy-ui-api/frontend/src/util/helpers.ts
JIRA ticket: https://jira.niis.org/browse/XRDDEV-1140
> XRDDEV-1140: fixes binary DER format download

- src/proxy-ui-api/frontend/src/store/modules/certificateSignRequest.ts
This PR also fixes DER download for the endpoint used by the keys and csr functionality. Similar fix to the PR https://github.com/nordic-institute/X-Road/pull/553/files
Related JIRA ticket: https://jira.niis.org/browse/XRDDEV-1139
> XRDDEV-1139: fixes wrong csr format downloaded

- src/proxy-ui-api/frontend/package-lock.json
- src/proxy-ui-api/frontend/package.json
- src/proxy-ui-api/frontend/src/components/ui/Snackbar.vue
- src/proxy-ui-api/frontend/src/main.ts
- src/proxy-ui-api/frontend/src/util/helpers.ts
JIRA ticket: https://jira.niis.org/browse/XRDDEV-1119
Also replaced the external dependency on vue-clipboard2 with a custom function.
> XRDDEV-1119: fix clipboard for correlation ID copy functionality

- doc/Manuals/ig-cs_x-road_6_central_server_installation_guide.md
- doc/Manuals/ig-ss_x-road_v6_security_server_installation_guide.md
- doc/Manuals/ig-ss_x-road_v6_security_server_installation_guide_for_rhel7.md
- doc/Manuals/ug-cp_x-road_v6_configuration_proxy_manual.md
Add repository sign key details to installation guides.
> XRDDEV-1157

- src/proxy-ui-api/frontend/src/components/ui/AlertsContainer.vue
- src/proxy-ui-api/frontend/src/store/modules/alerts.ts
JIRA ticket: https://jira.niis.org/browse/XRDDEV-1143
Also added an additional check to the alerts store to make sure that we have actually already queried the alerts status from the server.
> XRDDEV-1143: ignore alerts if not yet initialised

- src/proxy-ui-api/frontend/src/store/modules/initializeServer.ts
- src/proxy-ui-api/src/main/resources/openapi-definition.yaml
* change all OAS3 inline objects into referable object schemas
* change initializeServer store to use InitializationStatus OAS3 type
JIRA: https://jira.niis.org/browse/XRDDEV-1109
> XRDDEV-1109 Change inline objects to object schemas

- doc/Manuals/ug-syspar_x-road_v6_system_parameters.md
- src/packages/src/xroad/default-configuration/override-securityserver-ee.ini
- Enable enforce-token-pin-policy in EE metapackage
- Update documentation
JIRA issue: https://jira.niis.org/browse/XRDDEV-1173
> XRDDEV-1173 Enable enforce-token-pin-policy in EE metapackage

- src/build.gradle
The Spring Boot upgrade includes a Tomcat upgrade from 9.0.34 to 9.0.36
> XRDDEV-1107 Upgrade Spring Boot from 2.2.7 to 2.2.8

- src/proxy-ui-api/frontend/src/components/service/WarningDialog.vue
- src/proxy-ui-api/frontend/src/views/Clients/Services/AddRestDialog.vue
- src/proxy-ui-api/frontend/src/views/Clients/Services/Services.vue
- src/proxy-ui-api/frontend/src/views/ServiceDescriptionDetails/ServiceDescriptionDetails.vue
https://jira.niis.org/browse/XRDDEV-1192:
- Add spinner to warning dialog's Continue button.
- Close warning dialog only after save, refresh or edit operation has completed.
- Fix error code `400` when an OpenAPI description with warnings is updated.
https://jira.niis.org/browse/XRDDEV-1195:
- Add support for warning dialog when new OpenAPI service is added.
> XRDDEV-1192/XRDDEV-1195

- src/proxy-ui-api/frontend/src/views/ServiceDescriptionDetails/ServiceDescriptionDetails.vue
- src/proxy-ui-api/frontend/src/views/Settings/SystemParameters/UploadConfigurationAnchorDialog.vue
https://jira.niis.org/browse/XRDDEV-1198
- Anchor file is now cleared after error. This prevented the upload.
- Handling of the error replies is improved
> XRDDEV-1198 Fix anchor upload

- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/openapi/TokenCertificatesApiController.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/TokenCertificateService.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/service/TokenCertificateServiceTest.java
https://jira.niis.org/browse/XRDDEV-1187
> XRDDEV-1187 check possible actions for cert activate / disable

- src/proxy-ui-api/frontend/src/views/Clients/ClientsDataTable.vue
https://jira.niis.org/browse/XRDDEV-1205
Add missing permission check for add member button.
> XRDDEV-1205 Add missing permission check

- src/proxy-ui-api/frontend/tests/e2e/pages/ssMainPage.js
- src/proxy-ui-api/frontend/tests/e2e/specs/ss-clients-wsdlservices.js
Fix to match new UI of remove access right and remove all access rights dialogs
> e2etest fix for access right dialogs

- src/proxy-ui-api/frontend/src/views/InitialConfiguration/InitialConfiguration.vue
JIRA ticket: https://jira.niis.org/browse/XRDDEV-1199
> XRDDEV-1199: check for alerts immediately after initialisation is completed

- src/proxy-ui-api/frontend/tests/e2e/specs/ss-clients-localgroups.js
- src/proxy-ui-api/frontend/tests/e2e/specs/ss-clients-wsdlservices.js
Fix to snackbar error messages
> e2etest fix for new error messages

- src/proxy-ui-api/frontend/src/store/modules/addClient.ts
- src/proxy-ui-api/frontend/src/store/modules/certificateSignRequest.ts
- src/proxy-ui-api/frontend/src/views/AddMember/FinishPage.vue
https://jira.niis.org/browse/XRDDEV-1182
Fixes the add member flow in the case that the member already has existing csr
> XRDDEV-1182 Fix add member flow in case when the csr exists

- src/proxy-ui-api/frontend/src/components/client/SelectClientDialog.vue
- src/proxy-ui-api/frontend/src/locales/en.json
- src/proxy-ui-api/frontend/src/views/AddClient/AddClient.vue
- src/proxy-ui-api/frontend/src/views/AddClient/ClientDetailsPage.vue
- src/proxy-ui-api/frontend/src/views/AddClient/FinishPage.vue
- src/proxy-ui-api/frontend/src/views/AddMember/AddMember.vue
- src/proxy-ui-api/frontend/src/views/AddMember/FinishPage.vue
- src/proxy-ui-api/frontend/src/views/AddMember/MemberDetailsPage.vue
- src/proxy-ui-api/frontend/tests/e2e/pages/ssMainPage.js
- src/proxy-ui-api/frontend/tests/e2e/specs/ss-clients-wsdlservices.js
https://jira.niis.org/browse/XRDDEV-1183
- Add client flow handles existing csr / certificate scenarios in similar way as add member flow
- Some cleanup for add member flow
Merge PR 606 before this
https://github.com/nordic-institute/X-Road/pull/606
> XRDDEV-1183 Client flow improvement

- src/proxy-ui-api/frontend/src/views/Clients/ClientsDataTable.vue
JIRA ticket: https://jira.niis.org/browse/XRDDEV-1214
> XRDDEV-1214: added ':' to the check to fix grouping

- src/proxy-ui-api/frontend/src/views/Settings/SystemParameters/UploadConfigurationAnchorDialog.vue
https://jira.niis.org/browse/XRDDEV-1215
Fixes a bug when anchor preview gives an error
> XRDDEV-1215 Fix anchor upload error

- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/SignAndAuthKeys/CertificateRow.vue
- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/SignAndAuthKeys/KeyRow.vue
- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/SignAndAuthKeys/KeysTable.vue
JIRA ticket: https://jira.niis.org/browse/XRDDEV-907
> XRDDEV-907: keys and certificates view table layout fixes

- src/proxy-ui-api-devtools/build.gradle
- src/proxy-ui-api/build.gradle
Update Tomcat to fix a vulnerability
https://jira.niis.org/browse/XRDDEV-1204
> XRDDEV-1204 upgrade tomcat

- src/packages/src/xroad/redhat/SOURCES/proxy-ui-api/xroad-proxy-ui-api.service
- src/packages/src/xroad/ubuntu/bionic/debian/xroad-proxy-ui-api.service
https://jira.niis.org/browse/XRDDEV-1117
If application fails to start due to bad logging configuration, it does not (typically) try to restart forever. More details in jira ticket.
> XRDDEV-1117 fix eternal loop

- src/proxy-ui-api/frontend/src/components/ui/Snackbar.vue
- src/proxy-ui-api/frontend/src/locales/en.json
JIRA ticket: https://jira.niis.org/browse/XRDDEV-1145
Added translations for all validation error types listed, hard to tell how good the field coverage is. Added the service code fields, not sure if anywhere else should go past frontend validation at this point.
> XRDDEV-1145: add validation error handling to frontend

- src/proxy-ui-api/frontend/src/App.vue
https://jira.niis.org/browse/XRDDEV-1229
Frontend couldn't properly parse an error message when it was expecting content type to be blob. 
Source for the fix:
https://github.com/axios/axios/issues/815#issuecomment-453963910
> XRDDEV-1229 Fix error handling when expecting a blob response

- src/packages/src/xroad/default-configuration/override-securityserver-is.ini
- src/packages/src/xroad/redhat/SPECS/xroad-securityserver-is.spec
- src/packages/src/xroad/ubuntu/generic/xroad-securityserver-is.install
Resubmitting code changes from PR #561 due to vacations and CLA signing. Code originally submitted by @gudvardur
> Resubmitting #561 as new PR - CLA signing signing related

- src/proxy-ui-api/frontend/src/filters.ts
https://jira.niis.org/browse/XRDDEV-1235
Use getDate() instead of getDay()
> XRDDEV-1235 Fix wrong date

- src/proxy-ui-api/frontend/src/locales/en.json
- src/proxy-ui-api/frontend/src/plugins/vee-validate.ts
- src/proxy-ui-api/frontend/src/views/AddClient/ClientDetailsPage.vue
- src/proxy-ui-api/frontend/src/views/AddMember/MemberDetailsPage.vue
- src/proxy-ui-api/frontend/src/views/AddSubsystem/AddSubsystem.vue
- src/proxy-ui-api/frontend/src/views/Clients/Services/AddRestDialog.vue
- src/proxy-ui-api/frontend/src/views/InitialConfiguration/OwnerMemberStep.vue
- src/proxy-ui-api/frontend/src/views/ServiceDescriptionDetails/ServiceDescriptionDetails.vue
Jira ticket: https://jira.niis.org/browse/XRDDEV-1208
This turned out to be a bit more involved than just adding the validation rule, the "memberCode" checks also needed additional checks before REST calls to the backend were made so they wouldn't cause 400 errors when the user typed an incorrect identifier.
**NB!** Also changed the logic in AddRestDialog to use the validation results provided by ValidationObserver rather than a computed field that essentially ran the same checks that the framework was already running again.
> XRDDEV-1208: validating identifiers on the frontend

- doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md
- src/packages/src/xroad/default-configuration/proxy-ui-api-logback.xml
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/config/IpThrottlingFilter.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/config/LimitRequestSizesFilter.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/config/StartStopListener.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/repository/AnchorRepository.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/scheduling/GlobalConfChecker.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/CertificateAuthorityService.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/DiagnosticService.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/ExternalProcessRunner.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/InternalTlsCertificateService.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/ManagementRequestSenderService.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/MissingParameterException.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/NotificationService.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/SystemService.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/wsdl/OpenApiParser.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/wsdl/WsdlParser.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/wsdl/WsdlValidator.java
- src/proxy-ui-api/src/main/resources/common-application.yml
https://jira.niis.org/browse/XRDDEV-403
Updates to proxy-ui-api technical logging to better follow common conventions and OWASP recommendations. Some documentation updates.
> XRDDEV-403 technical log

- doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md
An addition to https://jira.niis.org/browse/XRDDEV-1117 based on demo comments.
- Updated documentation, now mentions unit start rate limits.
> XRDDEV-1117 document start rate limit

- src/asic-util/build.gradle
- src/common-util/build.gradle
- src/op-monitor-daemon/src/main/java/ee/ria/xroad/opmonitordaemon/QueryRequestHandler.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/config/UsernameSettingTransactionManager.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/exceptions/Deviation.java
- src/proxy/build.gradle
> XRDDEV-1247

- src/proxy-ui-api/frontend/src/views/Settings/BackupAndRestore/BackupAndRestore.vue
JIRA ticket: https://jira.niis.org/browse/XRDDEV-1252
> XRDDEV-1252: fix backup upload confirmation dialog not showing file name

- src/proxy-ui-api/frontend/package-lock.json
- src/proxy-ui-api/frontend/src/views/Clients/InternalServers/InternalServers.vue
- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/SecurityServerTlsCertificate/SecurityServerTlsCertificate.vue
Fix frontend permission checks:
- Fix permission check for the Upload button in the the Security Server TLS Certificate view.
- JIRA: https://jira.niis.org/browse/XRDDEV-1261
- Fix permission check for the Add IS TLS cert button in the Internal Servers tab.
- JIRA: https://jira.niis.org/browse/XRDDEV-1258
> XRDDEV-1261/XRDDEV-1258

- src/proxy-ui-api/frontend/src/components/wizard/CsrDetailsPageLocked.vue
- src/proxy-ui-api/frontend/src/components/wizard/WizardPageCsrDetails.vue
- src/proxy-ui-api/frontend/src/locales/en.json
- src/proxy-ui-api/frontend/src/store/modules/certificateSignRequest.ts
- src/proxy-ui-api/frontend/src/views/Settings/SystemParameters/TimestampingServiceRow.vue
https://jira.niis.org/browse/XRDDEV-1253
- Fix localisation related alerts in browser console by adding missing keys
- Alert dialog was used with translated text, now properly with the translation keys
- Removed some unused names
- Fixed misspellings of CRS -> CSR
> XRDDEV-1253 Fix localisation alerts in browser console

- LICENSE
- src/LICENSE.txt
- src/centralserver-LICENSE.info
- src/configuration-proxy-LICENSE.info
- src/securityserver-LICENSE.info
Update license and license info files:
- Update copyright notices.
- Update contact information.
JIRA issue: https://jira.niis.org/browse/XRDDEV-1274
> XRDDEV-1274

- src/proxy-ui-api/frontend/src/views/Clients/ServiceClients/AddServiceClientAccessRightsWizard.vue
- src/proxy-ui-api/frontend/src/views/Clients/ServiceClients/AddServiceClientServiceDialog.vue
- src/proxy-ui-api/frontend/src/views/Clients/ServiceClients/MemberOrGroupSelectionStep.vue
- src/proxy-ui-api/frontend/src/views/Clients/ServiceClients/ServiceSelectionStep.vue
https://jira.niis.org/browse/XRDDEV-1273
- Add selected button is now disabled is nothing is selected
- Add placeholder text for empty table
- Style fix for buttons being cut off
> XRDDEV-1273 Fixes for add subject wizard

- src/proxy-ui-api/frontend/src/components/layout/TabsBase.vue
- src/proxy-ui-api/frontend/src/components/ui/AlertsContainer.vue
- src/proxy-ui-api/frontend/src/router.ts
- src/proxy-ui-api/frontend/src/views/Clients/ServiceClients/ServiceClients.vue
- src/proxy-ui-api/frontend/src/views/KeyDetails/KeyDetails.vue
PR: https://jira.niis.org/browse/XRDDEV-1276
> XRDDEV-1276 Active tab fix

- src/proxy-ui-api/build.gradle
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/exceptions/ApplicationExceptionHandler.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/exceptions/ExceptionTranslator.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/exceptions/SpringInternalExceptionHandler.java
https://jira.niis.org/browse/XRDDEV-1231
> XRDDEV-1231 remove actuator and thymeleaf dependencies

- src/proxy-ui-api/frontend/src/views/Clients/Services/AddRestDialog.vue
- src/proxy-ui-api/frontend/tests/e2e/pages/ssMainPage.js
- src/proxy-ui-api/frontend/tests/e2e/specs/ss-clients-openapiservices.js
- src/proxy-ui-api/frontend/tests/e2e/specs/ss-clients-restservices.js
- src/proxy-ui-api/frontend/tests/e2e/specs/ss-clients-wsdlservices.js
Fixes to E2E-tests after minor UI-changes in rest, openapi and wsdl add/edit/service parameters dialogs
> XRDDEV-1250

- src/proxy-ui-api/frontend/src/views/Clients/InternalServers/InternalServers.vue
- src/proxy-ui-api/src/main/resources/common-application.yml
https://jira.niis.org/browse/XRDDEV-1288
Also fixes https://jira.niis.org/browse/XRDDEV-1289
> XRDDEV-1288 better file upload max size configuration

- src/proxy-ui-api/frontend/src/locales/en.json
Add localised text for the new signer error code
> Add new localisation for error code

- src/packages/src/xroad/common/proxy-ui-api/etc/xroad/services/proxy-ui-api.conf
https://jira.niis.org/browse/XRDDEV-646
Still doing some smoke testing of the change
> XRDDEV-646 increase proxy-ui-api max metaspace 150m -> 200m

- src/proxy-ui-api/src/main/resources/openapi-definition.yaml
JIRA: https://jira.niis.org/browse/XRDDEV-401
This only includes the minor findings such as 
* increase service id max length
* endpoint id max length
* security-server id max and min lengths
New tickets will be created out of the other findings; check the JIRA task comments
> XRDDEV-401 Input validation in api

- src/proxy-ui-api/frontend/src/global.ts
- src/proxy-ui-api/frontend/src/router.ts
- src/proxy-ui-api/frontend/src/store/modules/user.ts
- src/proxy-ui-api/frontend/src/views/Clients/Services/AddRestDialog.vue
- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/KeysAndCertificates.vue
- src/proxy-ui-api/frontend/src/views/Settings/Settings.vue
https://jira.niis.org/browse/XRDDEV-1303
https://jira.niis.org/browse/XRDDEV-1304
https://jira.niis.org/browse/XRDDEV-1308
Cherrypicked from merge of this PR: https://github.com/nordic-institute/X-Road/pull/690
> XRDDEV-1303 Fix router permissions - cherrypicked changes from bugfix branch

- src/proxy-ui-api/frontend/src/locales/en.json
JIRA issue: https://jira.niis.org/browse/XRDDEV-1337
> XRDDEV-1337 Update Keys and Certificates menu items' localisations

- src/proxy-ui-api/frontend/src/components/layout/AppToolbar.vue
- src/proxy-ui-api/frontend/src/views/AppLogin.vue
- src/proxy-ui-api/frontend/src/views/Clients/Services/AddRestDialog.vue
- src/proxy-ui-api/frontend/src/views/InitialConfiguration/InitialConfiguration.vue
https://jira.niis.org/browse/XRDDEV-1317
> XRDDEV-1315 Fix router duplicate navigation console alerts

- src/proxy-ui-api/frontend/audit-resolve.json
- src/proxy-ui-api/frontend/package-lock.json
- ran npm audit fix 
- updated check-audit ignore list
- updated confluence page for accepted npm audit vulnerabilities
> Update vulnerable npm packages and audit ignores

- src/proxy-ui-api/build.gradle
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/exceptions/ApplicationExceptionHandler.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/exceptions/ExceptionTranslator.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/exceptions/SpringInternalExceptionHandler.java
Add https://jira.niis.org/browse/XRDDEV-1231 to bugfix-6.24.1, not only develop
> XRDDEV-1231 to bugfix branch

- src/proxy-ui-api/frontend/src/components/certificate/CertificateLine.vue
https://jira.niis.org/browse/XRDDEV-1339
> XRDDEV-1339: Fix not_after value in certificate details

- src/proxy-ui-api/frontend/src/views/Clients/Services/AddRestDialog.vue
- src/proxy-ui-api/frontend/src/views/KeyDetails/KeyDetails.vue
Populate read-only field in key details with token data.
https://jira.niis.org/browse/XRDDEV-1321
> XRDDEV-1321

- src/proxy-ui-api/frontend/src/views/AddClient/ClientDetailsPage.vue
https://jira.niis.org/browse/XRDDEV-1350
> XRDDEV-1350 Client selection member code validation

- src/proxy-ui-api/frontend/src/assets/global-style.scss
- src/proxy-ui-api/frontend/src/components/ui/FormLabel.vue
- src/proxy-ui-api/frontend/src/components/ui/SubViewTitle.vue
- src/proxy-ui-api/frontend/src/views/AddSubsystem/AddSubsystem.vue
- src/proxy-ui-api/frontend/src/views/AppLogin.vue
- src/proxy-ui-api/frontend/src/views/Clients/Client.vue
- src/proxy-ui-api/frontend/src/views/Clients/ClientsDataTable.vue
- src/proxy-ui-api/frontend/src/views/Clients/Details/ClientDetails.vue
- src/proxy-ui-api/frontend/src/views/Clients/Services/Services.vue
- src/proxy-ui-api/frontend/src/views/Clients/Subsystem.vue
- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/SignAndAuthKeys/KeyRow.vue
https://jira.niis.org/browse/XRDDEV-1244
> XRDDEV-1244: Add fixes to ui breaking when there's long identifiers

- src/proxy-ui-api/frontend/src/views/AddClient/ClientDetailsPage.vue
- src/proxy-ui-api/frontend/src/views/AddMember/MemberDetailsPage.vue
https://jira.niis.org/browse/XRDDEV-1364
- Fix member code input error state in add member wizard
- Remove translation related warning from browser console generated by vee-validate
> XRDDEV-1364 Initial state of client selection for incorrect in add member wizard

- src/proxy-ui-api/frontend/package-lock.json
* https://www.npmjs.com/advisories/1561
> NPM audit fix: node-forge

- src/proxy-ui-api/frontend/src/store/modules/user.ts
JIRA: https://jira.niis.org/browse/XRDDEV-1359
> XRDDEV-1359 Remove cache busting (deprecated) from logout

- src/proxy-ui-api/frontend/tests/unit/vuex.spec.ts
Fixes the frontend's broken vuex unit tests
> Fix frontend unit tests

- src/proxy-ui-api/frontend/tests/e2e/pages/endpoints/accessRightsPage.js
- src/proxy-ui-api/frontend/tests/e2e/pages/ssMainPage.js
- src/proxy-ui-api/frontend/tests/e2e/specs/ss-clients-openapiservices.js
- src/proxy-ui-api/frontend/tests/e2e/specs/ss-clients-restservices.js
- src/proxy-ui-api/frontend/tests/e2e/specs/ss-clients-serviceclients.js
- src/proxy-ui-api/frontend/tests/e2e/specs/ss-clients-wsdlservices.js
- src/proxy-ui-api/frontend/tests/e2e/specs/ss-permissions-localgroups.js
> E2etestfixes localgroups services

- src/proxy-ui-api/frontend/src/views/Clients/ServiceClients/ServiceSelectionStep.vue
JIRA ticket: https://jira.niis.org/browse/XRDDEV-1407
> XRDDEV-1407: make the filtering case-insensitive

- src/proxy-ui-api/frontend/package-lock.json
- src/proxy-ui-api/frontend/src/store/modules/certificateSignRequest.ts
- src/proxy-ui-api/frontend/src/views/GenerateCertificateSignRequest/GenerateCertificateSignRequest.vue
- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/SignAndAuthKeys/TokenExpandable.vue
https://jira.niis.org/browse/XRDDEV-1425
> XRDDEV-1425 limit HSM CSR creation to SIGNING usage

- src/proxy-ui-api/frontend/src/store/index.ts
https://jira.niis.org/browse/XRDDEV-1405
> XRDDEV-1405: Save user module data to session storage instead of local storage

- src/proxy-ui-api/frontend/package-lock.json
- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/SignAndAuthKeys/KeyRow.vue
- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/SignAndAuthKeys/TokenExpandable.vue
- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/SignAndAuthKeys/UnknownKeysTable.vue
https://jira.niis.org/browse/XRDDEV-1426
> XRDDEV-1426

- src/proxy-ui-api/frontend/src/components/ui/Snackbar.vue
https://jira.niis.org/browse/XRDDEV-1445
> XRDDEV-1445 Fix snakbar style bug

- src/proxy-ui-api/frontend/src/components/layout/AppFooter.vue
- src/proxy-ui-api/frontend/src/locales/en.json
- Add link to an external web page that provides more information about licencing.
JIRA issue: https://jira.niis.org/browse/XRDDEV-1455
> XRDDEV-1455 Update licence information in the footer

- src/proxy-ui-api/build.gradle
- src/proxy-ui-api/frontend/nightwatch.json
- src/proxy-ui-api/frontend/package.json
Various imrovements to aws e2e testing
> E2etest aws improvements

- src/proxy-ui-api/frontend/src/router.ts
- src/proxy-ui-api/frontend/src/views/CertificateDetails/CertificateDetails.vue
- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/SignAndAuthKeys/CertificateRow.vue
- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/SignAndAuthKeys/UnknownKeysTable.vue
https://jira.niis.org/browse/XRDDEV-1457
> XRDDEV-1457: Fix broken certificate details link

- src/center-ui/app/controllers/licence_info_controller.rb
- src/center-ui/app/helpers/application_helper.rb
- src/center-ui/app/views/licence_info/index.html.erb
- src/center-ui/config/locales/controllers_en.yml
- src/center-ui/config/locales/controllers_et.yml
- src/center-ui/config/locales/views_en.yml
- src/center-ui/config/locales/views_et.yml
https://jira.niis.org/browse/XRDDEV-1459
> XRDDEV-1459 Add licence info to CS UI

- src/proxy-ui-api/frontend/src/components/layout/AppFooter.vue
- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/SignAndAuthKeys/UnknownKeysTable.vue
- src/proxy-ui-api/frontend/src/views/TokenDetails/TokenDetails.vue
Prevent user from editing token friendly name if it is not possible
> XRDDEV-1476

- src/proxy-ui-api/frontend/package-lock.json
- src/proxy-ui-api/frontend/src/components/layout/AppFooter.vue
- src/proxy-ui-api/frontend/src/components/wizard/WizardPageKeyLabel.vue
- src/proxy-ui-api/frontend/src/router.ts
- src/proxy-ui-api/frontend/src/views/AddKey/AddKey.vue
- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/SignAndAuthKeys/SignAndAuthKeys.vue
https://jira.niis.org/browse/XRDDEV-1454
> XRDDEV-1454 limit hsm key to signin

- src/build.gradle
- src/proxy-ui-api/build.gradle
- src/proxy-ui-api/frontend/package-lock.json
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/DiagnosticsApiControllerTest.java
https://jira.niis.org/browse/XRDDEV-1392
> XRDDEV-1392 upgrade spring versions, fix DiagnosticsApiControllerTest

- src/common-util/src/main/resources/akka-global.conf
Make confproxy timeouts less probable
> XRDDEV-1487

- src/signer/src/main/java/ee/ria/xroad/signer/protocol/handler/GetMemberSigningInfoRequestHandler.java
Improved error message for when user tries to register member while token is not logged in.
https://jira.niis.org/browse/XRDDEV-1481
> XRDDEV-1481

- src/proxy-ui-api/frontend/package-lock.json
- src/proxy-ui-api/frontend/src/assets/global-style.scss
- src/proxy-ui-api/frontend/src/assets/tables.scss
- src/proxy-ui-api/frontend/src/assets/wizards.scss
- src/proxy-ui-api/frontend/src/components/wizard/CsrDetailsPageLocked.vue
- src/proxy-ui-api/frontend/src/components/wizard/GenerateCsrPage.vue
- src/proxy-ui-api/frontend/src/components/wizard/SignKeyPage.vue
- src/proxy-ui-api/frontend/src/components/wizard/TokenPage.vue
- src/proxy-ui-api/frontend/src/components/wizard/WizardPageCsrDetails.vue
- src/proxy-ui-api/frontend/src/components/wizard/WizardPageGenerateCsr.vue
- src/proxy-ui-api/frontend/src/components/wizard/WizardPageKeyLabel.vue
- src/proxy-ui-api/frontend/src/views/AddClient/AddClient.vue
- src/proxy-ui-api/frontend/src/views/AddClient/ClientDetailsPage.vue
- src/proxy-ui-api/frontend/src/views/AddClient/FinishPage.vue
- src/proxy-ui-api/frontend/src/views/AddMember/FinishPage.vue
- src/proxy-ui-api/frontend/src/views/AddSubsystem/AddSubsystem.vue
- src/proxy-ui-api/frontend/src/views/Clients/ClientsDataTable.vue
- src/proxy-ui-api/frontend/vue.config.js
- src/shared-ui/package-lock.json
- src/shared-ui/src/components/CloseButton.vue
- src/shared-ui/src/components/FormLabel.vue
- src/shared-ui/src/components/LargeButton.vue
- src/shared-ui/src/components/SmallButton.vue
- src/shared-ui/src/components/SubViewTitle.vue
https://jira.niis.org/browse/XRDDEV-1490
Version 7 update to add client + add member wizards
> XRDDEV-1490 v7 Add client + add member wizards

- Docker/securityserver/files/ss-entrypoint.sh
JIRA: https://jira.niis.org/browse/XRDDEV-1401
> XRDDEV-1401 Remove nginx reference from Docker ss entrypoint script

- src/proxy-ui-api/frontend/src/views/AppBase.vue
- src/proxy-ui-api/frontend/src/views/Diagnostics/Diagnostics.vue
- src/proxy-ui-api/frontend/src/views/Settings/BackupAndRestore/BackupAndRestore.vue
- src/proxy-ui-api/frontend/src/views/Settings/BackupAndRestore/BackupsDataTable.vue
- src/proxy-ui-api/frontend/src/views/Settings/BackupAndRestore/DeleteBackupButton.vue
- src/proxy-ui-api/frontend/src/views/Settings/BackupAndRestore/RestoreBackupButton.vue
- src/proxy-ui-api/frontend/src/views/Settings/Settings.vue
- src/proxy-ui-api/frontend/src/views/Settings/SystemParameters/SystemParameters.vue
- src/proxy-ui-api/frontend/src/views/Settings/SystemParameters/TimestampingServiceRow.vue
https://jira.niis.org/browse/XRDDEV-1493
> XRDDEV-1493 v7 settings & diagnostics

- doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md
- src/proxy-ui-api/frontend/package-lock.json
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/auth/ApiKeyAuthenticationHelper.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/auth/ApiKeyAuthenticationManager.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/config/TtlConcurrentMapCacheConfiguration.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/controller/ApiKeysController.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/converter/PublicApiKeyDataConverter.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/dto/PlaintextApiKeyDto.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/ApiKeyService.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/CertificateAuthorityService.java
- src/proxy-ui-api/src/main/resources/common-application.yml
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/controller/ApiKeysControllerTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/converter/PublicApiKeyDataConverterTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/service/ApiKeyServiceCachingIntegrationTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/service/ApiKeyServiceIntegrationTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/service/CertificateAuthorityServiceTest.java
https://jira.niis.org/browse/XRDDEV-1395
> XRDDEV-1395 cache TTL

- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/SignAndAuthKeys/SignAndAuthKeys.vue
Update Keys and Certificates view search field label from "Service" to "Search". Other top level views (Clients + Backup and Restore) use the same label in the search field.
JIRA: https://jira.niis.org/browse/XRDDEV-1465
> XRDDEV-1465 

- src/proxy-ui-api/frontend/package-lock.json
Fix npm audit issue with updated package-lock file.
> Fix npm audit with updated package-lock.json

- src/proxy-ui-api/frontend/src/components/client/SelectClientDialog.vue
- src/proxy-ui-api/frontend/src/locales/en.json
- src/proxy-ui-api/frontend/src/views/AddClient/ClientDetailsPage.vue
- src/proxy-ui-api/frontend/src/views/AddMember/MemberDetailsPage.vue
- src/proxy-ui-api/frontend/src/views/AddSubsystem/AddSubsystem.vue
Update add client, member and subsystem dialog texts to be aligned with the context:
- Update dialog titles.
- Update search labels.
JIRA: https://jira.niis.org/browse/XRDDEV-1473
> XRDDEV-1473

- src/proxy-ui-api/frontend/src/locales/en.json
- src/proxy-ui-api/frontend/src/plugins/vee-validate.ts
- src/proxy-ui-api/frontend/src/views/Service/Endpoints/AddEndpointDialog.vue
- src/proxy-ui-api/frontend/src/views/Service/Endpoints/Endpoint/EndpointDetails.vue
https://jira.niis.org/browse/XRDDEV-1480
> XRDDEV-1480 Improve endpoind validation

- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/openapi/ClientsApiController.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/openapi/LocalGroupsApiController.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/openapi/validator/LocalGroupAddValidator.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/openapi/validator/LocalGroupDescriptionValidator.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/IdentifierValidationRestTemplateTest.java
Local group adding and editing is now validated for control characters
JIRA: https://jira.niis.org/browse/XRDDEV-1475
> XRDDEV-1475 non printing chars

- src/proxy-ui-api/frontend/nightwatch.json
- src/proxy-ui-api/frontend/tests/e2e/pages/ssMainPage.js
- src/proxy-ui-api/frontend/tests/e2e/pages/tabs/keysTab.js
- src/proxy-ui-api/frontend/tests/e2e/specs/ss-keyscerts-authsignkeys.js
XRDDEV-1050 added keys and certs e2e tests
Added default window size
> Xrddev 1050 e2etests keyscertstab

- src/proxy-ui-api/build.gradle
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/ApiValidationRestTemplateTest.java
https://jira.niis.org/browse/XRDDEV-1548
> XRDDEV-1548 fix broken api validation, and add test for validation

- src/proxy-ui-api/frontend/src/global.ts
- src/proxy-ui-api/frontend/src/router.ts
- src/proxy-ui-api/frontend/src/store/modules/user.ts
- src/proxy-ui-api/frontend/src/ui-types.ts
- src/proxy-ui-api/frontend/src/views/Clients/Client.vue
- src/proxy-ui-api/frontend/src/views/Clients/Subsystem.vue
- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/KeysAndCertificates.vue
- src/proxy-ui-api/frontend/src/views/Settings/Settings.vue
https://jira.niis.org/browse/XRDDEV-1351
There is now only one source of truth for route and tab permissions.
New PR for the new 7.0.0 branch.
> XRDDEV-1351 Modify tab permissions checks

- src/proxy-ui-api/frontend/src/views/Clients/ServiceClients/MemberOrGroupSelectionStep.vue
JIRA ticket: https://jira.niis.org/browse/XRDDEV-1474
> XRDDEV-1474: fix selection not clearing when filtering service client subjects

- src/proxy-ui-api/frontend/src/views/Clients/ServiceClients/ServiceSelectionStep.vue
- src/proxy-ui-api/frontend/tests/e2e/pages/serviceClients/addSubjectMemberStepPage.js
- src/proxy-ui-api/frontend/tests/e2e/pages/serviceClients/addSubjectServiceStepPage.js
- src/proxy-ui-api/frontend/tests/e2e/pages/serviceClients/serviceClientsPage.js
- src/proxy-ui-api/frontend/tests/e2e/specs/ss-clients-serviceclients-add-subject.js
e2e tests for adding a new Service Client
JIRA: https://jira.niis.org/browse/XRDDEV-1541
> XRDDEV-1541 add subject dialog e2e

- Jenkinsfile
- src/proxy-ui-api/build.gradle
- src/proxy-ui-api/frontend/audit-resolve.json
- src/proxy-ui-api/frontend/package-lock.json
https://jira.niis.org/browse/XRDDEV-1499
See also https://bitbucket.niis.org/projects/X-ROAD/repos/x-road-utils/pull-requests/145/overview, both should be merged at the same time
> XRDDEV-1499 lighter npm audit

- src/proxy-ui-api/frontend/package-lock.json
- src/proxy-ui-api/frontend/package.json
- src/proxy-ui-api/frontend/src/global.ts
- src/proxy-ui-api/frontend/src/router.ts
- src/proxy-ui-api/frontend/src/routes.ts
- src/proxy-ui-api/frontend/src/store/modules/user.ts
https://jira.niis.org/browse/XRDDEV-1564
Refactored the way routes are added to router to fix error in unit tests.
> XRDDEV-1564 Fix vuex unit tests

- src/proxy-ui-api/frontend/src/views/InitialConfiguration/ConfigurationAnchorStep.vue
- src/proxy-ui-api/frontend/src/views/InitialConfiguration/InitialConfiguration.vue
- src/proxy-ui-api/frontend/src/views/InitialConfiguration/OwnerMemberStep.vue
- src/proxy-ui-api/frontend/src/views/InitialConfiguration/TokenPinStep.vue
https://jira.niis.org/browse/XRDDEV-1565
Updates server initialisation UI
> XRDDEV-1565 Update server init wizard

- src/proxy-ui-api/frontend/package-lock.json
- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/SignAndAuthKeys/TokenExpandable.vue
- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/SignAndAuthKeys/UnknownKeysTable.vue
- src/proxy-ui-api/src/main/resources/openapi-definition.yaml
https://jira.niis.org/browse/XRDDEV-1460
> XRDDEV-1460 make key.usage not required

- src/proxy-ui-api/frontend/src/util/ClientUtil.ts
- src/proxy-ui-api/frontend/src/views/AddClient/FinishPage.vue
… register new client if there is no active certificate for the member
https://jira.niis.org/browse/XRDDEV-1559
> XRDDEV-1559

- src/proxy-ui-api/frontend/package-lock.json
- src/proxy-ui-api/frontend/package.json
- src/proxy-ui-api/frontend/src/components/client/SelectClientDialog.vue
- src/proxy-ui-api/frontend/src/components/service/WarningDialog.vue
- src/proxy-ui-api/frontend/src/components/ui/HelpDialog.vue
- src/proxy-ui-api/frontend/src/views/AppBase.vue
- src/proxy-ui-api/frontend/src/views/LocalGroup/AddMembersDialog.vue
- src/proxy-ui-api/frontend/src/views/Service/AccessRightsDialog.vue
- src/proxy-ui-api/frontend/src/views/Settings/SystemParameters/AddTimestampingServiceDialog.vue
- src/proxy-ui-api/frontend/src/views/Settings/SystemParameters/UploadConfigurationAnchorDialog.vue
- src/shared-ui/package-lock.json
- src/shared-ui/src/components/HelpDialog.vue
- src/shared-ui/src/components/SimpleDialog.vue
Add v-if to all usages of v-dialog component to remove it from the DOM while it is not visible in the UI
https://jira.niis.org/browse/XRDDEV-1563
> XRDDEV-1563

- src/proxy-ui-api/frontend/src/components/ui/GlobalAlerts.vue
JIRA: https://jira.niis.org/browse/XRDDEV-1468
> XRDDEV-1468 Add permission check to token login alert

- src/proxy-ui-api/frontend/src/views/AppBase.vue
- src/proxy-ui-api/frontend/src/views/Settings/SystemParameters/AddTimestampingServiceDialog.vue
Fix add timestamping service button missing bug
> XRDDEV-1593

- ansible/ss_cluster/README.md
- doc/Manuals/LoadBalancing/ig-xlb_x-road_external_load_balancer_installation_guide.md
- doc/Manuals/ig-csha_x-road_6_ha_installation_guide.md
Replaced master/slave with primary/replica in documentation files.
It turned out blacklist/whitelist was not used in our docs.
> XRDEV-1153

- src/proxy-ui-api/frontend/package-lock.json
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/openapi/BackupsApiController.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/BackupsApiControllerTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/CertificateAuthoritiesApiControllerTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/util/FormatUtilsTest.java
Fix two Sonar blockers that are making beta quality gate fail.
Failed Sonar report: https://sonarqube.niis.org/dashboard?id=xroad
Fixed Sonar: https://sonarqube.niis.org/dashboard?branch=fix-6.26-beta-quality-gate-sonar&id=xroad
> Fix 6.26 beta quality gate sonar

- src/proxy-ui-api/frontend/src/views/Clients/ServiceClients/AddServiceClientServiceDialog.vue
- src/shared-ui/src/components/SimpleDialog.vue
https://jira.niis.org/browse/XRDDEV-1470
> XRDDEV-1470 Dialog scroll fix

- src/proxy/src/main/java/ee/ria/xroad/proxy/clientproxy/ClientProxy.java
- src/shared-ui/audit-resolve.json
Add x-forwarded-for header value to proxy accesslog
https://jira.niis.org/browse/XRDDEV-427
> XRDDEV-427

- doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/ClearCacheService.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/InternalTlsCertificateService.java
- src/proxy-ui-api/src/main/resources/common-application.yml
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/service/InternalTlsCertificateServiceTest.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/ProxyMain.java
- src/serverconf/src/main/java/ee/ria/xroad/common/conf/serverconf/CachingServerConfImpl.java
- src/serverconf/src/main/java/ee/ria/xroad/common/conf/serverconf/ServerConf.java
- src/serverconf/src/main/java/ee/ria/xroad/common/conf/serverconf/ServerConfProvider.java
internal key cache clearing for proxy
> XRDDEV-964

- src/proxy-ui-api/frontend/src/views/Diagnostics/Diagnostics.vue
https://jira.niis.org/browse/XRDDEV-1610
Small adjustment to the timestamping table in diagnostics view.
> XRDDEV-1610 Timestamping previous field

- src/proxy-ui-api/frontend/src/routes.ts
- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/SignAndAuthKeys/TokenExpandable.vue
- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/SignAndAuthKeys/UnknownKeysTable.vue
https://jira.niis.org/browse/XRDDEV-1551
Add missing parameter to the certificate details route
> XRDDEV-1551 Add usage to url parameters

- src/addons/wsdlvalidator/build.gradle
- src/build.gradle
- src/monitor-common/build.gradle
- src/monitor-test/build.gradle
- src/monitor/build.gradle
- src/proxy-ui-api/build.gradle
JIRA: https://jira.niis.org/browse/XRDDEV-1592
> XRDDEV-1592 jcenter cleanup

- src/proxy-ui-api/frontend/src/App.vue
- src/proxy-ui-api/frontend/src/components/layout/TabsBaseEmpty.vue
- src/proxy-ui-api/frontend/src/components/ui/AlertsContainer.vue
- src/proxy-ui-api/frontend/src/components/ui/GlobalAlerts.vue
- src/proxy-ui-api/frontend/src/main.ts
- src/proxy-ui-api/frontend/src/routes.ts
- src/proxy-ui-api/frontend/src/views/Clients/ServiceClients/ServiceClientAccessRights.vue
- src/proxy-ui-api/frontend/src/views/Clients/ServiceClients/ServiceSelectionStep.vue
- src/proxy-ui-api/frontend/src/views/LocalGroup/AddMembersDialog.vue
- src/proxy-ui-api/frontend/src/views/Service/AccessRightsDialog.vue
- src/proxy-ui-api/frontend/src/views/Service/Endpoints/Endpoints.vue
- src/proxy-ui-api/frontend/src/views/Service/Service.vue
https://jira.niis.org/browse/XRDDEV-1552
- Added missing route parameters to service endpoints views though it seemed to work fine without them
- Added title parameter to AccessRightsDialog, because it was used when launching the dialog
- Cleaned up some unused code
> XRDDEV-1552 route parameters

- src/proxy-ui-api/frontend/src/assets/global-style.scss
- src/proxy-ui-api/frontend/src/global.ts
- src/proxy-ui-api/frontend/src/locales/en.json
- src/proxy-ui-api/frontend/src/plugins/vee-validate.ts
- src/proxy-ui-api/frontend/src/views/TokenDetails/TokenDetails.vue
- src/shared-ui/src/components/Expandable.vue
JIRA: https://jira.niis.org/browse/XRDDEV-1226
> XRDDEV-1226 Pin change frontend

- ansible/roles/xroad-cs/tasks/main.yml
- ansible/roles/xroad-cs/tasks/ubuntu.yml
- ansible/roles/xroad-ss/tasks/main.yml
- ansible/roles/xroad-ss/tasks/rhel.yml
- ansible/roles/xroad-ss/tasks/ubuntu.yml
- ansible/roles/xroad-ss/templates/db.properties
- ansible/roles/xroad-ss/templates/xroad.properties
- doc/Manuals/ig-cs_x-road_6_central_server_installation_guide.md
- doc/Manuals/ig-ss_x-road_v6_security_server_installation_guide.md
- doc/Manuals/ig-ss_x-road_v6_security_server_installation_guide_for_rhel.md
- src/packages/src/xroad-jetty9/ubuntu/generic/control
- src/packages/src/xroad/ubuntu/generic/control
- src/packages/src/xroad/ubuntu/generic/xroad-base.postinst
* Update installation instructions
* Update ansible scripts
* Packaging fixes
> XRDDEV-1591: Update remote database installation

- src/proxy-ui-api/frontend/src/views/Settings/SystemParameters/AddTimestampingServiceDialog.vue
- src/proxy-ui-api/frontend/src/views/Settings/SystemParameters/SystemParameters.vue
- src/proxy-ui-api/frontend/src/views/Settings/SystemParameters/TimestampingServiceRow.vue
- src/proxy-ui-api/frontend/src/views/Settings/SystemParameters/UploadConfigurationAnchorDialog.vue
https://jira.niis.org/browse/XRDDEV-1642
Fixes permission issues in couple of buttons on system parameters view.
> XRDDEV-1642 Fix permission issues in system parameters buttons

- src/centralserver/admin-ui/.gitignore
- src/centralserver/admin-ui/chromedriver.log
- src/centralserver/admin-ui/nightwatch.config.js
- src/centralserver/admin-ui/nightwatch.json
- src/centralserver/admin-ui/package-lock.json
- src/centralserver/admin-ui/package.json
- src/centralserver/admin-ui/tests/e2e/page-objects/loginpage.js
- src/centralserver/admin-ui/tests/e2e/specs/login.js
Setup initial configuration for e2e-test. 
https://jira.niis.org/browse/XRDDEV-1657
> XRDDEV-1657

- src/packages/src/xroad/redhat/SPECS/xroad-proxy.spec
- src/packages/src/xroad/ubuntu/generic/xroad-proxy.postinst
A parameter was missing . Tested this script standalone (ie did not run actual upgrade)
> upgrade process fix

- src/addons/messagelog/scripts/archive-http-transporter.sh
- Fix shellcheck issues in archive-http-transporter
- Add a --noauth flag that skips client TLS authentication (useful e.g. for debugging).
> XRDDEV-1645

- ansible/ss_cluster/roles/master/tasks/serverconf_master_db.yml
- ansible/ss_cluster/roles/node/tasks/centos.yml
- ansible/ss_cluster/roles/slave/tasks/centos.yml
https://jira.niis.org/browse/XRDDEV-1673
> XRDDEV-1673 fix ss_cluster playbook on centos

- src/addons/proxymonitor/metaservice/build.gradle
- src/settings.gradle
Change proxymonitor gradle project name to make artifact id unique.
> Change proxymonitor gradle project name

- ansible/ss_cluster/roles/node/tasks/main.yml
- ansible/ss_cluster/roles/node/tasks/ubuntu.yml
- ansible/ss_cluster/roles/slave/tasks/serverconf_slave_db.yml
https://jira.niis.org/browse/XRDDEV-1660
Alternative implementation of https://github.com/nordic-institute/X-Road/pull/956, this one checks postgresql version instead of OS version for added robustness.
> XRDDEV-1660 test postgresql version instead of OS version

- src/proxy-ui-api/frontend/audit-resolve.json
- src/proxy-ui-api/frontend/package-lock.json
- src/shared-ui/audit-resolve.json
- src/shared-ui/package-lock.json
Add ignores for some npm audit issues
> Update npm audit ignores

- src/proxy-ui-api/frontend/package-lock.json
- src/shared-ui/package-lock.json
Fix for the shared ui verification error when installing security server frontend
> Fix for a shared ui verification error

- src/addons/wsdlvalidator/src/test/resources/error.wsdl
- src/addons/wsdlvalidator/src/test/resources/testservice.wsdl
- src/addons/wsdlvalidator/src/test/resources/warn.wsdl
- src/addons/wsdlvalidator/src/test/resources/warnanderror.wsdl
- src/addons/wsdlvalidator/src/test/resources/xsd/identifiers.xsd
- src/addons/wsdlvalidator/src/test/resources/xsd/swaref.xsd
- src/addons/wsdlvalidator/src/test/resources/xsd/xml.xsd
- src/addons/wsdlvalidator/src/test/resources/xsd/xmlmime.xsd
- src/addons/wsdlvalidator/src/test/resources/xsd/xroad.xsd
https://jira.niis.org/browse/XRDDEV-1732
> XRDDEV-1732 use local files for WSDLValidatorTest xsds

- src/proxy-ui-api/frontend/audit-resolve.json
- src/proxy-ui-api/frontend/package-lock.json
- src/proxy-ui-api/frontend/package.json
- src/shared-ui/audit-resolve.json
- src/shared-ui/package-lock.json
- src/shared-ui/package.json
> Update npm dependencies

- doc/Manuals/LoadBalancing/ig-xlb_x-road_external_load_balancer_installation_guide.md
- src/proxy/src/main/java/ee/ria/xroad/common/util/healthcheck/HealthChecks.java
- src/proxy/src/main/java/ee/ria/xroad/common/util/healthcheck/StoppableCombinationHealthCheckProvider.java
- src/proxy/src/test/java/ee/ria/xroad/common/util/healthcheck/HealthChecksTest.java
JIRA: https://jira.niis.org/browse/XRDDEV-1749
> XRDDEV-1749 Health check global conf

- src/proxy-ui-api/frontend/package-lock.json
Version mismatch in package.json -> causing build failures in CI
> Janitoring: Update chromedriver version 93 in package-lock

- src/proxy-ui-api/frontend/package-lock.json
- src/shared-ui/package-lock.json
> Update package-lock files

- doc/UseCases/uc-ss_x-road_use_case_model_for_security_server_management_1.4_Y-883-4.md
https://jira.niis.org/browse/XRDDEV-1795
Update use case documentation about key delete to match current implementation
> XRDDEV-1795 update use cases about key deletion

- src/proxy-ui-api/frontend/src/assets/global-style.scss
- src/proxy-ui-api/frontend/src/views/Clients/ClientsDataTable.vue
- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/ApiKey/ApiKey.vue
Add some padding to Security Server clients data table as seen in 7.x Central Server
JIRA: https://jira.niis.org/browse/XRDDEV-1826
> XRDDEV-1826 Add extra padding bottom to clients data table

- src/centralserver/admin-ui/src/assets/global-style.scss
- src/centralserver/admin-ui/src/store/modules/system.ts
- src/centralserver/admin-ui/src/views/GlobalResources/GlobalResources.vue
- src/centralserver/admin-ui/src/views/Settings/SettingsTabs.vue
- src/centralserver/admin-ui/src/views/Settings/SystemSettings/SystemSettings.vue
Fix font weights of input fields
Fix letter spacing in tabs
Fix excess margin top in sub views
JIRA: https://jira.niis.org/browse/XRDDEV-1826
> XRDDEV-1826 Unify styling 7x

- src/centralserver/admin-ui/package-lock.json
- src/centralserver/admin-ui/package.json
- src/centralserver/admin-ui/src/views/GlobalConfiguration/GlobalConfigurationTabs.vue
- src/centralserver/admin-ui/src/views/Settings/SettingsTabs.vue
- src/shared-ui/package-lock.json
JIRA: https://jira.niis.org/browse/XRDDEV-1844
> XRDDEV-1844 Subtab slider bug in 7x

- src/proxy-ui-api/frontend/package-lock.json
- src/proxy-ui-api/frontend/package.json
- src/proxy-ui-api/frontend/src/store/modules/user.ts
- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/KeysAndCertificatesTabs.vue
- src/proxy-ui-api/frontend/src/views/Settings/SettingsTabs.vue
JIRA: https://jira.niis.org/browse/XRDDEV-1844
* upgrade Vuetify to 2.6.0
* change sub tab path matching to exact-path
> XRDDEV-1844 Fix tabs slider bug

- src/proxy-ui-api/build.gradle
- src/proxy-ui-api/frontend/audit-resolve.json
- src/proxy-ui-api/frontend/package-lock.json
- src/shared-ui/audit-resolve.json
- src/shared-ui/package-lock.json
- src/shared-ui/package.json
Updates node.js version and fixes current npm audit issues.
> Update node.js from 12.x to 14.x

- src/packages/src/xroad/common/base/etc/xroad/services/global.conf
- src/proxy-ui-api/frontend/audit-resolve.json
- src/proxy-ui-api/frontend/package-lock.json
- src/proxy-ui-api/src/test/java/org/niis/xroad/securityserver/restapi/wsdl/WsdlParserTest.java
- src/proxy-ui-api/src/test/resources/wsdl/xxe.wsdl
- src/shared-ui/audit-resolve.json
- src/shared-ui/package-lock.json
* add test
* restrict external stylesheets in xml
> XRDDEV-1855 Restrict xxe globally

- src/proxy-ui-api/frontend/package-lock.json
- src/proxy-ui-api/frontend/package.json
- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/KeysAndCertificatesTabs.vue
- src/proxy-ui-api/frontend/src/views/Settings/SettingsTabs.vue
* upgrade Vuetify to 2.6.0
* change sub tab path matching to exact-path
> XRDDEV-1844 Fix tabs slider bug in 7.0

- src/proxy-ui-api/frontend/src/views/Clients/ServiceClients/AddServiceClientServiceDialog.vue
- src/proxy-ui-api/frontend/src/views/Clients/ServiceClients/ServiceSelectionStep.vue
https://jira.niis.org/browse/XRDDEV-1861
> XRDDEV-1861 Fix service tables title column

- src/proxy-ui-api/frontend/src/views/Clients/Services/Services.vue
- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/SignAndAuthKeys/SignAndAuthKeys.vue
- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/SignAndAuthKeys/TokenExpandable.vue
- src/proxy-ui-api/frontend/src/views/TokenDetails/TokenDetails.vue
- src/shared-ui/src/components/EmptyPlaceholder.stories.js
- src/shared-ui/src/components/EmptyPlaceholder.vue
- src/shared-ui/src/components/EmptyPlaceholderRow.vue
- src/shared-ui/src/components/Expandable.vue
https://jira.niis.org/browse/XRDDEV-1852
https://jira.niis.org/browse/XRDDEV-1853
Add loading indicators to html tables and for sign and auth keys view.
> XRDDEV-1852 & XRDDEV-1853 Loading states

- src/proxy-ui-api/frontend/src/views/Clients/LocalGroups/LocalGroups.vue
> Fix css classes in localgroups table

- src/proxy-ui-api/frontend/src/views/Clients/ServiceClients/ServiceClients.vue
Add data-test id for service clients table to fix e2e tests
> Add data-test for service clients table

- src/centralserver/admin-service/build.gradle
- src/common-rest-api/src/main/java/org/niis/xroad/restapi/config/AddCorrelationIdFilter.java
- src/packages/src/xroad/default-configuration/centralserver-admin-service-logback.xml
- src/proxy-ui-api/build.gradle
- src/proxy-ui-api/src/main/java/org/niis/xroad/securityserver/restapi/config/IpThrottlingFilter.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/securityserver/restapi/config/LimitRequestSizesFilter.java
JIRA: https://jira.niis.org/browse/XRDDEV-1854
> XRDDEV-1854 Correlation id in CS

- doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md
JIRA: https://jira.niis.org/browse/XRDDEV-1851
> XRDDEV-1851 Add a chapter about password policies

- src/proxy-ui-api/frontend/src/store/modules/notifications.ts
- src/proxy-ui-api/frontend/src/ui-types.ts
- src/proxy-ui-api/frontend/src/views/AppLogin.vue
Additional PR for the issue https://jira.niis.org/browse/XRDDEV-1864
Small notification related fixes for security server frontend.
> XRDDEV-1864 Error message typing

- src/proxy-ui-api/frontend/src/components/ui/ContextualAlerts.vue
- src/proxy-ui-api/frontend/src/components/ui/GlobalAlerts.vue
- src/proxy-ui-api/frontend/src/views/AppLogin.vue
* margin-top 16px instead of 8px
JIRA: https://jira.niis.org/browse/XRDDEV-1856
> XRDDEV-1856 Align alerts with the styleguide

- src/proxy-ui-api/frontend/src/views/Clients/ServiceClients/AddServiceClientServiceDialog.vue
- src/proxy-ui-api/frontend/src/views/Clients/ServiceClients/ServiceSelectionStep.vue
- src/proxy-ui-api/frontend/src/views/Clients/Services/Services.vue
- src/proxy-ui-api/frontend/src/views/KeysAndCertificates/SignAndAuthKeys/SignAndAuthKeys.vue
https://jira.niis.org/browse/XRDDEV-1472
Unifying the search methods in tables
> XRDDEV-1472 Update search methods

- src/addons/messagelog/messagelog-addon/src/main/java/ee/ria/xroad/proxy/messagelog/LogRecordManager.java
- src/addons/messagelog/messagelog-addon/src/main/java/ee/ria/xroad/proxy/messagelog/SingleTimestampRequest.java
- src/addons/messagelog/messagelog-addon/src/main/java/ee/ria/xroad/proxy/messagelog/TaskQueue.java
- src/addons/messagelog/messagelog-addon/src/main/java/ee/ria/xroad/proxy/messagelog/TimestamperWorker.java
- src/packages/src/xroad/common/addon/proxy/messagelog-changelog.xml
- src/packages/src/xroad/common/addon/proxy/messagelog/10-timestamping-fix.xml
In certain conditions a single message record was timestamped
multiple times, causing an out of heap space error (XRDSD-222).
> XRDDEV-1876: Fix a message record can be timestamped multiple times

- src/centralserver/admin-ui/src/locales/en.json
- src/centralserver/admin-ui/src/views/GlobalConfiguration/TrustedAnchors/TrustedAnchors.vue
- src/centralserver/admin-ui/src/views/GlobalConfiguration/shared/Configuration.vue
- src/centralserver/admin-ui/src/views/GlobalConfiguration/shared/KeysTable.vue
- src/centralserver/admin-ui/src/views/Settings/BackupAndRestore/BackupAndRestore.vue
- src/centralserver/admin-ui/src/views/Settings/BackupAndRestore/BackupsDataTable.vue
- src/centralserver/admin-ui/src/views/Settings/SystemSettings/SystemSettings.vue
https://jira.niis.org/browse/XRDDEV-1862
> XRDDEV-1862 CS loading placeholders

- src/common-rest-api/src/main/java/org/niis/xroad/restapi/auth/ApiKeyAuthenticationManager.java
- src/common-rest-api/src/main/java/org/niis/xroad/restapi/auth/PamAuthenticationProvider.java
- src/common-rest-api/src/main/java/org/niis/xroad/restapi/auth/PamAuthenticationProviderConfig.java
- src/common-rest-api/src/main/java/org/niis/xroad/restapi/util/SecurityHelper.java
- src/common-rest-api/src/test/java/org/niis/xroad/restapi/auth/AuthenticationHeaderDecoderTest.java
- src/common-rest-api/src/test/java/org/niis/xroad/restapi/auth/AuthenticationIpWhitelistTest.java
- src/common-rest-api/src/test/java/org/niis/xroad/restapi/auth/GrantedAuthorityMapperTest.java
- src/common-rest-api/src/test/java/org/niis/xroad/restapi/auth/RoleTest.java
- src/common-rest-api/src/test/java/org/niis/xroad/restapi/util/SecurityHelperTest.java
JIRA: https://jira.niis.org/browse/XRDDEV-1827
> XRDDEV-1827 2nd node disable edit

- src/proxy-ui-api/frontend/audit-resolve.json
- src/proxy-ui-api/frontend/package-lock.json
- src/shared-ui/audit-resolve.json
- src/shared-ui/package-lock.json
- src/shared-ui/package.json
> NPM audit related updates

- src/proxy-ui-api/frontend/src/components/certificate/CertificateHash.vue
e2e tests passed at https://jenkins.niis.org/job/rest-ui-e2e-tests/944/ (packages were built and installed in restuitest-ss1)
adds one data-test tag, will merge myself
> XRDDEV-1716 add data-test tag for cert hash

- src/proxy-ui-api/frontend/package-lock.json
- src/proxy-ui-api/frontend/package.json
- src/shared-ui/package-lock.json
Update "openapi-typescript-codegen" and package-locks
> Fix npm audit

- src/packages/src/xroad/common/proxy/usr/share/xroad/scripts/restore_db.sh
> XRDDEV-1920: Fix restoring serverconf db with different user fails

- src/packages/src/xroad/redhat/SPECS/common.inc
- src/packages/src/xroad/redhat/SPECS/xroad-addon-messagelog.spec
- src/packages/src/xroad/redhat/SPECS/xroad-addon-wsdlvalidator.spec
- src/packages/src/xroad/redhat/SPECS/xroad-proxy-ui-api.spec
- src/packages/src/xroad/redhat/SPECS/xroad-proxy.spec
* Fix symlink to config file not correctly created during upgrade
* Minor packaging fixes
> XRDDEV-1921: Fix message log not working after upgrade (RHEL)

- Jenkinsfile
- src/proxy-ui-api/build.gradle
- src/proxy-ui-api/frontend/package.json
- src/shared-ui/build.gradle
- src/shared-ui/package.json
https://jira.niis.org/browse/XRDDEV-1878
> XRDDEV-1878 reconfigure npm audit (develop branch)

- src/proxy-ui-api/frontend/src/views/AppBase.vue
https://jira.niis.org/browse/XRDDEV-1951
> XRDDEV-1951 improve error notification visibility

- src/centralserver/admin-ui/src/views/AppBase.vue
https://jira.niis.org/browse/XRDDEV-1951
> XRDDEV-1951 improve error notification visibility 7.x

- src/proxy-ui-api/frontend/src/components/ui/ContextualAlerts.vue
- src/proxy-ui-api/frontend/src/store/modules/notifications.ts
- src/proxy-ui-api/frontend/src/ui-types.ts
https://jira.niis.org/browse/XRDDEV-1950
> XRDDEV-1950 Update error notification store

- src/centralserver/admin-ui/src/components/ui/ContextualAlerts.vue
- src/centralserver/admin-ui/src/components/ui/InitNotification.vue
- src/centralserver/admin-ui/src/components/ui/Snackbar.vue
- src/centralserver/admin-ui/src/locales/en.json
- src/centralserver/admin-ui/src/store/modules/notifications.ts
- src/centralserver/admin-ui/src/ui-types.ts
https://jira.niis.org/browse/XRDDEV-1950
> XRDDEV-1950 error store 7.x

- src/proxy-ui-api/frontend/tests/e2e/specs/ss-clients-restservices.js
There was extra codeblock that was able to pass our review process. removed erroneous code
> XRDDEV-1991 Copypaste error in rest tests

- src/common-util/src/main/java/ee/ria/xroad/common/AddOnStatusDiagnostics.java
- src/proxy-ui-api/frontend/package-lock.json
- src/proxy-ui-api/frontend/src/locales/en.json
- src/proxy-ui-api/frontend/src/views/Diagnostics/Diagnostics.vue
- src/proxy-ui-api/frontend/src/views/Settings/SystemParameters/SystemParameters.vue
- src/proxy-ui-api/frontend/src/views/Settings/SystemParameters/TimestampingServiceRow.vue
- src/proxy-ui-api/src/main/java/org/niis/xroad/securityserver/restapi/converter/AddOnStatusConverter.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/securityserver/restapi/converter/AddonStatusConverter.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/securityserver/restapi/openapi/DiagnosticsApiController.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/securityserver/restapi/service/DiagnosticService.java
- src/proxy-ui-api/src/main/resources/common-application.yml
- src/proxy-ui-api/src/main/resources/openapi-definition.yaml
- src/proxy-ui-api/src/test/java/org/niis/xroad/securityserver/restapi/openapi/DiagnosticsApiControllerTest.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/ProxyMain.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/messagelog/MessageLog.java
- src/shared-ui/src/components/StatusIcon.stories.js
- src/shared-ui/src/components/StatusIcon.vue
> XRDDEV-1961 - disabled messagelog API and UI changes

- src/centralserver/admin-ui/src/components/ui/ContextualAlerts.vue
Fixes the missing error notification for weak pin
> XRDDEV-1950 Fix bug in notification object handling Central Server

- src/proxy-ui-api/frontend/src/views/Settings/SystemParameters/SystemParameters.vue
https://jira.niis.org/browse/XRDDEV-2009
> XRDDEV-2009 bugfix for messageLogEnabled handling on the frontend

- CHANGELOG.md
- src/3RD-PARTY-NOTICES.txt
- src/addons/metaservice/build.gradle
- src/build.gradle
- src/center-service/build.gradle
- src/center-ui/build.gradle
- src/common-db/build.gradle
- src/common-rest-api/build.gradle
- src/common-util/build.gradle
- src/gradle.properties
- src/packages/build-rpm.sh
- src/packages/docker/rpm-el8/Dockerfile
- src/packages/download_jetty.sh
- src/packages/src/xroad-jetty9/generic/etc/xroad/jetty/start.ini
- src/packages/src/xroad-jetty9/jetty.url
- src/packages/src/xroad-jetty9/ubuntu/generic/changelog
- src/packages/src/xroad/common/signer/etc/xroad/services/signer-console.conf
- src/packages/src/xroad/redhat/SPECS/xroad-base.spec
- src/packages/src/xroad/ubuntu/generic/changelog
- src/packages/src/xroad/ubuntu/generic/xroad-base.install
- src/packages/src/xroad/ubuntu/generic/xroad-base.links
- src/proxy-ui-api-devtools/build.gradle
- src/proxy-ui-api/build.gradle
- src/proxy-ui-api/frontend/package-lock.json
- src/proxy/build.gradle
- src/shared-ui/audit-resolve.json
- src/shared-ui/package-lock.json
> Bugfix 7.0.3

- CHANGELOG.md
- src/packages/src/xroad-jetty9/ubuntu/generic/changelog
- src/packages/src/xroad/ubuntu/generic/changelog
Used `./version_change.sh --release 7.1.0` to update dates
> XRDDEV-2014 - Update `CHANGELOG.md`

- doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md
- Update Diagnostics section.
- Add more detailed instructions to backup encryption configuration.
- Minor updates to message log database encryption configuration.
- Minor updates to message log archive configuration.
> XRDDEV-2026 Updates to the Security Server user guide

- src/common-util/src/main/java/ee/ria/xroad/common/SystemProperties.java
- src/packages/src/xroad/default-configuration/proxy.ini
- src/proxy/src/main/java/ee/ria/xroad/common/util/healthcheck/StoppableCombinationHealthCheckProvider.java
JIRA: https://jira.niis.org/browse/XRDDEV-1561
> XRDDEV-1561 by default healthcheck of hardware security modules should be disabled

- src/common-messagelog/src/main/java/ee/ria/xroad/common/messagelog/archive/EncryptionConfigProvider.java
- src/common-messagelog/src/test/java/ee/ria/xroad/common/messagelog/archive/MemberEncryptionConfigProviderTest.java
- src/proxy-ui-api/frontend/src/views/Diagnostics/Diagnostics.vue
- src/proxy/src/main/java/ee/ria/xroad/proxy/ProxyMain.java
JIRA: https://jira.niis.org/browse/XRDDEV-2025
> XRDDEV-2025 Members without configured encryption keys in Diagnostic

- src/centralserver/admin-ui/src/views/Settings/ApiKeys/ApiKeys.vue
- src/centralserver/admin-ui/src/views/Settings/ApiKeys/CreateApiKeyStepper.vue
- src/centralserver/admin-ui/tests/e2e/page-objects/csApiKeysPage.js
- src/centralserver/admin-ui/tests/e2e/specs/060-cs-configuration-api_keys.js
Story: https://jira.niis.org/browse/XRDDEV-2053
> XRDDEV-2053 Central server API Keys remaining functionality

- src/centralserver/admin-service/src/test/java/org/niis/xroad/centralserver/restapi/converter/CertificationServiceConverterTest.java
Test fix for a story https://jira.niis.org/browse/XRDDEV-2031
> XRDDEV-2031: Fix test case, failing for mismatch in time assertion

- doc/Protocols/SecurityServerExtension/pr-targetss_security_server_targeting_extension_for_the_x-road_protocol.md
- doc/Protocols/SecurityTokenExtension/pr-sectoken_security_token_extension_for_the_x-road_protocol.md
- doc/Protocols/ThirdPartyRepresentationExtension/pr-third_party_representation_extension_for_the_x-road_protocol.md
- doc/Protocols/ThirdPartyRepresentationExtension/representation.xsd
- doc/README.md
- Add third party representation protocol extension document.
- Add third party representation protocol extension schema.
- Minor updates to other protocol extensions documents.
JIRA: https://jira.niis.org/browse/XRDDEV-2042
> XRDDEV-2042 Add third party representation protocol extension

- src/centralserver/admin-ui/src/locales/en.json
- src/centralserver/admin-ui/src/store/modules/global-groups.ts
- src/centralserver/admin-ui/src/views/GlobalResources/AddGroupDialog.vue
- src/centralserver/admin-ui/src/views/GlobalResources/GlobalResourcesList.vue
JIRA: https://jira.niis.org/browse/XRDDEV-2062
> XRDDEV-2062 A dialog is created for adding global groups and connected to the API

- src/packages/src/xroad/redhat/SPECS/xroad-opmonitor.spec
JIRA: https://jira.niis.org/browse/XRDDEV-2095
> XRDDEV-2095 Fix missing opmon db migrations during installation on RHEL8

- src/centralserver/admin-ui/tests/e2e/page-objects/csApiKeysPage.js
- src/centralserver/admin-ui/tests/e2e/specs/060-cs-configuration-api_keys.js
- src/centralserver/admin-ui/tests/e2e/specs/070-trust-services.js
Fix CS test cases with timing issues, failing to find not yet rendered elements.
> Fix CS test cases with timing issues

- src/centralserver/admin-ui/package-lock.json
- src/centralserver/admin-ui/package.json
- src/centralserver/admin-ui/src/views/GlobalResources/AddGroupDialog.vue
- src/centralserver/admin-ui/src/views/GlobalResources/GlobalResourcesList.vue
- src/centralserver/admin-ui/tests/e2e/page-objects/csGlobalGroupsPage.js
- src/centralserver/admin-ui/tests/e2e/specs/080-cs-global-groups.js
JIRA: https://nordic-institute.atlassian.net/browse/XRDDEV-2063
> XRDDEV-2063 E2E test for global group adding

- src/proxy-ui-api/src/main/java/org/niis/xroad/securityserver/restapi/service/ServiceDescriptionService.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/securityserver/restapi/service/ServiceDescriptionServiceIntegrationTest.java
When service description is removed, retain endpoints and ACLs if those
are referenced by other service versions
> XRDDEV-2112 Retain endpoints and ACLs when removing service description

- src/configuration-client/src/main/java/ee/ria/xroad/common/conf/globalconf/ConfigurationClientMain.java
- src/configuration-client/src/main/java/ee/ria/xroad/common/conf/globalconf/ConfigurationDownloader.java
- src/configuration-client/src/main/java/ee/ria/xroad/common/conf/globalconf/DownloadResult.java
Also includes slight code refactoring to make the code more readable, adding javadocs on more complex methods and using normal line length for code to look less blocky.
https://nordic-institute.atlassian.net/browse/XRDDEV-2097
> XRDDEV-2097 fix failing anchor re-upload in Security Server

- ansible/roles/build-packages/tasks/main.yml
https://nordic-institute.atlassian.net/browse/XRDDEV-2073
This is an updated user contribution
> Improving ansible build scripts

- Docker/centralserver/README.md
- Docker/securityserver/README.md
- Editorial changes to Central Server and Security Server Docker documentation.
> Update to CS and SS Docker documentation

- src/centralserver/admin-service/src/main/java/org/niis/xroad/centralserver/restapi/dto/converter/db/ClientDtoConverter.java
- src/centralserver/admin-service/src/main/java/org/niis/xroad/centralserver/restapi/openapi/ClientsApiController.java
- src/centralserver/admin-service/src/main/java/org/niis/xroad/centralserver/restapi/openapi/MemberClassesApiController.java
- src/centralserver/admin-service/src/main/java/org/niis/xroad/centralserver/restapi/service/ClientService.java
- src/centralserver/admin-service/src/main/resources/openapi-definition.yaml
- src/centralserver/admin-service/src/test/java/org/niis/xroad/centralserver/restapi/dto/converter/db/ClientDtoConverterTest.java
- src/centralserver/admin-service/src/test/java/org/niis/xroad/centralserver/restapi/openapi/ClientsApiControllerTest.java
- src/centralserver/admin-service/src/test/java/org/niis/xroad/centralserver/restapi/openapi/ClientsApiTest.java
- src/centralserver/admin-service/src/test/java/org/niis/xroad/centralserver/restapi/openapi/MemberClassesApiControllerTest.java
- src/centralserver/admin-service/src/test/java/org/niis/xroad/centralserver/restapi/service/ClientServiceTest.java
- src/centralserver/admin-ui/src/locales/en.json
- src/centralserver/admin-ui/src/store/modules/clients.ts
- src/centralserver/admin-ui/src/views/Members/Member/AddMemberDialog.vue
- src/centralserver/admin-ui/src/views/Members/MemberList.vue
- src/centralserver/admin-ui/src/views/TrustServices/AddApprovedCSDialog.vue
- src/common-rest-api/src/main/java/org/niis/xroad/restapi/config/audit/RestApiAuditEvent.java
- src/common-rest-api/src/main/java/org/niis/xroad/restapi/config/audit/RestApiAuditProperty.java
Also includes audit logging amendment
> XRDDEV-1934 - Add member UI

- src/e2e-tests/src/intTest/java/org/niis/xroad/test/ui/glue/CommonUiStepDefs.java
- src/e2e-tests/src/intTest/java/org/niis/xroad/test/ui/glue/SecurityServerBackupStepDefs.java
- src/e2e-tests/src/intTest/java/org/niis/xroad/test/ui/glue/centralserver/CentralServerMemberStepDefs.java
- src/e2e-tests/src/intTest/java/org/niis/xroad/test/ui/glue/constants/Constants.java
- src/e2e-tests/src/intTest/resources/behavior/ui/csAddMember.feature
https://nordic-institute.atlassian.net/browse/XRDDEV-1935
> XRDDEV-1935

- src/centralserver/admin-service/src/main/java/org/niis/xroad/centralserver/restapi/openapi/ClientsApiController.java
- src/centralserver/admin-service/src/main/java/org/niis/xroad/centralserver/restapi/repository/XRoadMemberRepository.java
- src/centralserver/admin-service/src/main/java/org/niis/xroad/centralserver/restapi/service/ClientService.java
- src/centralserver/admin-service/src/test/java/org/niis/xroad/centralserver/restapi/openapi/ClientsApiControllerTest.java
- src/centralserver/admin-service/src/test/java/org/niis/xroad/centralserver/restapi/openapi/ClientsApiTest.java
- src/centralserver/admin-service/src/test/java/org/niis/xroad/centralserver/restapi/repository/XRoadMemberRepositoryTest.java
- src/centralserver/admin-service/src/test/java/org/niis/xroad/centralserver/restapi/service/ClientServiceTest.java
https://nordic-institute.atlassian.net/browse/XRDDEV-2078
> XRDDEV-2078 client details api

- src/centralserver/admin-service/src/main/java/org/niis/xroad/centralserver/restapi/openapi/ClientsApiController.java
- src/centralserver/admin-service/src/main/java/org/niis/xroad/centralserver/restapi/repository/SecurityServerClientNameRepository.java
- src/centralserver/admin-service/src/main/java/org/niis/xroad/centralserver/restapi/service/ClientService.java
- src/centralserver/admin-service/src/test/java/org/niis/xroad/centralserver/restapi/openapi/ClientsApiControllerTest.java
- src/centralserver/admin-service/src/test/java/org/niis/xroad/centralserver/restapi/openapi/ClientsApiTest.java
- src/centralserver/admin-service/src/test/java/org/niis/xroad/centralserver/restapi/service/ClientServiceTest.java
https://nordic-institute.atlassian.net/browse/XRDDEV-2079
> XRDDEV-2079 update member name API endpoint

- src/centralserver/admin-service/src/main/java/org/niis/xroad/centralserver/restapi/openapi/ClientsApiController.java
- src/centralserver/admin-service/src/main/java/org/niis/xroad/centralserver/restapi/service/ClientService.java
- src/centralserver/admin-service/src/test/java/org/niis/xroad/centralserver/restapi/openapi/ClientsApiControllerTest.java
- src/centralserver/admin-service/src/test/java/org/niis/xroad/centralserver/restapi/openapi/ClientsApiTest.java
- src/centralserver/admin-service/src/test/java/org/niis/xroad/centralserver/restapi/service/ClientServiceTest.java
- src/centralserver/admin-ui/src/locales/en.json
- src/common-rest-api/src/main/java/org/niis/xroad/restapi/config/audit/RestApiAuditEvent.java
https://nordic-institute.atlassian.net/browse/XRDDEV-2080
> XRDDEV-2080 Implement delete member API

- src/centralserver/admin-service/src/main/java/org/niis/xroad/centralserver/restapi/converter/GroupMemberConverter.java
- src/centralserver/admin-service/src/main/java/org/niis/xroad/centralserver/restapi/converter/GroupMemberFilterModelConverter.java
- src/centralserver/admin-service/src/main/java/org/niis/xroad/centralserver/restapi/converter/PagedGroupMemberConverter.java
- src/centralserver/admin-service/src/main/java/org/niis/xroad/centralserver/restapi/entity/GlobalGroupMember.java
- src/centralserver/admin-service/src/main/java/org/niis/xroad/centralserver/restapi/openapi/GlobalGroupsApiController.java
- src/centralserver/admin-service/src/main/java/org/niis/xroad/centralserver/restapi/repository/GlobalGroupMemberRepository.java
- src/centralserver/admin-service/src/main/java/org/niis/xroad/centralserver/restapi/service/GlobalGroupService.java
- src/centralserver/admin-service/src/main/resources/openapi-definition.yaml
- src/centralserver/admin-service/src/test/java/org/niis/xroad/centralserver/restapi/converter/GlobalGroupConverterTest.java
- src/centralserver/admin-service/src/test/java/org/niis/xroad/centralserver/restapi/openapi/GlobalGroupApiTest.java
- src/centralserver/admin-service/src/test/java/org/niis/xroad/centralserver/restapi/service/GlobalGroupServiceTest.java
- src/centralserver/admin-ui/src/store/modules/global-groups.ts
- src/centralserver/admin-ui/src/views/GlobalResources/GlobalGroup/GlobalGroup.vue
- src/centralserver/admin-ui/src/views/GlobalResources/GlobalGroup/GroupMembersFilterDialog.vue
JIRA: https://nordic-institute.atlassian.net/browse/XRDDEV-2069
> XRDDEV-2069 Add Gloubal groups member search view

- src/centralserver/admin-service/src/main/java/org/niis/xroad/centralserver/restapi/dto/converter/db/ClientDtoConverter.java
- src/centralserver/admin-service/src/main/java/org/niis/xroad/centralserver/restapi/entity/SecurityServerClient.java
- src/centralserver/admin-service/src/main/java/org/niis/xroad/centralserver/restapi/entity/SecurityServerClientName.java
- src/centralserver/admin-service/src/main/java/org/niis/xroad/centralserver/restapi/openapi/ClientsApiController.java
- src/centralserver/admin-service/src/main/java/org/niis/xroad/centralserver/restapi/openapi/MembersApiController.java
- src/centralserver/admin-service/src/main/java/org/niis/xroad/centralserver/restapi/openapi/SubsystemsApiController.java
- src/centralserver/admin-service/src/main/java/org/niis/xroad/centralserver/restapi/service/MemberService.java
- src/centralserver/admin-service/src/main/java/org/niis/xroad/centralserver/restapi/service/SubsystemService.java
- src/centralserver/admin-service/src/main/java/org/niis/xroad/centralserver/restapi/service/exception/ErrorMessage.java
- src/centralserver/admin-service/src/main/resources/openapi-definition.yaml
- src/centralserver/admin-service/src/test/java/org/niis/xroad/centralserver/restapi/dto/converter/db/ClientDtoConverterTest.java
- src/centralserver/admin-service/src/test/java/org/niis/xroad/centralserver/restapi/openapi/ClientsApiControllerTest.java
- src/centralserver/admin-service/src/test/java/org/niis/xroad/centralserver/restapi/openapi/ClientsApiTest.java
- src/centralserver/admin-service/src/test/java/org/niis/xroad/centralserver/restapi/openapi/MembersApiControllerTest.java
- src/centralserver/admin-service/src/test/java/org/niis/xroad/centralserver/restapi/openapi/MembersApiTest.java
- src/centralserver/admin-service/src/test/java/org/niis/xroad/centralserver/restapi/openapi/SubsystemsApiControllerTest.java
- src/centralserver/admin-service/src/test/java/org/niis/xroad/centralserver/restapi/openapi/SubsystemsApiTest.java
- src/centralserver/admin-service/src/test/java/org/niis/xroad/centralserver/restapi/service/ClientServiceTest.java
- src/centralserver/admin-service/src/test/java/org/niis/xroad/centralserver/restapi/service/MemberServiceTest.java
- src/centralserver/admin-service/src/test/java/org/niis/xroad/centralserver/restapi/service/SubsystemServiceTest.java
- src/centralserver/admin-ui/src/store/modules/members.ts
- src/centralserver/admin-ui/src/views/Members/Member/AddMemberDialog.vue
- src/common-rest-api/src/main/java/org/niis/xroad/restapi/config/audit/RestApiAuditEvent.java
- src/common-rest-api/src/main/java/org/niis/xroad/restapi/config/audit/RestApiAuditProperty.java
https://nordic-institute.atlassian.net/browse/XRDDEV-2082
> XRDDEV-2082

- src/centralserver/admin-service/src/main/java/org/niis/xroad/centralserver/restapi/openapi/SubsystemsApiController.java
- src/centralserver/admin-service/src/main/java/org/niis/xroad/centralserver/restapi/service/SubsystemService.java
- src/centralserver/admin-service/src/main/java/org/niis/xroad/centralserver/restapi/service/exception/ErrorMessage.java
- src/centralserver/admin-service/src/main/resources/openapi-definition.yaml
- src/centralserver/admin-service/src/test/java/org/niis/xroad/centralserver/restapi/openapi/SubsystemsApiControllerTest.java
- src/centralserver/admin-service/src/test/java/org/niis/xroad/centralserver/restapi/openapi/SubsystemsApiTest.java
- src/centralserver/admin-service/src/test/java/org/niis/xroad/centralserver/restapi/service/SubsystemServiceTest.java
- src/common-rest-api/src/main/java/org/niis/xroad/restapi/config/audit/RestApiAuditEvent.java
XRDDEV-2084 delete subsystem api
> XRDDEV-2084 delete subsystem api

- CONTRIBUTING.md
Updated the CONTRIBUTING.md document to include information about extensions as well as clarifying branching/commit rules for GitHub issues.
> Updated the CONTRIBUTING.md document

- src/centralserver/admin-ui/src/locales/en.json
- src/centralserver/admin-ui/src/views/Members/Member/Details/DeleteMemberDialog.vue
https://nordic-institute.atlassian.net/browse/XRDDEV-2085
> XRDDEV-2085 displaying member name in bold in delete dialog

- src/common-verifier/src/main/java/ee/ria/xroad/common/conf/globalconf/GlobalConfImpl.java
- src/proxy-ui-api/frontend/src/locales/en.json
- src/proxy-ui-api/frontend/src/views/AddClient/ClientDetailsPage.vue
- src/proxy-ui-api/frontend/src/views/AddMember/MemberDetailsPage.vue
- src/proxy-ui-api/frontend/src/views/AddSubsystem/AddSubsystem.vue
- src/proxy-ui-api/src/main/java/org/niis/xroad/securityserver/restapi/scheduling/GlobalConfChecker.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/securityserver/restapi/scheduling/GlobalConfCheckerTest.java
https://nordic-institute.atlassian.net/browse/XRDDEV-2133
> XRDDEV-2133 In case of secondary SS nodes do refresh proxy admin's globalconf (but don't update serverconf)

- src/centralserver/admin-ui/src/locales/en.json
- src/centralserver/admin-ui/src/router/routes.ts
- src/centralserver/admin-ui/src/store/modules/subsystems.ts
- src/centralserver/admin-ui/src/views/Members/Member/Subsystems/AddMemberSubsystemDialog.vue
- src/centralserver/admin-ui/src/views/Members/Member/Subsystems/DeleteMemberSubsystemDialog.vue
- src/centralserver/admin-ui/src/views/Members/Member/Subsystems/MemberSubsystems.vue
- src/centralserver/admin-ui/src/views/Members/Member/Subsystems/UnregisterMemberSubsystemDialog.vue
https://nordic-institute.atlassian.net/browse/XRDDEV-2086
> XRDDEV-2086 Member subsystem details view

- src/centralserver/admin-ui/src/views/Members/Member/Subsystems/AddMemberSubsystemDialog.vue
- src/centralserver/admin-ui/src/views/Members/Member/Subsystems/MemberSubsystems.vue
- src/e2e-tests/src/intTest/java/org/niis/xroad/test/ui/glue/centralserver/CentralServerMemberDetailsStepDefs.java
- src/e2e-tests/src/intTest/java/org/niis/xroad/test/ui/glue/centralserver/CentralServerMemberStepDefs.java
- src/e2e-tests/src/intTest/java/org/niis/xroad/test/ui/glue/centralserver/CentralServerMemberSubsystemsStepDefs.java
- src/e2e-tests/src/intTest/resources/behavior/ui/csMemberDetails.feature
- src/e2e-tests/src/intTest/resources/behavior/ui/csMemberSubsystems.feature
JIRA: https://nordic-institute.atlassian.net/browse/XRDDEV-2088
> XRDDEV-2088 Add member details view subsystems tab E2E test

- src/packages/src/xroad/common/base/usr/share/xroad/scripts/_restore_xroad.sh
https://nordic-institute.atlassian.net/browse/XRDDEV-2114
> XRDDEV-2114 Update xroad restoration scripts to keep xroad.properties file

- src/e2e-tests/src/intTest/java/org/niis/xroad/test/ui/glue/centralserver/CentralServerMemberSubsystemsStepDefs.java
JIRA: https://nordic-institute.atlassian.net/browse/XRDDEV-2088
> XRDDEV-2088 Subsystem E2E fixes

- src/centralserver/admin-service/core/src/main/java/org/niis/xroad/centralserver/restapi/service/CertificationServicesService.java
- src/centralserver/admin-service/infra-api-rest/src/main/java/org/niis/xroad/centralserver/restapi/openapi/CertificationServicesController.java
- src/centralserver/admin-service/infra-api-rest/src/main/resources/openapi-definition.yaml
- src/centralserver/admin-service/infra-api-rest/src/test/java/org/niis/xroad/centralserver/restapi/openapi/CertificationServicesApiTest.java
- src/centralserver/admin-ui/package-lock.json
- src/centralserver/admin-ui/src/store/modules/trust-services.ts
- src/common-rest-api/src/main/java/org/niis/xroad/restapi/config/audit/RestApiAuditEvent.java
- src/shared-ui/package-lock.json
https://nordic-institute.atlassian.net/browse/XRDDEV-2140
> XRDDEV-2140 Add patch certification service settings api endpoint

- src/centralserver/admin-service/core/src/main/java/org/niis/xroad/centralserver/restapi/dto/CertificateAuthority.java
- src/centralserver/admin-service/core/src/main/java/org/niis/xroad/centralserver/restapi/dto/converter/CaInfoConverter.java
- src/centralserver/admin-service/core/src/main/java/org/niis/xroad/centralserver/restapi/entity/ApprovedCa.java
- src/centralserver/admin-service/core/src/main/java/org/niis/xroad/centralserver/restapi/service/CertificationServicesService.java
- src/centralserver/admin-service/core/src/test/java/org/niis/xroad/centralserver/restapi/dto/converter/CaInfoConverterTest.java
- src/centralserver/admin-service/core/src/test/java/org/niis/xroad/centralserver/restapi/service/CertificationServicesServiceTest.java
- src/centralserver/admin-service/infra-api-rest/src/main/java/org/niis/xroad/centralserver/restapi/converter/CertificateAuthorityDtoConverter.java
- src/centralserver/admin-service/infra-api-rest/src/main/java/org/niis/xroad/centralserver/restapi/openapi/CertificationServicesController.java
- src/centralserver/admin-service/infra-api-rest/src/main/resources/openapi-definition.yaml
- src/centralserver/admin-service/infra-api-rest/src/test/java/org/niis/xroad/centralserver/restapi/openapi/CertificationServicesApiTest.java
- src/common-rest-api/src/main/java/org/niis/xroad/restapi/config/audit/RestApiAuditEvent.java
- src/common-rest-api/src/main/java/org/niis/xroad/restapi/config/audit/RestApiAuditProperty.java
XXRDDEV-2148 API to add a intermediate CA to a certification service
https://nordic-institute.atlassian.net/browse/XRDDEV-2148
> XXRDDEV-2148 API to add a intermediate CA to a certification service

- src/centralserver/admin-service/core/src/main/java/org/niis/xroad/centralserver/restapi/service/OcspRespondersService.java
- src/centralserver/admin-service/core/src/test/java/org/niis/xroad/centralserver/restapi/service/OcspRespondersServiceTest.java
- src/centralserver/admin-service/infra-api-rest/src/main/java/org/niis/xroad/centralserver/restapi/openapi/OcspRespondersController.java
- src/centralserver/admin-service/infra-api-rest/src/main/resources/openapi-definition.yaml
- src/centralserver/admin-ui/package-lock.json
- src/proxy-ui-api/frontend/package-lock.json
https://nordic-institute.atlassian.net/browse/XRDDEV-2144
> XRDDEV-2144 API to get the certificate of an OCSP responder of a certification service

- src/centralserver/admin-service/core/src/main/java/org/niis/xroad/centralserver/restapi/dto/converter/CaInfoConverter.java
- src/centralserver/admin-service/core/src/main/java/org/niis/xroad/centralserver/restapi/service/CertificationServicesService.java
- src/centralserver/admin-service/core/src/test/java/org/niis/xroad/centralserver/restapi/service/CertificationServicesServiceTest.java
- src/centralserver/admin-service/infra-api-rest/src/main/java/org/niis/xroad/centralserver/restapi/converter/CertificateAuthorityDtoConverter.java
- src/centralserver/admin-service/infra-api-rest/src/main/java/org/niis/xroad/centralserver/restapi/openapi/CertificationServicesController.java
- src/centralserver/admin-service/infra-api-rest/src/main/resources/openapi-definition.yaml
- src/centralserver/admin-service/infra-api-rest/src/test/java/org/niis/xroad/centralserver/restapi/openapi/CertificationServicesApiTest.java
https://nordic-institute.atlassian.net/browse/XRDDEV-2147
> XRDDEV-2147 API to view a list of intermediate CA-s connected to a certification service

- src/centralserver/admin-service/core/src/main/java/org/niis/xroad/centralserver/restapi/service/CertificationServicesService.java
- src/centralserver/admin-service/infra-api-rest/src/main/java/org/niis/xroad/centralserver/restapi/openapi/CertificationServicesController.java
- src/centralserver/admin-ui/src/global.ts
- src/centralserver/admin-ui/src/locales/en.json
- src/centralserver/admin-ui/src/router/routes.ts
- src/centralserver/admin-ui/src/store/modules/trust-services.ts
- src/centralserver/admin-ui/src/views/TrustServices/CertificationService/Details/CertificationServiceDetails.vue
- src/centralserver/admin-ui/src/views/TrustServices/CertificationService/Settings/CertificationServiceSettings.vue
- src/centralserver/admin-ui/src/views/TrustServices/CertificationService/Settings/EditCertProfileDialog.vue
- src/centralserver/admin-ui/src/views/TrustServices/CertificationService/Settings/EditTlsAuthDialog.vue
https://nordic-institute.atlassian.net/browse/XRDDEV-2163
> XRDDEV-2163

- src/centralserver/admin-service/application/src/test/java/org/niis/xroad/cs/admin/application/openapi/OcspRespondersApiTest.java
- src/centralserver/admin-service/core-api/src/main/java/org/niis/xroad/centralserver/restapi/service/exception/ErrorMessage.java
- src/centralserver/admin-service/core-api/src/main/java/org/niis/xroad/cs/admin/api/service/OcspRespondersService.java
- src/centralserver/admin-service/core/src/main/java/org/niis/xroad/centralserver/restapi/service/OcspRespondersServiceImpl.java
- src/centralserver/admin-service/core/src/test/java/org/niis/xroad/centralserver/restapi/service/OcspRespondersServiceImplTest.java
- src/centralserver/admin-service/infra-api-rest/src/main/java/org/niis/xroad/centralserver/restapi/openapi/OcspRespondersController.java
- src/centralserver/admin-service/infra-api-rest/src/main/resources/openapi-definition.yaml
- src/common-rest-api/src/main/java/org/niis/xroad/restapi/config/audit/RestApiAuditEvent.java
https://nordic-institute.atlassian.net/browse/XRDDEV-2146
> XRDDEV-2146 API to delete an OCSP responder

- src/centralserver/admin-service/application/src/test/java/org/niis/xroad/cs/admin/application/openapi/IntermediateCasApiTest.java
- src/centralserver/admin-service/core-api/src/main/java/org/niis/xroad/cs/admin/api/service/IntermediateCasService.java
- src/centralserver/admin-service/core/src/main/java/org/niis/xroad/centralserver/restapi/service/IntermediateCasServiceImpl.java
- src/centralserver/admin-service/core/src/test/java/org/niis/xroad/centralserver/restapi/service/IntermediateCasServiceImplTest.java
- src/centralserver/admin-service/infra-api-rest/src/main/java/org/niis/xroad/centralserver/restapi/openapi/IntermediateCasController.java
- src/centralserver/admin-service/infra-api-rest/src/main/resources/openapi-definition.yaml
- src/common-rest-api/src/main/java/org/niis/xroad/restapi/config/audit/RestApiAuditEvent.java
https://nordic-institute.atlassian.net/browse/XRDDEV-2153
> XRDDEV-2153 API to delete an intermediate CA

- src/centralserver/admin-service/core/src/main/java/org/niis/xroad/centralserver/restapi/dto/converter/CaInfoConverter.java
- src/centralserver/admin-service/core/src/main/java/org/niis/xroad/centralserver/restapi/dto/converter/CertificateConverter.java
- src/centralserver/admin-service/core/src/main/java/org/niis/xroad/centralserver/restapi/service/CertificationServicesServiceImpl.java
- src/centralserver/admin-service/core/src/main/java/org/niis/xroad/centralserver/restapi/service/OcspRespondersServiceImpl.java
- src/centralserver/admin-service/core/src/test/java/org/niis/xroad/centralserver/restapi/dto/converter/CaInfoConverterTest.java
- src/centralserver/admin-service/core/src/test/java/org/niis/xroad/centralserver/restapi/service/CertificationServicesServiceImplTest.java
- src/centralserver/admin-service/core/src/test/java/org/niis/xroad/centralserver/restapi/service/OcspRespondersServiceImplTest.java
https://nordic-institute.atlassian.net/browse/XRDDEV-2144
OCSPResponderService should return certificateDetails of ocspInfo instead of caInfo
> XRDDEV-2144 OCSPResponderService should return ocspInfo certificateDetails

- src/packages/src/xroad/common/addon/proxy/messagelog-archiver.conf
https://nordic-institute.atlassian.net/browse/XRDDEV-2167
> XRDDEV-2167 Increased messagelg archiver max memory to 200m

- src/centralserver/admin-service/application/src/intTest/java/org/niis/xroad/cs/test/glue/BaseStepDefs.java
- src/centralserver/admin-service/application/src/intTest/java/org/niis/xroad/cs/test/glue/CertificationServicesApiStepDefs.java
- src/centralserver/admin-service/application/src/intTest/java/org/niis/xroad/cs/test/glue/IntermediateCasApiStepDefs.java
- src/centralserver/admin-service/application/src/intTest/resources/behavior/api/intermediateCasApi.feature
- src/centralserver/admin-service/core-api/src/main/java/org/niis/xroad/cs/admin/api/service/IntermediateCasService.java
- src/centralserver/admin-service/core/src/main/java/org/niis/xroad/centralserver/restapi/service/IntermediateCasServiceImpl.java
- src/centralserver/admin-service/core/src/test/java/org/niis/xroad/centralserver/restapi/service/IntermediateCasServiceImplTest.java
- src/centralserver/admin-service/infra-api-rest/src/main/java/org/niis/xroad/centralserver/restapi/openapi/IntermediateCasController.java
- src/centralserver/admin-service/infra-api-rest/src/main/resources/openapi-definition.yaml
https://nordic-institute.atlassian.net/browse/XRDDEV-2150
> XRDDEV-2150 API to view the OCSP responders of an intermediate CA

- src/centralserver/admin-service/application/src/intTest/java/org/niis/xroad/cs/test/api/FeignOcspRespondersApi.java
- src/centralserver/admin-service/application/src/intTest/java/org/niis/xroad/cs/test/constants/Constants.java
- src/centralserver/admin-service/application/src/intTest/java/org/niis/xroad/cs/test/glue/IntermediateCasApiStepDefs.java
- src/centralserver/admin-service/application/src/intTest/java/org/niis/xroad/cs/test/glue/OcspRespondersApiStepDefs.java
- src/centralserver/admin-service/application/src/intTest/resources/behavior/api/intermediateCasApi.feature
https://nordic-institute.atlassian.net/browse/XRDDEV-2152
> XRDDEV-2152 Integration tests for modifying OCSP Responder

- src/centralserver/admin-service/ui/src/views/TrustServices/CertificationService/CertificationService.vue
- src/e2e-tests/build.gradle
- src/e2e-tests/src/intTest/java/org/niis/xroad/test/ui/glue/centralserver/CentralServerCertificationServicesStepDefs.java
- src/e2e-tests/src/intTest/java/org/niis/xroad/test/ui/glue/constants/Constants.java
- src/e2e-tests/src/intTest/java/org/niis/xroad/test/ui/utils/CertificateUtils.java
- src/e2e-tests/src/intTest/resources/behavior/ui/csCertificationService.feature
https://nordic-institute.atlassian.net/browse/XRDDEV-2171
>  XRDDEV-2171 E2E tests for the certification service

- src/centralserver/admin-service/ui/src/assets/tables.scss
- src/centralserver/admin-service/ui/src/components/certificate/CertificateDetails.vue
- src/centralserver/admin-service/ui/src/components/intermediateCas/AddIntermediateCaDialog.vue
- src/centralserver/admin-service/ui/src/components/intermediateCas/IntermediateCasList.vue
- src/centralserver/admin-service/ui/src/global.ts
- src/centralserver/admin-service/ui/src/locales/en.json
- src/centralserver/admin-service/ui/src/router/routes.ts
- src/centralserver/admin-service/ui/src/store/modules/trust-services.ts
- src/centralserver/admin-service/ui/src/views/TrustServices/CertificationService/CertificationService.vue
- src/centralserver/admin-service/ui/src/views/TrustServices/CertificationService/CertificationServiceCertificate.vue
- src/centralserver/admin-service/ui/src/views/TrustServices/CertificationService/CertificationServiceIntermediateCas.vue
- src/centralserver/admin-service/ui/src/views/TrustServices/CertificationService/CertificationServiceOcspResponders.vue
- src/centralserver/admin-service/ui/src/views/TrustServices/CertificationService/IntermediateCACertificate.vue
https://nordic-institute.atlassian.net/browse/XRDDEV-2168
> XRDDEV-2168 CentralServer UI intermediateCa page

- src/e2e-tests/src/intTest/java/org/niis/xroad/test/ui/glue/SecurityServerDiagnosticsStepDefs.java
- src/e2e-tests/src/intTest/resources/behavior/ui/ssBackupEncryption.feature
- src/proxy-ui-api/frontend/src/views/Diagnostics/Diagnostics.vue
https://nordic-institute.atlassian.net/browse/XRDDEV-2019
> XRDDEV-2019 backup encryption configuration e2e tests

- src/centralserver/admin-service/ui/src/components/ocspResponders/AddOcspResponderDialog.vue
- src/centralserver/admin-service/ui/src/components/ocspResponders/OcspRespondersList.vue
- src/centralserver/admin-service/ui/src/store/modules/trust-services.ts
- src/centralserver/admin-service/ui/src/views/TrustServices/CertificationService/CertificationServiceOcspResponders.vue
- src/centralserver/admin-service/ui/src/views/TrustServices/CertificationService/IntermediateCaOcspResponders.vue
https://nordic-institute.atlassian.net/browse/XRDDEV-2170
> XRDDEV-2170 Remove unnesacary intermediateCa indication

- src/centralserver/admin-service/application/src/intTest/java/org/niis/xroad/cs/test/glue/BaseStepDefs.java
- src/centralserver/admin-service/application/src/intTest/java/org/niis/xroad/cs/test/glue/CertificationServicesApiStepDefs.java
- src/centralserver/admin-service/application/src/intTest/java/org/niis/xroad/cs/test/glue/IntermediateCasApiStepDefs.java
- src/centralserver/admin-service/application/src/intTest/java/org/niis/xroad/cs/test/glue/OcspRespondersApiStepDefs.java
- src/centralserver/admin-service/application/src/intTest/java/org/niis/xroad/cs/test/glue/SecurityServerApiStepDefs.java
- src/centralserver/admin-service/application/src/intTest/java/org/niis/xroad/cs/test/glue/SystemApiStepDefs.java
- src/centralserver/admin-service/application/src/intTest/java/org/niis/xroad/cs/test/glue/TimestampingServicesApiStepDefs.java
- src/centralserver/admin-service/application/src/intTest/java/org/niis/xroad/cs/test/hook/DatabaseResetHook.java
- src/centralserver/admin-service/application/src/intTest/resources/behavior/api/timestampingServicesApi.feature
- src/centralserver/admin-service/core/src/main/java/org/niis/xroad/centralserver/restapi/service/OcspRespondersServiceImpl.java
- src/centralserver/admin-service/core/src/main/java/org/niis/xroad/centralserver/restapi/service/TimestampingServicesServiceImpl.java
- src/centralserver/admin-service/core/src/main/java/org/niis/xroad/centralserver/restapi/validation/UrlValidator.java
- src/centralserver/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/entity/mapper/ApprovedTsaMapper.java
- src/centralserver/admin-service/core/src/test/java/org/niis/xroad/centralserver/restapi/service/OcspRespondersServiceImplTest.java
- src/centralserver/admin-service/core/src/test/java/org/niis/xroad/centralserver/restapi/service/TimestampingServicesServiceImplTest.java
- src/centralserver/admin-service/core/src/test/java/org/niis/xroad/centralserver/restapi/validation/UrlValidatorTest.java
- src/centralserver/admin-service/core/src/test/java/org/niis/xroad/cs/admin/core/entity/mapper/ApprovedTsaMapperTest.java
- src/centralserver/admin-service/infra-api-rest/src/main/java/org/niis/xroad/centralserver/restapi/openapi/TimestampingServicesApiController.java
- src/centralserver/admin-service/infra-api-rest/src/main/resources/openapi-definition.yaml
- src/common-rest-api/src/main/java/org/niis/xroad/restapi/config/audit/RestApiAuditProperty.java
- src/gradle.properties
https://nordic-institute.atlassian.net/browse/XRDDEV-2175
> XRDDEV-2175 API to add a timestamping authority

- doc/Manuals/ig-cs_x-road_6_central_server_installation_guide.md
- doc/Manuals/ig-ss_x-road_v6_security_server_installation_guide.md
- doc/Manuals/ug-cs_x-road_6_central_server_user_guide.md
- doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md
https://nordic-institute.atlassian.net/browse/XRDDEV-2119
> XRDDEV-2119 Update CS documentation regarding migration to remote database

- src/centralserver/admin-service/ui/src/components/intermediateCas/IntermediateCasList.vue
- src/centralserver/admin-service/ui/src/components/ocspResponders/AddOcspResponderDialog.vue
- src/centralserver/admin-service/ui/src/components/ocspResponders/EditOcspResponderDialog.vue
- src/centralserver/admin-service/ui/src/components/ocspResponders/OcspRespondersList.vue
- src/e2e-tests/src/intTest/java/org/niis/xroad/test/ui/glue/centralserver/CentralServerCertificationServicesStepDefs.java
- src/e2e-tests/src/intTest/java/org/niis/xroad/test/ui/glue/centralserver/CentralServerIntermediateCasStepDefs.java
- src/e2e-tests/src/intTest/java/org/niis/xroad/test/ui/glue/centralserver/CentralServerMemberSubsystemsStepDefs.java
- src/e2e-tests/src/intTest/java/org/niis/xroad/test/ui/glue/centralserver/CentralServerOcspRespondersStepDefs.java
- src/e2e-tests/src/intTest/java/org/niis/xroad/test/ui/glue/constants/Constants.java
- src/e2e-tests/src/intTest/resources/behavior/ui/csIntermediateCaOcspResponders.feature
- src/e2e-tests/src/intTest/resources/behavior/ui/csMemberSubsystems.feature
- src/e2e-tests/src/intTest/resources/behavior/ui/csOcspResponders.feature
JIRA: https://nordic-institute.atlassian.net/browse/XRDDEV-2173
> XRDDEV-2173 OCSP responders E2E tests

- src/centralserver/admin-service/application/src/intTest/java/org/niis/xroad/cs/test/glue/BaseStepDefs.java
- src/centralserver/admin-service/application/src/intTest/java/org/niis/xroad/cs/test/glue/TimestampingServicesApiStepDefs.java
- src/centralserver/admin-service/application/src/intTest/resources/behavior/api/timestampingServicesApi.feature
- src/centralserver/admin-service/core-api/src/main/java/org/niis/xroad/centralserver/restapi/service/exception/ErrorMessage.java
- src/centralserver/admin-service/core-api/src/main/java/org/niis/xroad/cs/admin/api/service/TimestampingServicesService.java
- src/centralserver/admin-service/core/src/main/java/org/niis/xroad/centralserver/restapi/service/TimestampingServicesServiceImpl.java
- src/centralserver/admin-service/core/src/test/java/org/niis/xroad/centralserver/restapi/service/TimestampingServicesServiceImplTest.java
- src/centralserver/admin-service/infra-api-rest/src/main/java/org/niis/xroad/centralserver/restapi/openapi/TimestampingServicesApiController.java
- src/centralserver/admin-service/infra-api-rest/src/main/resources/openapi-definition.yaml
https://nordic-institute.atlassian.net/browse/XRDDEV-2178
> XRDDEV-2178 API to delete a timestamping authority

- src/centralserver/admin-service/ui/src/views/AppBase.vue
- src/centralserver/admin-service/ui/src/views/Settings/SystemSettings/SystemSettings.vue
Fetch/Update system status on page reload or when opening system settings
> XRDDEV-2184 Fetch/Update system status on page reload

- src/centralserver/admin-service/application/src/intTest/java/org/niis/xroad/cs/test/glue/TimestampingServicesApiStepDefs.java
- src/centralserver/admin-service/application/src/intTest/resources/behavior/api/timestampingServicesApi.feature
- src/centralserver/admin-service/core-api/src/main/java/org/niis/xroad/cs/admin/api/service/TimestampingServicesService.java
- src/centralserver/admin-service/core/src/main/java/org/niis/xroad/centralserver/restapi/service/TimestampingServicesServiceImpl.java
- src/centralserver/admin-service/core/src/test/java/org/niis/xroad/centralserver/restapi/service/TimestampingServicesServiceImplTest.java
- src/centralserver/admin-service/infra-api-rest/src/main/java/org/niis/xroad/centralserver/restapi/openapi/TimestampingServicesApiController.java
- src/centralserver/admin-service/infra-api-rest/src/main/resources/openapi-definition.yaml
https://nordic-institute.atlassian.net/browse/XRDDEV-2174
> XRDDEV-2177 CentralServer API get timestamping authority

- src/centralserver/admin-service/ui/src/components/timestampingServices/TimestampingServiceCertificate.vue
- src/centralserver/admin-service/ui/src/components/timestampingServices/TimestampingServicesList.vue
- src/centralserver/admin-service/ui/src/global.ts
- src/centralserver/admin-service/ui/src/locales/en.json
- src/centralserver/admin-service/ui/src/router/routes.ts
- src/centralserver/admin-service/ui/src/store/modules/trust-services.ts
- src/centralserver/admin-service/ui/src/views/TrustServices/TrustServiceList.vue
https://nordic-institute.atlassian.net/browse/XRDDEV-2179
> XRDDEV-2179 UI to view the timestamping services

- src/centralserver/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/entity/mapper/ServerClientMapper.java
- src/centralserver/admin-service/core/src/test/java/org/niis/xroad/cs/admin/core/entity/mapper/SecurityServerClientMapperTest.java
https://nordic-institute.atlassian.net/browse/XRDDEV-2190
> XRDDEV-2190 ServerClient mapping in subsystems mapper

- src/centralserver/admin-service/ui/src/components/timestampingServices/AddTimestampingServiceDialog.vue
- src/centralserver/admin-service/ui/src/components/timestampingServices/EditTimestampingServiceDialog.vue
- src/centralserver/admin-service/ui/src/components/timestampingServices/TimestampingServicesList.vue
- src/centralserver/admin-service/ui/src/components/ui/Snackbar.vue
XRDDEV-2203 Only translate message when adding to notifications list/stack and then render them as is
> XRDDEV-2203 Only translate message when adding to notifications list

- src/centralserver/admin-service/ui-system-test/src/intTest/java/org/niis/xroad/cs/test/ui/glue/TrustServicesIntermediateCasStepDefs.java
- src/centralserver/admin-service/ui-system-test/src/intTest/java/org/niis/xroad/cs/test/ui/page/IntermediateCasPageObj.java
- src/centralserver/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0530-cs-intermediate-ca.feature
- src/centralserver/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0540-cs-intermediate-ca-details.feature
- src/centralserver/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0550-cs-intermediate-ca-ocsp-responders.feature
- src/centralserver/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0560-cs-ocsp-responders.feature
- src/centralserver/admin-service/ui/src/components/intermediateCas/AddIntermediateCaDialog.vue
- src/centralserver/admin-service/ui/src/components/intermediateCas/IntermediateCasList.vue
https://nordic-institute.atlassian.net/browse/XRDDEV-2172
> XRDDEV-2172 Intermediate CA and their details e2e tests

- src/centralserver/admin-service/core/src/test/java/org/niis/xroad/centralserver/restapi/service/ConfigurationServiceImplTest.java
- src/centralserver/admin-service/int-test/src/intTest/java/org/niis/xroad/cs/test/glue/ConfigurationInfoApiStepDefs.java
- src/centralserver/admin-service/int-test/src/intTest/resources/behavior/api/configurationInfoApis.feature
- src/centralserver/admin-service/int-test/src/intTest/resources/test-data/baseline-intTest.xml
JIRA: https://nordic-institute.atlassian.net/browse/XRDDEV-2200
> XRDDEV-2200 Details of External configuration

- src/centralserver/admin-service/ui-system-test/src/intTest/java/org/niis/xroad/cs/test/ui/glue/CommonUiStepDefs.java
- src/centralserver/admin-service/ui-system-test/src/intTest/java/org/niis/xroad/cs/test/ui/glue/TrustServicesTimestampingServicesStepDefs.java
- src/centralserver/admin-service/ui-system-test/src/intTest/java/org/niis/xroad/cs/test/ui/page/TimestampingServicesPageObj.java
- src/centralserver/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0570-cs-trust-services-timestamping-services.feature
- src/centralserver/admin-service/ui/src/components/timestampingServices/EditTimestampingServiceDialog.vue
- src/centralserver/admin-service/ui/src/components/timestampingServices/TimestampingServicesList.vue
- src/centralserver/admin-service/ui/src/store/modules/trust-services.ts
JIRA: https://nordic-institute.atlassian.net/browse/XRDDEV-2181
> XRDDEV-2181 Timestamping service E2E tests

- src/centralserver/admin-service/ui-system-test/src/intTest/java/org/niis/xroad/cs/test/ui/glue/CommonUiStepDefs.java
- src/centralserver/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0570-cs-trust-services-timestamping-services.feature
JIRA: https://nordic-institute.atlassian.net/browse/XRDDEV-2181
> XRDDEV-2181 Enabling chrome throttling for all loading check tests

- Jenkinsfile
https://nordic-institute.atlassian.net/browse/XRDDEV-2204
[XRDDEV-2204]: https://nordic-institute.atlassian.net/browse/XRDDEV-2204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> XRDDEV-2204 Building only if Jenkinsfile or any file in src/ folder changes

- doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md
https://nordic-institute.atlassian.net/browse/XRDDEV-2096
> XRDDEV-2096 Improve documentation regarding Security Server <-> Information System communication

- src/centralserver/admin-service/application/src/test/java/org/niis/xroad/cs/admin/application/openapi/InitializationApiControllerTest.java
- src/centralserver/admin-service/application/src/test/java/org/niis/xroad/cs/admin/application/openapi/SystemApiControllerTest.java
- src/centralserver/admin-service/core-api/src/main/java/org/niis/xroad/cs/admin/api/service/SystemParameterService.java
- src/centralserver/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/ConfigurationServiceImpl.java
- src/centralserver/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/ConfigurationSigningKeysServiceImpl.java
- src/centralserver/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/InitializationServiceImpl.java
- src/centralserver/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/SystemParameterServiceImpl.java
- src/centralserver/admin-service/core/src/test/java/org/niis/xroad/cs/admin/core/service/ConfigurationServiceImplTest.java
- src/centralserver/admin-service/core/src/test/java/org/niis/xroad/cs/admin/core/service/ConfigurationSigningKeysServiceImplTest.java
- src/centralserver/admin-service/core/src/test/java/org/niis/xroad/cs/admin/core/service/SystemParameterServiceImplTest.java
- src/centralserver/admin-service/globalconf-generator/src/main/java/org/niis/xroad/cs/admin/globalconf/generator/GlobalConfGenerationServiceImpl.java
Hides generic getParameterValue() method from public
> SystemParameterService refacto

- src/packages/src/xroad/ubuntu/generic/control
- src/proxy-ui-api/frontend/package-lock.json
- src/proxy-ui-api/frontend/package.json
https://nordic-institute.atlassian.net/browse/XRDDEV-2230
> XRDDEV-2230 adding 'gpg' and 'gpg-agent' dependencies to xroad-base package

- src/central-server/admin-service/core-api/src/main/java/org/niis/xroad/cs/admin/api/dto/File.java
- src/central-server/admin-service/core-api/src/main/java/org/niis/xroad/cs/admin/api/exception/ErrorMessage.java
- src/central-server/admin-service/core-api/src/main/java/org/niis/xroad/cs/admin/api/service/ConfigurationService.java
- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/entity/mapper/DistributedFileMapper.java
- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/ConfigurationServiceImpl.java
- src/central-server/admin-service/core/src/test/java/org/niis/xroad/cs/admin/core/entity/mapper/DistributedFileMapperTest.java
- src/central-server/admin-service/core/src/test/java/org/niis/xroad/cs/admin/core/service/ConfigurationServiceImplTest.java
- src/central-server/admin-service/infra-api-rest/src/main/java/org/niis/xroad/cs/admin/rest/api/openapi/ConfigurationPartsController.java
- src/central-server/admin-service/int-test/src/intTest/java/org/niis/xroad/cs/test/glue/ConfigurationInfoApiStepDefs.java
- src/central-server/admin-service/int-test/src/intTest/resources/behavior/api/configurationInfoApis.feature
- src/central-server/admin-service/int-test/src/intTest/resources/test-data/baseline-intTest.xml
https://nordic-institute.atlassian.net/browse/XRDDEV-2226
> XRDDEV-2226 API to download configuration parts

- doc/UseCases/uc-mess_x-road_member_communication_use_case_model.md
- src/center-service/src/main/java/ee/ria/xroad/common/request/ManagementRequestHandler.java
- src/common-test/src/main/java/ee/ria/xroad/common/conf/globalconf/EmptyGlobalConf.java
- src/common-verifier/src/main/java/ee/ria/xroad/common/cert/CertChainVerifier.java
- src/common-verifier/src/main/java/ee/ria/xroad/common/conf/globalconf/GlobalConf.java
- src/common-verifier/src/main/java/ee/ria/xroad/common/conf/globalconf/GlobalConfImpl.java
- src/common-verifier/src/main/java/ee/ria/xroad/common/conf/globalconf/GlobalConfProvider.java
- src/common-verifier/src/main/java/ee/ria/xroad/common/ocsp/OcspCache.java
- src/common-verifier/src/test/java/ee/ria/xroad/common/conf/globalconf/GlobalConfTest.java
- src/common-verifier/src/test/java/ee/ria/xroad/common/ocsp/OcspVerifierTest.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/conf/CachingKeyConfImpl.java
- src/proxy/src/test/java/ee/ria/xroad/proxy/testsuite/TestSuiteKeyConf.java
- src/proxy/src/test/java/ee/ria/xroad/proxy/testutil/TestKeyConf.java
- src/signer/src/main/java/ee/ria/xroad/signer/certmanager/OcspClientWorker.java
- src/signer/src/main/java/ee/ria/xroad/signer/protocol/handler/GetAuthKeyRequestHandler.java
- src/signer/src/main/java/ee/ria/xroad/signer/protocol/handler/GetMemberSigningInfoRequestHandler.java
- src/signer/src/test/java/ee/ria/xroad/signer/certmanager/OcspClientTest.java
https://nordic-institute.atlassian.net/browse/XRDDEV-2210
> XRDDEV-2210 using ocspFreshnessSeconds value of the X-Road instance

- .githooks/commit-msg
- CONTRIBUTING.md
- src/build.gradle
This is initial version of git hook which will validate against https://www.conventionalcommits.org/en/v1.0.0/#summary
> feat: Git commit message validation

- src/central-server/admin-service/infra-api-rest/build.gradle
- src/central-server/openapi-model/build.gradle
- src/central-server/registration-service/build.gradle
- src/central-server/registration-service/src/test/resources/logback-test.xml
- src/common-rest-api/build.gradle
- src/gradle.properties
- src/security-server/admin-service/application/build.gradle
- src/security-server/openapi-model/build.gradle
> fix: jetty is not used for registration service api

- src/central-server/admin-service/core-api/src/main/java/org/niis/xroad/cs/admin/api/exception/ErrorMessage.java
- src/central-server/admin-service/core/src/test/java/org/niis/xroad/cs/admin/core/service/SecurityServerServiceImplTest.java
- src/central-server/admin-service/infra-api-rest/src/main/java/org/niis/xroad/cs/admin/rest/api/openapi/SecurityServersApiController.java
- src/central-server/admin-service/int-test/src/intTest/java/org/niis/xroad/cs/test/api/FeignSecurityServersApi.java
- src/central-server/admin-service/int-test/src/intTest/java/org/niis/xroad/cs/test/glue/ManagementRequestsApiStepDefs.java
- src/central-server/admin-service/int-test/src/intTest/java/org/niis/xroad/cs/test/glue/SecurityServerApiStepDefs.java
- src/central-server/admin-service/int-test/src/intTest/resources/behavior/api/securityServerApi.feature
https://nordic-institute.atlassian.net/browse/XRDDEV-2256
> XRDDEV-2256 API for getting the details of a Security Server

- src/central-server/admin-service/application/src/test/java/org/niis/xroad/cs/admin/application/openapi/InitializationApiControllerTest.java
- src/central-server/admin-service/core-api/src/main/java/org/niis/xroad/cs/admin/api/domain/ManagementServicesConfiguration.java
- src/central-server/admin-service/core-api/src/main/java/org/niis/xroad/cs/admin/api/domain/SubsystemId.java
- src/central-server/admin-service/core-api/src/main/java/org/niis/xroad/cs/admin/api/service/ManagementServicesService.java
- src/central-server/admin-service/core-api/src/main/java/org/niis/xroad/cs/admin/api/service/SystemParameterService.java
- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/ManagementServicesServiceImpl.java
- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/SystemParameterServiceImpl.java
- src/central-server/admin-service/core/src/test/java/org/niis/xroad/cs/admin/core/service/ManagementServicesServiceImplTest.java
- src/central-server/admin-service/infra-api-rest/src/main/java/org/niis/xroad/cs/admin/rest/api/converter/ManagementServicesConfigurationMapper.java
- src/central-server/admin-service/infra-api-rest/src/main/java/org/niis/xroad/cs/admin/rest/api/exception/ConflictException.java
- src/central-server/admin-service/infra-api-rest/src/main/java/org/niis/xroad/cs/admin/rest/api/exception/InternalServerErrorException.java
- src/central-server/admin-service/infra-api-rest/src/main/java/org/niis/xroad/cs/admin/rest/api/openapi/InitializationApiController.java
- src/central-server/admin-service/infra-api-rest/src/main/java/org/niis/xroad/cs/admin/rest/api/openapi/ManagementServicesController.java
- src/central-server/admin-service/infra-jpa/src/main/java/org/niis/xroad/cs/admin/jpa/repository/JpaSubsystemRepository.java
- src/common-domain/src/main/java/org/niis/xroad/restapi/converter/ClientIdConverter.java
- src/common-domain/src/main/java/org/niis/xroad/restapi/converter/SecurityServerIdConverter.java
- src/common-domain/src/main/java/org/niis/xroad/restapi/util/FormatUtils.java
- src/common-util/build.gradle
- src/common-util/src/main/java/ee/ria/xroad/common/identifier/SecurityServerId.java
- src/common-util/src/main/java/ee/ria/xroad/common/identifier/XRoadId.java
- src/common-util/src/test/java/ee/ria/xroad/common/identifier/XRoadIdTest.java
- src/gradle.properties
- src/security-server/admin-service/application/src/main/java/org/niis/xroad/securityserver/restapi/converter/GlobalGroupConverter.java
- src/security-server/admin-service/application/src/main/java/org/niis/xroad/securityserver/restapi/converter/LocalGroupConverter.java
- src/security-server/admin-service/application/src/main/java/org/niis/xroad/securityserver/restapi/converter/ServiceConverter.java
- src/security-server/admin-service/application/src/main/java/org/niis/xroad/securityserver/restapi/service/TokenCertificateService.java
- src/security-server/admin-service/application/src/test/java/org/niis/xroad/securityserver/restapi/openapi/TokenCertificatesApiControllerIntegrationTest.java
> feat: security server management configuration api (GET)

- src/central-server/admin-service/core-api/src/main/java/org/niis/xroad/cs/admin/api/service/SecurityServerService.java
- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/SecurityServerServiceImpl.java
- src/central-server/admin-service/core/src/test/java/org/niis/xroad/cs/admin/core/service/SecurityServerServiceImplTest.java
- src/central-server/admin-service/infra-api-rest/src/main/java/org/niis/xroad/cs/admin/rest/api/openapi/SecurityServersApiController.java
- src/central-server/admin-service/int-test/src/intTest/java/org/niis/xroad/cs/test/glue/ManagementRequestsApiStepDefs.java
- src/central-server/admin-service/int-test/src/intTest/java/org/niis/xroad/cs/test/glue/SecurityServerApiStepDefs.java
- src/central-server/admin-service/int-test/src/intTest/resources/behavior/api/securityServerApi.feature
- src/central-server/openapi-model/src/main/resources/openapi-definition.yaml
https://nordic-institute.atlassian.net/browse/XRDDEV-2258
> XRDDEV-2258 API for getting a list of clients for a Security Server

- src/central-server/admin-service/core-api/src/main/java/org/niis/xroad/cs/admin/api/dto/SecurityServerAuthenticationCertificateDetails.java
- src/central-server/admin-service/core-api/src/main/java/org/niis/xroad/cs/admin/api/service/SecurityServerService.java
- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/converter/CertificateConverter.java
- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/entity/AuthCertEntity.java
- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/SecurityServerServiceImpl.java
- src/central-server/admin-service/core/src/test/java/org/niis/xroad/cs/admin/core/service/SecurityServerServiceImplTest.java
- src/central-server/admin-service/infra-api-rest/src/main/java/org/niis/xroad/cs/admin/rest/api/openapi/SecurityServersApiController.java
- src/central-server/admin-service/int-test/src/intTest/java/org/niis/xroad/cs/test/glue/SecurityServerApiStepDefs.java
- src/central-server/admin-service/int-test/src/intTest/resources/behavior/api/securityServerApi.feature
- src/central-server/openapi-model/src/main/resources/openapi-definition.yaml
https://nordic-institute.atlassian.net/browse/XRDDEV-2259
> XRDDEV-2259 Added API for getting security server authentication certificates

- src/central-server/admin-service/ui/src/components/managementRequests/ManagementRequestActionsCell.vue
- src/central-server/admin-service/ui/src/components/managementRequests/ManagementRequestConfirmDialog.vue
- src/central-server/admin-service/ui/src/components/managementRequests/ManagementRequestDeclineDialog.vue
- src/central-server/admin-service/ui/src/components/managementRequests/ManagementRequestsList.vue
- src/central-server/admin-service/ui/src/locales/en.json
- src/central-server/admin-service/ui/src/store/modules/managementRequestStore.ts
> Management request approve/decline buttons 

- src/central-server/admin-service/ui/src/components/systemSettings/ManagementServices.vue
- src/central-server/admin-service/ui/src/components/systemSettings/SelectSubsystemDialog.vue
- src/central-server/admin-service/ui/src/locales/en.json
> chore: Changing UI component name to SelectSubsystemDialoge

- src/central-server/admin-service/ui/src/components/intermediateCas/IntermediateCasList.vue
- src/central-server/admin-service/ui/src/components/layout/PageNavigation.vue
- src/central-server/admin-service/ui/src/router/routes.ts
- src/central-server/admin-service/ui/src/store/modules/clients.ts
- src/central-server/admin-service/ui/src/views/Members/Member/Member.vue
- src/central-server/admin-service/ui/src/views/SecurityServers/SecurityServer/SecurityServer.vue
- src/central-server/admin-service/ui/src/views/SecurityServers/SecurityServer/SecurityServerClients.vue
- src/central-server/admin-service/ui/src/views/SecurityServers/SecurityServersList.vue
- src/central-server/admin-service/ui/src/views/TrustServices/CertificationService/CertificationService.vue
- src/central-server/admin-service/ui/src/views/TrustServices/CertificationService/IntermediateCa.vue
- src/central-server/admin-service/ui/src/views/TrustServices/TrustServiceList.vue
https://nordic-institute.atlassian.net/browse/XRDDEV-2266
> feat: Complement UI for viewing security server clients

- src/central-server/admin-service/ui/src/locales/en.json
- src/central-server/admin-service/ui/src/router/routes.ts
- src/central-server/admin-service/ui/src/store/modules/security-servers.ts
- src/central-server/admin-service/ui/src/views/SecurityServers/SecurityServer/DeleteSecurityServerAddressDialog.vue
- src/central-server/admin-service/ui/src/views/SecurityServers/SecurityServer/EditSecurityServerAddressDialog.vue
- src/central-server/admin-service/ui/src/views/SecurityServers/SecurityServer/SecurityServer.vue
- src/central-server/admin-service/ui/src/views/SecurityServers/SecurityServer/SecurityServerDetails.vue
> feat(CS:UI): Security server details (XRDDEV-2265)

- src/central-server/admin-service/ui-system-test/src/intTest/java/org/niis/xroad/cs/test/ui/glue/SystemSettingsManagementServicesStepDefs.java
- src/central-server/admin-service/ui-system-test/src/intTest/java/org/niis/xroad/cs/test/ui/page/SettingsManagementServicesPageObj.java
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0470-cs-settings-management-services.feature
- src/central-server/admin-service/ui/src/components/systemSettings/ManagementServices.vue
- src/central-server/admin-service/ui/src/components/systemSettings/SelectSubsystemDialog.vue
- src/central-server/admin-service/ui/src/store/modules/management-services.ts
under Settings -> System Settings 
Refs: XRDDEV-2253
> feat: e2e tests for cs management services block 

- src/central-server/admin-service/infra-api-rest/src/main/java/org/niis/xroad/cs/admin/rest/api/openapi/BackupsApiController.java
- src/central-server/admin-service/int-test/src/intTest/java/org/niis/xroad/cs/test/glue/BackupStepDefs.java
- src/central-server/admin-service/int-test/src/intTest/resources/behavior/api/backupsApi.feature
> feat: Central server backup delete endpoint

- src/central-server/admin-service/infra-api-rest/src/main/java/org/niis/xroad/cs/admin/rest/api/openapi/TrustedAnchorsApiController.java
- src/central-server/admin-service/int-test/src/intTest/java/org/niis/xroad/cs/test/glue/TrustedAnchorsApiStepDefs.java
- src/central-server/admin-service/int-test/src/intTest/resources/behavior/api/trustedAnchorsApi.feature
- src/central-server/admin-service/int-test/src/intTest/resources/files/trusted-anchor/trusted-anchor-2.xml
https://nordic-institute.atlassian.net/browse/XRDDEV-2294
> feat: API to view a list of trusted anchors

- src/central-server/admin-service/ui/src/locales/en.json
- src/central-server/admin-service/ui/src/views/Members/Member/Details/DeleteMemberDialog.vue
> fix: the error message in member delete dialog

- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/managementrequest/ManagementRequestServiceImpl.java
- src/central-server/admin-service/ui/src/views/ManagementRequests/ManagementRequestsList.vue
> fix: management request default sorting added

- src/central-server/admin-service/ui-system-test/src/intTest/java/org/niis/xroad/cs/test/ui/glue/ManagementRequestsStepDefs.java
- src/central-server/admin-service/ui-system-test/src/intTest/java/org/niis/xroad/cs/test/ui/page/ManagementRequestsPageObj.java
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0900-cs-management-requests.feature
> chore: Set default ordering in Management Requests E2E test

- src/central-server/admin-service/globalconf-generator/src/main/java/org/niis/xroad/cs/admin/globalconf/generator/DirectoryContentBuilder.java
- src/central-server/admin-service/globalconf-generator/src/main/java/org/niis/xroad/cs/admin/globalconf/generator/DirectoryContentSigner.java
- src/central-server/admin-service/globalconf-generator/src/main/java/org/niis/xroad/cs/admin/globalconf/generator/MultipartMessage.java
- src/central-server/admin-service/globalconf-generator/src/test/java/org/niis/xroad/cs/admin/globalconf/generator/DirectoryContentBuilderTest.java
- src/central-server/admin-service/globalconf-generator/src/test/java/org/niis/xroad/cs/admin/globalconf/generator/DirectoryContentSignerTest.java
- src/central-server/admin-service/globalconf-generator/src/test/java/org/niis/xroad/cs/admin/globalconf/generator/MultipartMessageTest.java
Hash should not include content type header.
> fix: global configuration hash calculation

- src/central-server/admin-service/infra-api-rest/src/main/java/org/niis/xroad/cs/admin/rest/api/openapi/SystemApiController.java
- src/central-server/openapi-model/src/main/resources/openapi-definition.yaml
> chore: remove unused apis

- Docker/centralserver/README.md
- src/central-server/admin-service/ui/package-lock.json
- src/central-server/admin-service/ui/package.json
- src/security-server/admin-service/ui/package-lock.json
- src/shared-ui/package-lock.json
- src/shared-ui/package.json
merge from develop, bump decode-uri-component version to 0.2.2
> Bump decode uri component version

- src/central-server/admin-service/core-api/src/main/java/org/niis/xroad/cs/admin/api/service/CertificationServicesService.java
- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/CertificationServicesServiceImpl.java
- src/central-server/admin-service/core/src/test/java/org/niis/xroad/cs/admin/core/service/CertificationServicesServiceImplTest.java
- src/central-server/admin-service/infra-api-rest/src/main/java/org/niis/xroad/cs/admin/rest/api/openapi/CertificationServicesController.java
- src/central-server/admin-service/int-test/src/intTest/java/org/niis/xroad/cs/test/glue/CertificationServicesApiStepDefs.java
- src/central-server/admin-service/int-test/src/intTest/resources/behavior/api/certificationServicesApi.feature
- src/common-rest-api/src/main/java/org/niis/xroad/restapi/config/audit/RestApiAuditEvent.java
> feat: API for deleting a certification service

- src/central-server/admin-service/ui-system-test/src/intTest/java/org/niis/xroad/cs/test/ui/glue/TrustServicesStepDefs.java
- src/central-server/admin-service/ui-system-test/src/intTest/java/org/niis/xroad/cs/test/ui/page/TrustServicesPageObj.java
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0500-cs-trust-services.feature
- src/central-server/admin-service/ui/src/locales/en.json
- src/central-server/admin-service/ui/src/store/modules/trust-services.ts
- src/central-server/admin-service/ui/src/views/TrustServices/CertificationService/CertificationServiceDetails.vue
- src/central-server/admin-service/ui/src/views/TrustServices/TrustServiceList.vue
> feat: delete a certification service through the UI

- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/InitializationServiceImpl.java
- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/SystemParameterServiceImpl.java
- src/central-server/admin-service/int-test/src/intTest/resources/behavior/api/initializationApi.feature
- src/central-server/admin-service/ui/src/views/InitialConfiguration/InitialConfiguration.vue
- src/common-domain/src/main/java/org/niis/xroad/restapi/exceptions/DeviationCodes.java
> fix: Central Server initialization form fields are mandatory in the API, but sent as null from UI, when value previously set

- doc/Manuals/ig-csha_x-road_6_ha_installation_guide.md
> fix: Documentation update for standby DB, standby setup has changed in newer Postgres versions.

- src/common-rest-api/src/main/java/org/niis/xroad/restapi/auth/securityconfigurer/MultiAuthWebSecurityConfig.java
- src/packages/src/xroad/common/center/usr/share/xroad/scripts/configure_management_api_key.sh
- src/packages/src/xroad/ubuntu/generic/xroad-center.postinst
> feat: Ensure API KEY with XROAD_MANAGEMENT_SERVICE role configured for registration & management services during installation

- src/central-server/admin-service/core-api/src/main/java/org/niis/xroad/cs/admin/api/service/ManagementRequestService.java
- src/central-server/admin-service/core-api/src/main/java/org/niis/xroad/cs/admin/api/service/SecurityServerService.java
- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/SecurityServerServiceImpl.java
- src/central-server/admin-service/core/src/test/java/org/niis/xroad/cs/admin/core/service/SecurityServerServiceImplTest.java
- src/central-server/admin-service/infra-api-rest/src/main/java/org/niis/xroad/cs/admin/rest/api/converter/db/SubsystemDtoConverter.java
- src/central-server/admin-service/infra-api-rest/src/test/java/org/niis/xroad/cs/admin/rest/api/converter/db/SubsystemDtoConverterTest.java
- src/central-server/admin-service/infra-jpa/src/main/java/org/niis/xroad/cs/admin/jpa/repository/JpaManagementRequestViewRepository.java
Refs: XRDDEV-2341
https://nordic-institute.atlassian.net/browse/XRDDEV-2341
> fix: Subsystem-related information is not shown correctly in the Central Server Members

- src/central-server/admin-service/ui-system-test/src/intTest/java/org/niis/xroad/cs/test/ui/page/GlobalGroupDetailsPageObj.java
- src/central-server/admin-service/ui-system-test/src/intTest/java/org/niis/xroad/cs/test/ui/page/TrustServicesPageObj.java
- src/central-server/admin-service/ui/src/components/globalGroups/AddGroupMembersDialog.vue
- src/central-server/admin-service/ui/src/components/globalGroups/GlobalGroupMembers.vue
- src/central-server/admin-service/ui/src/components/ui/DetailsView.vue
- src/central-server/admin-service/ui/src/views/AppBase.vue
- src/central-server/admin-service/ui/src/views/GlobalResources/GlobalGroup/GlobalGroup.vue
- src/central-server/admin-service/ui/src/views/ManagementRequests/ManagementRequestDetails.vue
- src/central-server/admin-service/ui/src/views/Members/Member/Member.vue
- src/central-server/admin-service/ui/src/views/SecurityServers/SecurityServer/SecurityServer.vue
- src/central-server/admin-service/ui/src/views/TrustServices/CertificationService/CertificationService.vue
quick change to have consistent back button form details view
Refs: XRDDEV-2343
> fix(cs:api): Active session check

- src/central-server/admin-service/application/src/main/resources/application.yml
- src/packages/src/xroad/ubuntu/generic/xroad-center.postinst
> feat: CS admin shall continue using existing TLS key & certificate when upgrading to version >= 7.3.0

- src/central-server/admin-service/ui/src/assets/global-style.scss
- src/central-server/admin-service/ui/src/views/Members/Member/Subsystems/MemberSubsystems.vue
> fix: highlighting in the Central Server Members - Subsystems table

- src/central-server/admin-service/infra-jpa/src/main/resources/liquibase/centerui/007-management-request-view.xml
> fix: Client owner name fix in Management requests view details

- src/central-server/admin-service/ui/src/components/managementRequests/MrConfirmDialog.vue
- src/central-server/admin-service/ui/src/components/managementRequests/MrDeclineDialog.vue
> fix: Central Server Approve/Decline management request popup is not closed when an error occurs

- src/central-server/management-service/core/src/main/java/org/niis/xroad/cs/management/core/configuration/ManagementServiceConfiguration.java
- src/central-server/management-service/core/src/main/java/org/niis/xroad/cs/management/core/service/GlobalConfUpdater.java
- src/central-server/registration-service/src/main/java/org/niis/xroad/cs/registrationservice/config/RegistrationServiceConfiguration.java
> fix: management service shall keep globalconf up to date

- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/SecurityServerServiceImpl.java
- src/central-server/admin-service/core/src/test/java/org/niis/xroad/cs/admin/core/service/SecurityServerServiceImplTest.java
- src/central-server/admin-service/ui/src/components/managementRequests/details/MrClientInformation.vue
- src/central-server/admin-service/ui/src/locales/en.json
Refs: XRDDEV-2362
fix: Member details subsystems view shows incorrect registered subsystems
Refs: XRDDEV-2341
> fix: Owner change management request details title has an incorrect label

- src/security-server/admin-service/ui/src/views/AddSubsystem/AddSubsystem.vue
- src/security-server/admin-service/ui/src/views/AppError.vue
Refs: XRDDEV-2366
also removed one line of duplicate ccs style
> fix: No error message is shown in the UI when sending a client registration request from the Security Server fails.

- doc/Manuals/ig-cs_x-road_6_central_server_installation_guide.md
> docs: Central Server installation manual reviewed

- src/central-server/management-service/application/src/main/java/org/niis/xroad/cs/management/application/configuration/WebServerCustomizer.java
> fix: Incorrect conditional property value in management service rate limit

- src/common-rest-api/src/main/java/org/niis/xroad/restapi/config/audit/AuditEventLoggingFacadeImpl.java
- src/common-rest-api/src/test/java/org/niis/xroad/restapi/config/audit/AuditLoggingTest.java
- src/common-ui/src/main/java/ee/ria/xroad/commonui/jaas/PAMLoginModule.java
- src/common-util/src/main/java/ee/ria/xroad/common/AuditLogger.java
- src/common-util/src/test/java/ee/ria/xroad/common/AuditLoggerTest.java
- src/security-server/admin-service/application/src/test/java/org/niis/xroad/securityserver/restapi/openapi/AuditLoggingRestTemplateTest.java
- src/signer-console/src/main/java/ee/ria/xroad/signer/console/SignerCLI.java
> feat: Include IP addresses in audit logs

- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/config/CookieSameSiteConfig.java
> feat: setting SameSite=Strict for Central Server UI cookies

- src/central-server/admin-service/ui/package-lock.json
- src/central-server/admin-service/ui/package.json
- src/central-server/admin-service/ui/src/components/layout/UserDropMenu.vue
- src/central-server/admin-service/ui/src/main.ts
> XRDDEV-2392 use session storage for UI state

- doc/Manuals/ig-cs_x-road_6_central_server_installation_guide.md
> docs: minor updates in central server installation manual

- src/packages/src/xroad/common/center-management-service/etc/xroad/services/centralserver-management-service.conf
- src/packages/src/xroad/common/center-registration-service/etc/xroad/services/centralserver-registration-service.conf
- src/packages/src/xroad/common/center/etc/xroad/services/centralserver-admin-service.conf
This change gives more breathing room for application under heavy use.
Refs: XRDDEV-2391
> chore: Increase default CS admin/registration/management api memory settings

- src/central-server/admin-service/ui/src/views/Members/Member/Subsystems/AddMemberSubsystemDialog.vue
- src/central-server/admin-service/ui/src/views/Members/Member/Subsystems/DeleteMemberSubsystemDialog.vue
- src/central-server/admin-service/ui/src/views/Members/Member/Subsystems/MemberSubsystems.vue
- src/central-server/admin-service/ui/src/views/Members/Member/Subsystems/UnregisterMemberSubsystemDialog.vue
> fix: Confirm dialogs of subsystems action should clear if error occurs

- src/central-server/admin-service/globalconf-generator/src/main/java/org/niis/xroad/cs/admin/globalconf/generator/GlobalConfGenerationServiceImpl.java
- src/central-server/admin-service/globalconf-generator/src/main/java/org/niis/xroad/cs/admin/globalconf/generator/PrivateParametersMarshaller.java
- src/central-server/admin-service/globalconf-generator/src/main/java/org/niis/xroad/cs/admin/globalconf/generator/SharedParametersMarshaller.java
- src/central-server/admin-service/globalconf-generator/src/test/java/org/niis/xroad/cs/admin/globalconf/generator/PrivateParametersMarshallerTest.java
- src/central-server/admin-service/globalconf-generator/src/test/java/org/niis/xroad/cs/admin/globalconf/generator/SharedParametersMarshallerTest.java
- src/common-util/src/main/java/ee/ria/xroad/common/conf/globalconf/PrivateParametersSchemaValidatorV2.java
- src/common-util/src/main/java/ee/ria/xroad/common/conf/globalconf/SharedParametersSchemaValidatorV2.java
> fix: Verify private-params.xml & shared-params.xml during their generation

- src/central-server/admin-service/ui/src/components/globalGroups/DeleteGroupMemberDialog.vue
- src/central-server/admin-service/ui/src/components/globalGroups/GlobalGroupMembers.vue
- src/central-server/admin-service/ui/src/components/managementRequests/MrStatusCell.vue
- src/central-server/admin-service/ui/src/components/securityServers/DeleteAuthenticationCertificateDialog.vue
- src/central-server/admin-service/ui/src/views/Members/Member/Subsystems/MemberSubsystems.vue
show request without status with no status + few small fixes for warnings
Closes XRDDEV-2380
> XRDDEV-2380: fix(cs:ui): display properly request without status

- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/ConfigurationSigningKeysServiceImpl.java
- src/central-server/admin-service/core/src/test/java/org/niis/xroad/cs/admin/core/service/ConfigurationSigningKeysServiceImplTest.java
- src/central-server/admin-service/infra-api-rest/src/main/java/org/niis/xroad/cs/admin/rest/api/openapi/SystemApiController.java
- src/central-server/admin-service/ui/src/components/managementRequests/details/MrClientInformation.vue
- src/central-server/admin-service/ui/src/components/tokens/KeysTable.vue
- src/central-server/admin-service/ui/src/components/tokens/TokenExpandable.vue
- src/central-server/admin-service/ui/src/components/tokens/Tokens.vue
- src/central-server/admin-service/ui/src/main.ts
- src/central-server/admin-service/ui/src/views/GlobalConfiguration/shared/Configuration.vue
recreate anchor on add/delete signey key and CS address update
Closes XRDDEV-2394
> XRDDEV-2394: recreate anchor on CS setting changes

- doc/Manuals/ig-cs_x-road_6_central_server_installation_guide.md
- doc/Manuals/ig-ss_x-road_v6_security_server_installation_guide.md
- doc/Manuals/ig-ss_x-road_v6_security_server_installation_guide_for_rhel.md
> docs: Backup Encryption Configuration

- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/entity/AuthenticationCertificateDeletionRequestEntity.java
- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/entity/AuthenticationCertificateRegistrationRequestEntity.java
- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/entity/ClientDeletionRequestEntity.java
- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/entity/ClientRegistrationRequestEntity.java
- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/entity/OwnerChangeRequestEntity.java
- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/entity/RequestEntity.java
- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/entity/RequestWithProcessingEntity.java
- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/managementrequest/AuthenticationCertificateDeletionRequestHandler.java
- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/managementrequest/AuthenticationCertificateRegistrationRequestHandler.java
- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/managementrequest/ClientDeletionRequestHandler.java
- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/managementrequest/ClientRegistrationRequestHandler.java
- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/managementrequest/OwnerChangeRequestHandler.java
- src/central-server/admin-service/core/src/test/java/org/niis/xroad/cs/admin/core/entity/mapper/RequestMapperTest.java
- src/central-server/admin-service/int-test/src/intTest/java/org/niis/xroad/cs/test/glue/ManagementRequestsApiStepDefs.java
- src/central-server/admin-service/int-test/src/intTest/resources/behavior/api/securityServerApi.feature
> fix: saving comments for management requests

- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0100-cs-initialization.feature
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0200-cs-authentication.feature
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0300-cs-settings-member-classes.feature
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0340-cs-settings-global-resources.feature
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0350-cs-settings-system-parameters.feature
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0360-cs-settings-api-keys.feature
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0400-cs-members.feature
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0450-cs-member-subsystems.feature
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0460-cs-management-service-provider-registration.feature
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0480-cs-global-group-members.feature
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0500-cs-trust-services.feature
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0530-cs-intermediate-ca.feature
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0540-cs-intermediate-ca-details.feature
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0550-cs-intermediate-ca-ocsp-responders.feature
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0560-cs-ocsp-responders.feature
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0570-cs-trust-services-timestamping-services.feature
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0600-cs-internal-signing-keys.feature
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0610-cs-external-signing-keys.feature
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0700-cs-global-configuration-anchor-internal.feature
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0710-cs-global-configuration-anchor-external.feature
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0800-cs-global-configuration-parts-external.feature
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0810-cs-global-configuration-parts-internal.feature
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0850-cs-global-configuration-trusted-anchors.feature
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0900-cs-management-requests.feature
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0970-cs-settings-management-services.feature
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/1000-cs-security-server-details.feature
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/1010-cs-security-server-clients.feature
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/1020-cs-security-server-auth-certificates.feature
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/1100-cs-backup-and-restore.feature
> test: ui-system-tests reorganized due to globalConf generation validation

- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/entity/mapper/ApprovedTsaMapper.java
- src/central-server/admin-service/core/src/test/java/org/niis/xroad/cs/admin/core/entity/mapper/ApprovedTsaMapperTest.java
- src/central-server/admin-service/ui/package-lock.json
- src/central-server/admin-service/ui/public/index.html
- src/central-server/admin-service/ui/src/views/SecurityServers/SecurityServersList.vue
- src/central-server/admin-service/ui/src/views/Settings/ApiKeys/ApiKeys.vue
- src/shared-ui/src/components/icons/IconBase.vue
> fix: small Central Server UI improvementss

- src/central-server/admin-service/ui/src/views/Members/Member/Subsystems/MemberSubsystems.vue
> fix: Member Subsystem lists 'Server Owner' column name

- doc/Manuals/ig-csha_x-road_6_ha_installation_guide.md
Refs: XRDDEV-2356
Note. The Monitoring HA State endpoint part will be updated with implementation story (XRDDEV-2401)
> chore: Central Server HA installation manual updates

- src/central-server/admin-service/ui/src/views/Members/Member/Member.vue
- src/central-server/admin-service/ui/src/views/Members/MemberList.vue
- src/central-server/admin-service/ui/src/views/SecurityServers/SecurityServer/SecurityServerClients.vue
- src/central-server/admin-service/ui/src/views/SecurityServers/SecurityServer/SecurityServerDetails.vue
> fix: Navigating Back from Security Server client details goes to Members list

- src/central-server/admin-service/ui-system-test/src/intTest/java/org/niis/xroad/cs/test/ui/glue/ManagementRequestsStepDefs.java
- src/central-server/admin-service/ui-system-test/src/intTest/java/org/niis/xroad/cs/test/ui/glue/NavigationStepDefs.java
- src/central-server/admin-service/ui-system-test/src/intTest/java/org/niis/xroad/cs/test/ui/page/CommonPageObj.java
- src/central-server/admin-service/ui-system-test/src/intTest/resources/application-override.yml
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0900-cs-management-requests.feature
- src/central-server/admin-service/ui/package-lock.json
- src/central-server/admin-service/ui/src/router/routes.ts
- src/central-server/admin-service/ui/src/store/modules/managementRequestStore.ts
- src/central-server/admin-service/ui/src/store/modules/trusted-anchors.ts
- src/central-server/admin-service/ui/src/views/ManagementRequests/ManagementRequestsList.vue
- src/shared-ui/src/components/XrdSearch.vue
> feat: remembering the filters on management requests UI page

- src/central-server/admin-service/ui/src/views/Members/Member/Details/MemberDetails.vue
> fix: Owned Servers list is empty in the Member details view

- src/central-server/admin-service/ui/src/components/configurationParts/ConfigurationPartsList.vue
> fix: missing file name in Configuration Parts

- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/managementrequest/AuthenticationCertificateDeletionRequestHandler.java
- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/managementrequest/ClientDeletionRequestHandler.java
- src/central-server/admin-service/int-test/src/intTest/resources/behavior/api/managementRequestsApi.feature
- src/security-server/admin-service/ui/src/views/CertificateDetails/CertificateDetails.vue
also small SS UI fix
Closes XRDDEV-2395
> fix(cs): revoke pending registration on delete request

- src/central-server/admin-service/ui/src/views/SecurityServers/SecurityServer/SecurityServerDetails.vue
Rollback previous change to security server delete dialog.
> fix: delete security server fix

- doc/Architecture/arc-tec_x-road_technologies.md
> docs: xroad technologies doc updated (Central Server part)

- doc/Manuals/ug-cs_x-road_6_central_server_user_guide.md
- doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md
> docs: Central Server REST API doc

- src/central-server/admin-service/ui/src/components/systemSettings/MemberClasses.vue
> fix: member class add dialog didn't disappear after saving

- src/packages/src/xroad/ubuntu/generic/xroad-base.preinst
https://github.com/nordic-institute/X-Road/issues/1717
> fix: Improve setting locale

- src/packages/src/xroad/common/centralserver/usr/share/xroad/scripts/configure_management_api_key.sh
> fix(cs): fix wrong variable name in script

- doc/DataModels/dm-cs_x-road_central_server_configuration_data_model.md
- doc/Manuals/ug-cs_x-road_6_central_server_user_guide.md
- src/central-server/admin-service/infra-jpa/src/main/resources/liquibase/centerui-changelog.xml
- src/central-server/admin-service/infra-jpa/src/main/resources/liquibase/centerui/202306151639-drop-schema-migrations.xml
- src/central-server/admin-service/infra-jpa/src/main/resources/liquibase/centerui/202306161128-requests-remove-unused-columns.xml
> fix: removing unnecessary database objects from cs database

- src/BUILD.md
- src/common/common-ui/src/test/java/ee/ria/xroad/commonui/OptionalPartsConfBehavior.java
- src/compile_code.sh
- src/prepare_buildhost.sh
> chore: update BUILD.md for new Central Server

- src/central-server/admin-service/ui/src/views/InitialConfiguration/InitialConfiguration.vue
> fix: disable button after submit in cs init form

- ansible/README.md
- ansible/group_vars/all/vars.yml
- ansible/roles/build-packages/tasks/main.yml
- ansible/roles/init-lxd/tasks/main.yml
- ansible/roles/packages-to-local-repo/tasks/main.yml
- ansible/roles/packages-to-local-repo/tasks/ubuntu.yml
- ansible/vars_files/common_modules.yml
- ansible/vars_files/cs_modules.yml
- ansible/vars_files/ss_modules.yml
- ansible/xroad_dev.yml
- src/BUILD.md
- src/compile_env.sh
- src/packages/docker/rpm-el8/Dockerfile
> chore: update ansible scripts and related documentation

- ansible/roles/xroad-ca/files/home/ca/CA/CA.cnf
- Add support for the businessCategory field.
Refs: [XRDDEV-2446](https://nordic-institute.atlassian.net/browse/XRDDEV-2446)
[XRDDEV-2446]: https://nordic-institute.atlassian.net/browse/XRDDEV-2446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: XRDDEV-2446 Update Test CA configuration

- src/central-server/admin-service/ui-system-test/src/intTest/java/org/niis/xroad/cs/test/ui/glue/SystemSettingsManagementServicesStepDefs.java
- src/central-server/admin-service/ui-system-test/src/intTest/java/org/niis/xroad/cs/test/ui/page/SettingsManagementServicesPageObj.java
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0460-cs-management-service-provider-registration.feature
- src/central-server/admin-service/ui/src/components/systemSettings/ManagementServices.vue
- src/central-server/admin-service/ui/src/locales/en.json
- src/security-server/admin-service/ui/src/locales/en.json
Refs: [XRDDEV-2445](https://nordic-institute.atlassian.net/browse/XRDDEV-2445)
[XRDDEV-2445]: https://nordic-institute.atlassian.net/browse/XRDDEV-2445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: XRDDEV-2445 minor fixes to Central Server and Security Server translations

- doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md
- src/common/common-admin-api/src/main/java/org/niis/xroad/restapi/config/AbstractDeprecatedPropsChecker.java
- src/security-server/admin-service/application/src/main/resources/common-application.yml
- src/security-server/admin-service/application/src/test/java/org/niis/xroad/securityserver/restapi/ApplicationIpRateLimitTest.java
> chore: deprecating old rate limiting parameters

- src/op-monitor-daemon/src/main/java/ee/ria/xroad/opmonitordaemon/HealthDataMetrics.java
- src/op-monitor-daemon/src/main/java/ee/ria/xroad/opmonitordaemon/OperationalDataRecord.java
- src/op-monitor-daemon/src/test/java/ee/ria/xroad/opmonitordaemon/OperationalDataRecordManagerTest.java
- src/op-monitor-daemon/src/test/java/ee/ria/xroad/opmonitordaemon/OperationalDataRecordsTest.java
> fix: Store securityServerType property value in the operational monitoring database using non capital letters

- src/central-server/admin-service/ui/src/components/globalGroups/GroupMembersFilterDialog.vue
> fix: Central Server global groups member list search filtering does not work correctly

- sidecar/Dockerfile
- sidecar/Dockerfile-variant
- sidecar/docker-build.sh
- sidecar/kubernetes/security-server-sidecar-slim.yaml
- sidecar/kubernetes/security-server-sidecar.yaml
- sidecar/kubernetesBalancer/primary/Dockerfile
- sidecar/kubernetesBalancer/secondary/Dockerfile
- sidecar/kubernetesBalancer/slim/primary/Dockerfile
- sidecar/kubernetesBalancer/slim/secondary/Dockerfile
- sidecar/slim/Dockerfile
> fix: Sidecar version number fixes

- doc/Sidecar/kubernetes_security_server_sidecar_user_guide.md
> fix: type errors fixes in yml scripts

- ansible/TESTCA.md
> docs: Update test CA documentation

- src/security-server/admin-service/ui-system-test/src/intTest/java/org/niis/xroad/ss/test/ui/glue/ClientServicesStepDefs.java
- src/security-server/admin-service/ui-system-test/src/intTest/java/org/niis/xroad/ss/test/ui/page/ClientInfoPageObj.java
- src/security-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0560-ss-client-soap-services.feature
- src/security-server/admin-service/ui/src/views/Service/AccessRightsDialog.vue
> Security Server add client service access rights filter clearing fix

- src/security-server/admin-service/application/src/main/java/org/niis/xroad/securityserver/restapi/openapi/DiagnosticsApiController.java
> Missing authority for timestamping service table

- src/packages/src/xroad/ubuntu/generic/xroad-center-management-service.links
- src/packages/src/xroad/ubuntu/generic/xroad-center-management-service.postinst
- src/packages/src/xroad/ubuntu/generic/xroad-center-registration-service.links
- src/packages/src/xroad/ubuntu/generic/xroad-center-registration-service.postinst
> fix: renamed nginx sites-enabled symlinks

- doc/Manuals/ig-cs_x-road_6_central_server_installation_guide.md
- src/packages/src/xroad/ubuntu/generic/xroad-center.preinst
> Database integrity checks before center upgrade

- src/security-server/admin-service/application/src/main/java/org/niis/xroad/securityserver/restapi/openapi/OpenapiApiController.java
> Security Server OpenAPI description file default filename

- doc/Manuals/ig-cs_x-road_6_central_server_installation_guide.md
> Database integrity check minor documentation fix

- .github/docker/securityserver/Dockerfile
- .github/docker/securityserver/files/ss-xroad.conf
- .github/workflows/run_tests.yaml
- Docker/securityserver/Dockerfile
- Docker/securityserver/files/ss-xroad.conf
- src/security-server/system-test/build.gradle
- src/security-server/system-test/src/intTest/java/org/niis/xroad/ss/test/addons/SsAddonTestConfiguration.java
- src/security-server/system-test/src/intTest/java/org/niis/xroad/ss/test/addons/api/FeignXRoadSoapRequestsApi.java
- src/security-server/system-test/src/intTest/java/org/niis/xroad/ss/test/addons/glue/OpMonitorStepDefs.java
- src/security-server/system-test/src/intTest/java/org/niis/xroad/ss/test/addons/glue/ProxyMonitorStepDefs.java
- src/security-server/system-test/src/intTest/resources/behavior/02-addons/0200-ss-opmonitoring.feature
- src/security-server/system-test/src/intTest/resources/behavior/02-addons/2300-ss-opmonitoring.feature
- src/security-server/system-test/src/intTest/resources/files/soap-requests/health-data.request
- src/security-server/system-test/src/intTest/resources/files/soap-requests/operational-data.request
> Security server op-monitor addon system tests

- src/packages/src/xroad/default-configuration/override-securityserver-ee.ini
- src/packages/src/xroad/default-configuration/override-securityserver-fi.ini
- src/version_change.sh
Refs: XRDDEV-2488
Setting the min supported version in scr/version_change.sh tool. 
Release template is updated with verification step.
> feat: setting min supported version

- src/build.gradle
- src/central-server/admin-service/application/build.gradle
> build: hierarchical subproject group ids to generate unique ids for ORT

- src/central-server/admin-service/infra-jpa/src/main/resources/liquibase/centerui-changelog.xml
- src/central-server/admin-service/infra-jpa/src/main/resources/liquibase/centerui/202310031700-security-server-unique.xml
- src/packages/src/xroad/ubuntu/generic/xroad-center.preinst
- src/shared-ui/audit-ci-shared.json
> fix: added unique constraint for security server code

- src/central-server/admin-service/ui-system-test/src/intTest/java/org/niis/xroad/cs/test/ui/glue/MemberDetailsStepDefs.java
- src/central-server/admin-service/ui-system-test/src/intTest/java/org/niis/xroad/cs/test/ui/page/MemberDetailsPageObj.java
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/1040-cs-member-details.feature
- src/central-server/admin-service/ui/src/views/Members/Member/Details/MemberDetails.vue
> feat: navigation from the member details view to the related security server details

- src/packages/src/xroad/common/base/usr/share/xroad/db/liquibase.sh
> feat: do not print liquibase banner

- src/central-server/admin-service/globalconf-generator/src/main/java/org/niis/xroad/cs/admin/globalconf/generator/GlobalConfGenerationServiceImpl.java
- src/central-server/admin-service/globalconf-generator/src/main/java/org/niis/xroad/cs/admin/globalconf/generator/LocalCopyWriter.java
- src/central-server/admin-service/globalconf-generator/src/test/java/org/niis/xroad/cs/admin/globalconf/generator/LocalCopyWriterTest.java
- src/common/common-verifier/src/main/java/ee/ria/xroad/common/conf/globalconf/GlobalConfImpl.java
> fix: Missing configuration version prop from CS's configuration part metadata file

- src/central-server/admin-service/int-test/src/intTest/java/org/niis/xroad/cs/test/api/FeignClientsApi.java
- src/central-server/admin-service/int-test/src/intTest/resources/behavior/api/clients.feature
- src/central-server/admin-service/ui-system-test/src/intTest/java/org/niis/xroad/cs/test/ui/glue/MemberStepDefs.java
- src/central-server/admin-service/ui-system-test/src/intTest/java/org/niis/xroad/cs/test/ui/page/MemberPageObj.java
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0400-cs-members.feature
- src/central-server/openapi-model/src/main/resources/openapi-definition.yaml
> feat: member and security server search fields should accept more than 25 characters

- src/security-server/admin-service/ui/src/views/Settings/BackupAndRestore/BackupAndRestore.vue
- src/security-server/system-test/src/intTest/java/org/niis/xroad/ss/test/ui/glue/CommonStepDefs.java
- src/security-server/system-test/src/intTest/resources/behavior/01-ui/0600-ss-backup-and-restore.feature
> fix: fix security server restore from backup

- doc/Manuals/ug-sec_x_road_security_hardening.md
> docs: Updating Security hardening guidelines about Publish global configuration over HTTPS

- doc/Manuals/ug-sec_x_road_security_hardening.md
> fix: doc little fixes

- src/central-server/admin-service/globalconf-generator/src/main/java/org/niis/xroad/cs/admin/globalconf/generator/SharedParameters.java
- src/central-server/admin-service/globalconf-generator/src/main/java/org/niis/xroad/cs/admin/globalconf/generator/SharedParametersV3Converter.java
- src/central-server/admin-service/globalconf-generator/src/test/java/org/niis/xroad/cs/admin/globalconf/generator/SharedParametersV3ConverterTest.java
- src/common/common-util/src/main/java/ee/ria/xroad/common/conf/globalconf/SharedParameters.java
- src/common/common-util/src/main/java/ee/ria/xroad/common/conf/globalconf/SharedParametersV3Converter.java
- src/common/common-util/src/main/resources/globalconf/common/shared-parameters.xsd
- src/common/common-util/src/main/resources/globalconf/v2/shared-parameters.xsd
- src/common/common-util/src/main/resources/globalconf/v3/shared-parameters.xsd
refs: XRDDEV-2496
These are ACME related global configuration changes, that go with version 7.4. Other ACME related code changes will be added to version 7.5.
> feat: added couple of ACME properties to global conf

- sidecar/files/_entrypoint_common.sh
> feat: generate sidecar grpc tls keys

- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/CertificationServicesServiceImpl.java
- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/IntermediateCasServiceImpl.java
- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/OcspRespondersServiceImpl.java
- src/central-server/admin-service/infra-api-rest/src/main/java/org/niis/xroad/cs/admin/rest/api/openapi/CertificationServicesController.java
- src/central-server/admin-service/infra-api-rest/src/main/java/org/niis/xroad/cs/admin/rest/api/openapi/IntermediateCasController.java
- src/central-server/admin-service/ui-system-test/src/intTest/java/org/niis/xroad/cs/test/ui/glue/TrustServicesOcspRespondersStepDefs.java
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0550-cs-intermediate-ca-ocsp-responders.feature
- src/central-server/admin-service/ui-system-test/src/intTest/resources/behavior/ui/0560-cs-ocsp-responders.feature
- src/central-server/admin-service/ui/src/components/ocspResponders/AddOcspResponderDialog.vue
- src/central-server/admin-service/ui/src/components/ocspResponders/EditOcspResponderDialog.vue
- src/central-server/admin-service/ui/src/components/ocspResponders/OcspRespondersList.vue
- src/central-server/admin-service/ui/src/store/modules/trust-services.ts
- src/central-server/openapi-model/src/main/resources/openapi-definition.yaml
> feat: allow adding OCSP responder without a certificate.

- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/entity/AddressChangeRequestEntity.java
- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/managementrequest/AddressChangeRequestHandler.java
- src/central-server/admin-service/core/src/test/java/org/niis/xroad/cs/admin/core/entity/mapper/RequestMapperTest.java
- src/central-server/admin-service/core/src/test/java/org/niis/xroad/cs/admin/core/service/managementrequest/AddressChangeRequestHandlerTest.java
> feat: when updating Security Server address, saving previous one in comment

- src/security-server/admin-service/ui/src/main.ts
- src/security-server/admin-service/ui/src/store/modules/services.ts
- src/security-server/admin-service/ui/src/store/modules/system.ts
- src/security-server/admin-service/ui/src/store/modules/tokens.ts
- src/security-server/admin-service/ui/src/store/modules/user.ts
- src/security-server/admin-service/ui/src/views/LocalGroup/LocalGroup.vue
- src/security-server/admin-service/ui/src/views/Service/Endpoints/Endpoint/EndpointDetails.vue
- src/security-server/admin-service/ui/src/views/TokenDetails/TokenDetails.vue
> fix: Security server edit token view crashes when refreshing page

- doc/Architecture/spec-al_x-road_audit_log_events.md
- doc/Manuals/ug-cs_x-road_6_central_server_user_guide.md
- src/packages/src/xroad/common/center/etc/sudoers.d/xroad-nginx-reload
- src/packages/src/xroad/common/center/usr/share/xroad/scripts/reload_nginx_if_management_service_cert_changed.sh
- src/packages/src/xroad/ubuntu/generic/xroad-center.cron.d
> docs: Management service TLS certificate

- src/central-server/admin-service/infra-jpa/src/main/resources/liquibase/centerui-changelog.xml
- src/central-server/admin-service/infra-jpa/src/main/resources/liquibase/centerui/202312121722-truncate-query-string-from-anchor-urls.xml
- src/central-server/admin-service/infra-jpa/src/main/resources/liquibase/centerui/202312121722-truncate-version-from-anchor-urls.xml
> fix: Truncate version from previously persisted anchor urls

- doc/Manuals/ug-cs_x-road_6_central_server_user_guide.md
- doc/Manuals/ug-sec_x_road_security_hardening.md
> docs: Recreating Configuration Anchor file to publish over HTTPS

- doc/Manuals/ug-cs_x-road_6_central_server_user_guide.md
- doc/Protocols/pr-gconf_x-road_protocol_for_downloading_configuration.md
> docs: Update documentation regarding globalconf V3

- src/central-server/admin-service/infra-api-rest/src/main/resources/META-INF/custom-constraints.xml
- src/central-server/admin-service/int-test/src/intTest/resources/behavior/api/initializationApi.feature
- src/central-server/admin-service/int-test/src/intTest/resources/behavior/api/systemApi.feature
- src/central-server/admin-service/ui/src/components/systemSettings/EditServerAddressDialog.vue
- src/central-server/admin-service/ui/src/locales/en.json
- src/central-server/admin-service/ui/src/main.ts
- src/central-server/admin-service/ui/src/plugins/vee-validate.ts
- src/central-server/admin-service/ui/src/views/GlobalConfiguration/shared/ConfigurationDownloadUrl.vue
- src/central-server/admin-service/ui/src/views/InitialConfiguration/InitialConfiguration.vue
- src/central-server/admin-service/ui/src/views/SecurityServers/SecurityServer/EditSecurityServerAddressDialog.vue
- src/common/common-admin-api/src/main/java/org/niis/xroad/restapi/openapi/validator/AddressCharsValidator.java
- src/common/common-admin-api/src/main/java/org/niis/xroad/restapi/openapi/validator/HostAddressValidator.java
- src/common/common-admin-api/src/main/java/org/niis/xroad/restapi/openapi/validator/OnlyAddressChars.java
- src/common/common-admin-api/src/main/java/org/niis/xroad/restapi/openapi/validator/ValidHostAddress.java
- src/common/common-domain/src/main/java/org/niis/xroad/common/exception/util/CommonDeviationMessage.java
- src/security-server/admin-service/application/src/main/resources/META-INF/custom-constraints.xml
- src/security-server/admin-service/ui/src/plugins/vee-validate.ts
- src/security-server/admin-service/ui/src/views/KeysAndCertificates/SignAndAuthKeys/RegisterCertificateDialog.vue
- src/security-server/admin-service/ui/src/views/Settings/SystemParameters/EditSecurityServerAddressDialog.vue
- src/security-server/admin-service/ui/yarn.lock
- src/shared-ui/src/locales/en.json
Detect invalid characters in address
> feat: Improve address field validation

- src/configuration-client/src/main/java/ee/ria/xroad/common/conf/globalconf/ConfigurationClient.java
- src/configuration-client/src/main/java/ee/ria/xroad/common/conf/globalconf/ConfigurationClientMain.java
- src/configuration-client/src/main/java/ee/ria/xroad/common/conf/globalconf/ConfigurationDownloader.java
- src/configuration-proxy/src/main/java/ee/ria/xroad/confproxy/ConfProxy.java
- src/configuration-proxy/src/main/java/ee/ria/xroad/confproxy/ConfProxyExecutionResult.java
> Confproxy bugfixes

- src/common/common-util/src/main/java/ee/ria/xroad/common/conf/globalconf/SharedParametersV3.java
- src/common/common-util/src/main/resources/globalconf/v3/shared-parameters.xsd
- src/configuration-client/src/main/java/ee/ria/xroad/common/conf/globalconf/ConfigurationDownloader.java
- src/configuration-proxy/src/main/java/ee/ria/xroad/confproxy/ConfProxy.java
- src/configuration-proxy/src/main/java/ee/ria/xroad/confproxy/util/ConfProxyHelper.java
- src/configuration-proxy/src/main/java/ee/ria/xroad/confproxy/util/OutputBuilder.java
> feat: Confproxy shall overwrite shared-parameters' sources with its own data

- doc/Manuals/LoadBalancing/ig-xlb_x-road_external_load_balancer_installation_guide.md
> docs: RHEL PostgreSQL 12 support in external load balancer installation guide

- src/configuration-client/src/main/java/ee/ria/xroad/common/conf/globalconf/ConfigurationDownloader.java
> fix: the use of successful configuration locations' cache by changing the map's key from complex object to simple string

- doc/Manuals/ug-cs_x-road_6_central_server_user_guide.md
- src/common/common-util/src/main/java/ee/ria/xroad/common/conf/globalconf/SharedParametersV2Converter.java
- src/common/common-util/src/main/java/ee/ria/xroad/common/conf/globalconf/SharedParametersV3Converter.java
- src/common/common-util/src/test/resources/globalconf_good_v2/EE/shared-params.xml
- src/common/common-util/src/test/resources/globalconf_good_v3/EE/shared-params.xml
- src/common/common-verifier/src/test/java/ee/ria/xroad/common/conf/globalconf/GlobalConfTest.java
- src/common/common-verifier/src/test/java/ee/ria/xroad/common/conf/globalconf/GlobalConfVer3Test.java
> fix: Shared parameters converter fix

- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/managementrequest/ClientDeletionRequestHandler.java
- src/central-server/admin-service/core/src/test/java/org/niis/xroad/cs/admin/core/service/managementrequest/ClientDeletionRequestHandlerTest.java
> fix: When also declined management request not exists then throw not found exception

- src/addons/hwtoken/src/main/java/ee/ria/xroad/signer/tokenmanager/module/HardwareModuleWorker.java
- src/signer/src/main/java/ee/ria/xroad/signer/tokenmanager/module/AbstractModuleWorker.java
- src/signer/src/main/java/ee/ria/xroad/signer/tokenmanager/token/BlockingTokenWorker.java
> fix(signer): concurrency issues with HSM

- doc/DataModels/dm-ss_x-road_security_server_configuration_data_model.md
- src/security-server/admin-service/application/src/main/java/org/niis/xroad/securityserver/restapi/repository/IdentifierRepository.java
- src/security-server/admin-service/application/src/main/java/org/niis/xroad/securityserver/restapi/service/ClientService.java
- src/security-server/admin-service/application/src/test/java/org/niis/xroad/securityserver/restapi/service/ClientServiceIntegrationTest.java
> chore: When client is deleted then respective identifier is deleted as well

- src/security-server/admin-service/ui/src/components/ui/SnackBar.vue
- src/security-server/admin-service/ui/src/locales/en.json
- src/security-server/admin-service/ui/src/views/AddClient/AddClient.vue
- src/security-server/admin-service/ui/src/views/AddClient/FinishPage.vue
- src/security-server/admin-service/ui/src/views/AddMember/AddMember.vue
- src/security-server/admin-service/ui/yarn.lock
> fix SS Add Member/Client wizards

- src/common/common-admin-api/src/main/java/org/niis/xroad/restapi/auth/securityconfigurer/ApiWebSecurityConfig.java
> fix: disable session creation for requests using API key authentication

- CHANGELOG.md
- sidecar/docker-build.sh
- sidecar/kubernetes/security-server-sidecar-slim.yaml
- sidecar/kubernetes/security-server-sidecar.yaml
- src/packages/src/xroad/ubuntu/generic/changelog
> chore: Version bump and prepare for release

- doc/EnvironmentalMonitoring/Monitoring-architecture.md
- Add information about JMX and authentication.
> docs: Update environmental monitoring architecture

- doc/Manuals/LoadBalancing/ig-xlb_x-road_external_load_balancer_installation_guide.md
> docs: Add RHEL PostgreSQL 13 support in external load balancer installation guide

- .github/workflows/run_tests.yaml
- src/security-server/admin-service/ui/src/views/Service/Endpoints/Endpoint/EndpointDetails.vue
- src/security-server/admin-service/ui/src/views/Service/ServiceView.vue
> fix: after successful endpoint delete hide dialog and go back to list

- src/central-server/admin-service/globalconf-generator/src/main/java/org/niis/xroad/cs/admin/globalconf/generator/ConfigurationDistributor.java
- src/central-server/admin-service/globalconf-generator/src/main/java/org/niis/xroad/cs/admin/globalconf/generator/FileUtils.java
- src/central-server/admin-service/globalconf-generator/src/main/java/org/niis/xroad/cs/admin/globalconf/generator/GlobalConfApplier.java
- src/central-server/admin-service/globalconf-generator/src/main/java/org/niis/xroad/cs/admin/globalconf/generator/GlobalConfGenerationServiceImpl.java
> feat: cleanup after failed global conf generation

- src/asicverifier/src/main/java/ee/ria/xroad/asicverifier/AsicVerifierMain.java
- src/settings.gradle
Refs: //github.com/nordic-institute/X-Road/security/code-scanning/36
Closes: XRDDEV-2612
> chore: fix zip slip vulnerability

- sidecar/files/_entrypoint_common.sh
> fix: initialize postgres data directory when used with empty volume

- doc/Manuals/LoadBalancing/ig-xlb_x-road_external_load_balancer_installation_guide.md
> docs: Simplified creation of PostgreSQL serverconf service for RHEL 8, 9 and added warning about SELinux policy

- src/op-monitor-daemon/src/main/resources/op-monitor.hbm.xml
- src/packages/src/xroad/common/op-monitor/usr/share/xroad/db/op-monitor-changelog.xml
- src/packages/src/xroad/common/op-monitor/usr/share/xroad/db/op-monitor/6-restart-sequence.xml
> fix: reset sequence to produce predictable id values

- src/common/common-core/src/main/java/ee/ria/xroad/common/ErrorCodes.java
- src/common/common-db/src/main/java/ee/ria/xroad/common/db/HibernateUtil.java
- src/common/common-db/src/test/java/ee/ria/xroad/common/db/HibernateUtilTest.java
- src/common/common-jetty/src/main/java/ee/ria/xroad/common/util/HandlerBase.java
- src/common/common-jetty/src/main/java/ee/ria/xroad/common/util/RequestWrapper.java
- src/common/common-message/src/main/java/ee/ria/xroad/common/message/SaxSoapParserImpl.java
- src/common/common-message/src/main/java/ee/ria/xroad/common/message/SoapFault.java
- src/common/common-message/src/main/java/ee/ria/xroad/common/message/SoapParserImpl.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/clientproxy/AbstractClientProxyHandler.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/serverproxy/ServerProxyHandler.java
- src/proxy/src/main/java/ee/ria/xroad/proxy/util/CertHashBasedOcspResponder.java
> fix: Don't reveal DB data in error response

- src/addons/metaservice/build.gradle
- src/addons/metaservice/src/test/java/ee/ria/xroad/proxy/clientproxy/MetadataClientRequestProcessorTest.java
- src/common/common-domain/src/main/java/ee/ria/xroad/common/identifier/XRoadId.java
- src/gradle/libs.versions.toml
> fix: removed additional field from listClients metaservice

- src/security-server/admin-service/application/src/main/java/org/niis/xroad/securityserver/restapi/converter/CertificateAuthorityConverter.java
- src/security-server/admin-service/application/src/main/java/org/niis/xroad/securityserver/restapi/dto/ApprovedCaDto.java
- src/security-server/admin-service/application/src/main/java/org/niis/xroad/securityserver/restapi/openapi/CertificateAuthoritiesApiController.java
- src/security-server/admin-service/application/src/main/java/org/niis/xroad/securityserver/restapi/service/AcmeService.java
- src/security-server/admin-service/application/src/main/java/org/niis/xroad/securityserver/restapi/service/CertificateAuthorityService.java
- src/security-server/admin-service/ui/src/components/wizard/WizardPageCsrDetails.vue
- src/security-server/admin-service/ui/src/locales/en.json
- src/security-server/admin-service/ui/src/store/modules/certificateSignRequest.ts
- src/security-server/admin-service/ui/src/store/modules/notifications.ts
- src/security-server/admin-service/ui/src/views/AddClient/AddClient.vue
- src/security-server/admin-service/ui/src/views/KeysAndCertificates/SignAndAuthKeys/AcmeOrderCertificateDialog.vue
- src/security-server/admin-service/ui/src/views/KeysAndCertificates/SignAndAuthKeys/KeysTable.vue
- src/security-server/openapi-model/src/main/resources/META-INF/openapi-definition.yaml
show ACME metadata fetch failure warning
Refs: XRDDEV-2651
> fix: ensure that manual key creation works in case ACME failures

- src/packages/docker/rpm/Dockerfile
- src/security-server/admin-service/application/src/main/java/org/niis/xroad/securityserver/restapi/config/AcmeConfig.java
> fix: acme config had missing property substitutions that help convert acme.yml properties to java AcmeProperties

- Docker/xrd-dev-stack/local-dev-prepare.sh
- src/build_packages.sh
- src/packages/build-deb.sh
- src/packages/build-rpm.sh
> fix: handle no text coloring in jenkins for warning/error messages

- src/common/common-admin-api/src/main/java/org/niis/xroad/restapi/common/backup/repository/BackupRepository.java
- src/common/common-admin-api/src/test/java/org/niis/xroad/restapi/common/backup/repository/BackupRepositoryTest.java
Refs: https://github.com/nordic-institute/X-Road/security/code-scanning/39
> fix: ensure file is in expected directory

- src/central-server/admin-service/ui/src/store/modules/system.ts
> fix: don't show init page in case signer not responding

- src/packages/src/xroad/common/base/usr/share/xroad/scripts/_setup_db.sh
- src/packages/src/xroad/common/center/usr/share/xroad/scripts/backup_db.sh
- src/packages/src/xroad/common/center/usr/share/xroad/scripts/restore_db.sh
- src/packages/src/xroad/common/centralserver/usr/share/xroad/scripts/configure_management_api_key.sh
- src/packages/src/xroad/common/proxy/usr/share/xroad/scripts/backup_db.sh
- src/packages/src/xroad/common/proxy/usr/share/xroad/scripts/restore_db.sh
- src/packages/src/xroad/common/proxy/usr/share/xroad/scripts/setup_serverconf_db.sh
> fix: avoid adding unnecessary spaces

- src/packages/src/xroad/ubuntu/generic/xroad-center.postinst
> fix: don't override spring.datasource.url if it's present

- sidecar/kubernetesBalancer/primary/Dockerfile
- sidecar/kubernetesBalancer/slim/primary/Dockerfile
> fix: create xroad-slave home dir

- src/packages/src/xroad/common/base/usr/share/xroad/scripts/_setup_db.sh
- src/packages/src/xroad/common/center/usr/share/xroad/scripts/backup_db.sh
- src/packages/src/xroad/common/center/usr/share/xroad/scripts/restore_db.sh
- src/packages/src/xroad/common/centralserver/usr/share/xroad/scripts/configure_management_api_key.sh
- src/packages/src/xroad/common/proxy/usr/share/xroad/scripts/backup_db.sh
- src/packages/src/xroad/common/proxy/usr/share/xroad/scripts/restore_db.sh
- src/packages/src/xroad/common/proxy/usr/share/xroad/scripts/setup_serverconf_db.sh
- src/packages/src/xroad/ubuntu/generic/xroad-center.postinst
> fix: allow override of PGHOST/PGPORT using db_libpq.env

- doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md
> doc: don't allow delete disabled subsystem

- src/common/common-message/src/main/java/ee/ria/xroad/common/hashchain/HashChainVerifier.java
- src/common/common-verifier/src/main/java/ee/ria/xroad/common/signature/SignatureVerifier.java
> chore: improve logging for hash chain verifacation

- src/packages/src/xroad/common/base/usr/share/xroad/scripts/_setup_db.sh
- src/packages/src/xroad/common/center/usr/share/xroad/scripts/backup_db.sh
- src/packages/src/xroad/common/center/usr/share/xroad/scripts/restore_db.sh
- src/packages/src/xroad/common/centralserver/usr/share/xroad/scripts/configure_management_api_key.sh
- src/packages/src/xroad/common/proxy/usr/share/xroad/scripts/backup_db.sh
- src/packages/src/xroad/common/proxy/usr/share/xroad/scripts/restore_db.sh
- src/packages/src/xroad/common/proxy/usr/share/xroad/scripts/setup_serverconf_db.sh
- src/packages/src/xroad/ubuntu/generic/xroad-center.postinst
- src/shared-ui/audit-ci-shared.json
> fix: PGOPTIONS_EXTRA handling

- src/packages/src/xroad/common/centralserver/usr/share/xroad/scripts/configure_management_api_key.sh
> fix: PGOPTIONS_EXTRA handling in configure_management_api_key.sh

- doc/Manuals/LoadBalancing/ig-xlb_x-road_external_load_balancer_installation_guide.md
- Add assumption that the load balancer must support TLS passthrough.
- Editorial updates.
> docs: Updates to the SS LB installation guide

- src/addons/wsdlvalidator/build.gradle
- src/gradle/libs.versions.toml
- src/security-server/system-test/src/intTest/resources/container-files/etc/xroad/conf.d/local.ini
> fix: add Apache CXF HTTP Transport library for fixing WSDL validation

- src/pnpm-lock.yaml
- src/shared-ui/audit-ci-shared.json
- src/shared-ui/package.json
> chore: bump axios from 1.7.2 to 1.7.4

- src/common/common-globalconf/src/main/java/ee/ria/xroad/common/conf/globalconf/VersionedConfigurationDirectory.java
> chore: don't log exception when version number is missing

- src/security-server/admin-service/ui/src/views/KeysAndCertificates/SignAndAuthKeys/KeysTable.vue
- src/security-server/admin-service/ui/src/views/KeysAndCertificates/SignAndAuthKeys/keyColumnSorting.ts
this is optimistic fix done by following Vue guidelines/tips
Refs: XRDDEV-2692
> fix: duplicating certificates in UI list view

- CHANGELOG.md
- src/packages/src/xroad/ubuntu/generic/changelog
> chore: update 7.5.1 release changelog

- src/central-server/admin-service/ui/README.md
- src/security-server/admin-service/ui/README.md
- src/security-server/admin-service/ui/vite.config.js
- src/shared-ui/README.md
> docs: update UI readme files

- src/package.json
- src/shared-ui/audit-ci-shared.json
* Upgrade audit-ci to version 7
* Clear ignored CVEs (develop version is clear)
> chore: update audit-ci and clear ignored CVEs

- src/configuration-client/application/build.gradle
- src/gradle.properties
> chore: enable publishing configuration-client jar to artifactory or local maven

- src/addons/op-monitoring/src/main/java/ee/ria/xroad/proxy/opmonitoring/OpMonitoringBuffer.java
- src/addons/op-monitoring/src/main/java/ee/ria/xroad/proxy/opmonitoring/SavedServiceEndpoint.java
- src/addons/op-monitoring/src/test/java/ee/ria/xroad/proxy/opmonitoring/OpMonitoringBufferTest.java
- src/addons/op-monitoring/src/test/java/ee/ria/xroad/proxy/opmonitoring/SavedServiceEndpointTest.java
- src/common/common-op-monitoring/src/main/java/ee/ria/xroad/common/opmonitoring/OpMonitoringData.java
- src/proxy/application/src/main/java/ee/ria/xroad/proxy/util/MessageProcessorBase.java
- src/proxy/application/src/test/java/ee/ria/xroad/proxy/clientproxy/ClientRestMessageProcessorTest.java
- src/security-server/system-test/src/intTest/java/org/niis/xroad/ss/test/addons/api/FeignXRoadRestRequestsApi.java
- src/security-server/system-test/src/intTest/java/org/niis/xroad/ss/test/addons/glue/OpMonitorStepDefs.java
> chore: match endpoint path with saved path in producer side

- src/configuration-client/application/src/main/java/org/niis/xroad/confclient/ConfClientCLIMain.java
- src/packages/src/xroad/common/proxy/usr/share/xroad/scripts/verify_internal_configuration.sh
> fix: apache cli default parser need also option's short name

- Docker/xrd-dev-stack/hurl-src/setup.hurl
- src/central-server/admin-service/ui/src/store/modules/user.ts
- src/security-server/admin-service/ui/src/components/ui/SnackBar.vue
- src/security-server/admin-service/ui/src/locales/en.json
- src/security-server/admin-service/ui/src/router.ts
- src/security-server/admin-service/ui/src/store/modules/notifications.ts
- src/security-server/admin-service/ui/src/store/modules/services.ts
- src/security-server/admin-service/ui/src/store/modules/tokens.ts
- src/security-server/admin-service/ui/src/store/modules/user.ts
- src/security-server/admin-service/ui/src/ui-types.ts
- src/security-server/admin-service/ui/src/views/ClientTlsCertificate/ClientTlsCertificate.vue
- src/security-server/admin-service/ui/src/views/Clients/Services/ServicesView.vue
- src/security-server/admin-service/ui/src/views/Diagnostics/DiagnosticsView.vue
- src/security-server/admin-service/ui/src/views/KeysAndCertificates/SignAndAuthKeys/AcmeOrderCertificateDialog.vue
- src/security-server/admin-service/ui/src/views/KeysAndCertificates/SignAndAuthKeys/KeysTable.vue
- src/security-server/admin-service/ui/src/views/LocalGroup/LocalGroup.vue
- src/security-server/admin-service/ui/src/views/TokenDetails/TokenDetails.vue
> fix: fix UI issues on SS

- sidecar/files/proxy-ui-api-logback-access.xml
- src/packages/src/xroad/default-configuration/proxy-ui-api-logback-access.xml
- src/packages/src/xroad/redhat/SPECS/xroad-proxy-ui-api.spec
- src/packages/src/xroad/ubuntu/generic/xroad-proxy-ui-api.install
- src/security-server/admin-service/application/src/main/java/org/niis/xroad/securityserver/restapi/config/LogbackAccessConfig.java
- src/security-server/admin-service/application/src/main/resources/application.yml
> feat: direct access logs in the sidecar image to standard output

- src/common/common-message/src/main/java/ee/ria/xroad/common/hashchain/HashChainBuilder.java
> chore: small clean up

- doc/Sidecar/kubernetes_security_server_sidecar_user_guide.md
- sidecar/files/_entrypoint_common.sh
> feat: add backup folder if it does not exists when volume mounting

- Docker/securityserver/files/override-docker.ini
> fix: remove unnecessary values from override-docker.ini

- Docker/centralserver/Dockerfile
- Docker/securityserver/Dockerfile
- Docker/securityserver/init_context.sh
- Docker/testca/Dockerfile
- Docker/xrd-dev-stack/local-dev-prepare.sh
- src/central-server/admin-service/int-test/src/intTest/resources/application-override.yml
- src/central-server/management-service/int-test/src/intTest/resources/application-override.yml
- src/common/common-int-test/src/main/resources/META-INF/ca-container/Dockerfile
- src/common/common-int-test/src/main/resources/signer-container-files/Dockerfile
- src/security-server/admin-service/int-test/src/intTest/resources/application-override.yml
> chore: minify images generated from dockerfiles

- src/common/common-admin-api/src/main/java/org/niis/xroad/restapi/service/ConfigurationVerifier.java
- src/common/common-core/src/main/java/ee/ria/xroad/common/util/process/ExternalProcessRunner.java
> chore: add external process output logging on configuration verifing

- Docker/securityserver-v2/compose.yaml
- src/central-server/admin-service/core-api/src/main/java/org/niis/xroad/cs/admin/api/service/NotificationService.java
- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/InitializationServiceImpl.java
- src/central-server/admin-service/core/src/main/java/org/niis/xroad/cs/admin/core/service/NotificationServiceImpl.java
- src/central-server/admin-service/globalconf-generator/src/main/java/org/niis/xroad/cs/admin/globalconf/generator/GlobalConfGenerationServiceImpl.java
- src/common/common-globalconf/src/main/java/ee/ria/xroad/common/conf/globalconf/GlobalConfInitState.java
- src/common/common-globalconf/src/main/java/ee/ria/xroad/common/conf/globalconf/RemoteGlobalConfSource.java
- src/common/common-globalconf/src/test/java/ee/ria/xroad/common/conf/globalconf/BaseRemoteGlobalConfTest.java
- src/common/common-globalconf/src/test/java/ee/ria/xroad/common/conf/globalconf/RemoteGlobalConfDataLoaderTest.java
- src/common/common-globalconf/src/test/java/ee/ria/xroad/common/conf/globalconf/RemoteGlobalConfSourceTest.java
- src/common/common-rpc/src/main/java/org/niis/xroad/common/rpc/client/RpcChannelFactory.java
- src/common/common-verifier/src/main/java/ee/ria/xroad/common/conf/globalconf/GlobalConfImpl.java
- src/configuration-client/confclient-rpc-client/src/main/java/org/niis/xroad/confclient/proto/ConfClientRpcClient.java
- src/configuration-client/confclient-rpc-client/src/main/proto/globalconf_service.proto
- src/configuration-client/core/src/main/java/ee/ria/xroad/common/conf/globalconf/ConfigurationClientJob.java
- src/configuration-client/core/src/main/java/org/niis/xroad/confclient/config/ConfClientRpcConfig.java
- src/configuration-client/core/src/main/java/org/niis/xroad/confclient/globalconf/AnchorService.java
- src/configuration-client/core/src/main/java/org/niis/xroad/confclient/globalconf/GlobalConfRpcCache.java
- src/configuration-client/core/src/main/java/org/niis/xroad/confclient/globalconf/GlobalConfRpcService.java
- src/configuration-client/core/src/test/java/org/niis/xroad/confclient/globalconf/GlobalConfRpcCacheTest.java
Returning global conf status with data when using remoting, simplified errors logging when servers are not initialized yet
> chore: global conf implementation improvements

- Docker/xrd-dev-stack/tools/build.sh
- Docker/xrd-dev-stack/tools/deploy.sh
- src/packages/src/xroad/common/signer/etc/xroad/services/signer-console.conf
- src/signer-console/build.gradle
- src/signer-console/src/main/java/ee/ria/xroad/signer/console/SignerCLI.java
- src/signer-console/src/main/java/ee/ria/xroad/signer/console/SignerCLIConfig.java
- src/signer-console/src/main/java/ee/ria/xroad/signer/console/SignerCLIMain.java
- src/signer-console/src/main/resources/application.yaml
- src/signer-console/src/main/resources/logback.xml
> chore: signer-console fix

- src/security-server/admin-service/ui/src/locales/en.json
- src/security-server/admin-service/ui/src/views/Clients/InternalServers/InternalServers.vue
- src/security-server/system-test/src/intTest/java/org/niis/xroad/ss/test/ui/glue/ClientInternalServersStepDefs.java
- src/security-server/system-test/src/intTest/java/org/niis/xroad/ss/test/ui/page/ClientInfoPageObj.java
> feat: add more information to system tls certificate table

- src/common/common-mail/src/main/java/org/niis/xroad/common/mail/MailService.java
- src/common/common-mail/src/test/java/org/niis/xroad/common/mail/MailServiceTest.java
- src/security-server/admin-service/application/src/main/java/org/niis/xroad/securityserver/restapi/scheduling/GlobalConfChecker.java
- src/security-server/admin-service/application/src/main/java/org/niis/xroad/securityserver/restapi/util/MailNotificationHelper.java
- src/security-server/admin-service/application/src/test/java/org/niis/xroad/securityserver/restapi/openapi/MailApiControllerTest.java
> fix: Broken notifications breaks Certificate status change flow

- src/central-server/admin-service/ui/src/locales/en.json
- src/security-server/admin-service/ui/src/locales/en.json
- src/security-server/admin-service/ui/src/plugins/vuetify.ts
- src/security-server/admin-service/ui/src/views/KeysAndCertificates/ApiKey/ApiKey.vue
- src/security-server/admin-service/ui/src/views/KeysAndCertificates/SignAndAuthKeys/CertificateRenewalStatus.vue
- src/shared-ui/src/locales/en.json
also couple small fixes for missing components
Refs: XRDDEV-2728
> refactor: Extract common messages to shared UI module

- src/pnpm-lock.yaml
- src/security-server/admin-service/ui/package.json
- src/security-server/admin-service/ui/src/views/Clients/ServiceClients/AddServiceClientAccessRightsWizard.vue
- src/security-server/admin-service/ui/src/views/Clients/ServiceClients/MemberOrGroupSelectionStep.vue
- src/security-server/admin-service/ui/tests/unit/views/Clients/ServiceClients/MemberOrGroupSelectionStep.spec.ts
- src/shared-ui/build.gradle
The root cause seems to be the radiobutton group component in Vuetify not handling such a large list being updated properly. The workaround is to not use the group, which should be fine for our use case as we can just rely on the selection event itself.
Added unit tests to the component to verify and updated the Gradle setup to run the SS unit tests.
> chore: work around issue with large list causing recursion error

- src/security-server/admin-service/ui/src/locales/ee.json
- src/shared-ui/src/locales/ee.json
> Added Estonian localization for Security Server and shared UI

- ansible/roles/xroad-ss/tasks/rhel.yml
- doc/Manuals/ig-ss_x-road_v6_security_server_installation_guide_for_rhel.md
- src/packages/src/xroad/redhat/SPECS/xroad-proxy.spec
Installing PostgreSQL before starting to install Security Server on RHEL.
Refs: XRDDEV-2794
> chore: Security Server installation manual for RHEL updated 

- src/central-server/admin-service/ui/src/locales/en.json
- src/central-server/admin-service/ui/src/locales/es.json
- src/security-server/admin-service/ui/src/locales/en.json
- src/security-server/admin-service/ui/src/locales/es.json
- src/security-server/admin-service/ui/src/locales/et.json
- src/shared-ui/src/locales/en.json
- src/shared-ui/src/locales/es.json
- src/shared-ui/src/locales/et.json
improve consistency between files for easier handling
Refs: XRDDEV-2728
> chore(UI): order translations by keys

- src/packages/src/xroad/common/base/usr/share/xroad/scripts/_setup_db.sh
- src/packages/src/xroad/common/center/usr/share/xroad/db/migrate.sh
- src/packages/src/xroad/common/center/usr/share/xroad/scripts/restore_db.sh
- src/packages/src/xroad/common/proxy/usr/share/xroad/scripts/read_db_properties.sh
- src/packages/src/xroad/common/proxy/usr/share/xroad/scripts/restore_db.sh
- src/packages/src/xroad/common/proxy/usr/share/xroad/scripts/setup_serverconf_db.sh
Refs: XRDDEV-2814
Refs: XRDDEV-2817
> fix: backup restore with multiple ports and with mTLS configuration

- src/addons/messagelog/messagelog-db/src/main/resources/messagelog.hbm.xml
> fix: detach MessageAttachment from hibernate session when archiving

- publiccode.yml
More information about the standard is available [here](https://github.com/publiccodeyml/publiccode.yml).
> chore: Add support for the publiccode.yml standard

- src/packages/src/xroad/common/addon/proxy/messagelog-archiver.conf
- src/packages/src/xroad/common/monitor/etc/xroad/services/monitor.conf
- src/packages/src/xroad/common/proxy/etc/xroad/services/proxy.conf
> chore: increase MaxMetaspaceSize size

- .ort.yml
> chore: Update ORT config

- src/security-server/admin-service/ui/src/store/modules/certificateSignRequest.ts
- src/security-server/admin-service/ui/src/util/sorting.ts
- src/security-server/admin-service/ui/src/views/Settings/SystemParameters/AddTimestampingServiceDialog.vue
- src/security-server/admin-service/ui/src/views/Settings/SystemParameters/SystemParameters.vue
> feat: add csr form fields ordering, cas and timestamp selection drop-down ordering

- src/packages/src/xroad/common/addon/proxy/validate-monitoring-params.sh
- src/packages/src/xroad/default-configuration/proxy-logback.xml
chore: proxy-logback.xml, validate-monitoring-params.sh fixes after package rename
> chore: proxy-logback.xml, validate-monitoring-params.sh fixes after package rename

- doc/Manuals/ig-ss_x-road_v6_security_server_installation_guide.md
- doc/Manuals/ig-ss_x-road_v6_security_server_installation_guide_for_rhel.md
- doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md
- doc/Sidecar/security_server_sidecar_user_guide.md
- sidecar/slim/Dockerfile
> feat: documentation for proxy memory helper

- publiccode.yml
Update the `publiccode.yml` file to version 0.4 (#2669).
> chore: Update publiccode.yml

- doc/Manuals/ig-cs_x-road_6_central_server_installation_guide.md
- doc/Manuals/ig-ss_x-road_v6_security_server_installation_guide.md
- doc/Manuals/ig-ss_x-road_v6_security_server_installation_guide_for_rhel.md
- doc/Manuals/ug-cp_x-road_v6_configuration_proxy_manual.md
- Remove Ubuntu 20.04 and RHEL from installation guides.
- Add health check port to SS installation guides.
- Editorial updates.
> docs: Minor updates to documentation

- src/packages/src/xroad/default-configuration/op-monitor-logback.xml
- src/packages/src/xroad/default-configuration/signer-logback.xml
- src/service/signer/signer-core/src/main/java/org/niis/xroad/signer/core/certmanager/GlobalConfChangeChecker.java
> chore: improving logging

- src/packages/src/xroad/common/base/usr/share/xroad/scripts/_backup_xroad.sh
> chore: exclude lost+found subdirectory from backup script

- .github/workflows/merge_develop_to_8x.yaml
fix dependabot 403 on push
refs: XRDDEV-2875
> feat: As a Developer I want to look into automating the merge from develop to develop-8.x so that changes would automatically be included

- src/common/common-mail/src/main/java/org/niis/xroad/common/mail/MailNotificationType.java
- src/common/common-mail/src/main/java/org/niis/xroad/common/mail/MailService.java
- src/common/common-mail/src/test/java/org/niis/xroad/common/mail/MailServiceTest.java
- src/security-server/admin-service/application/src/main/java/org/niis/xroad/securityserver/restapi/converter/MailNotificationTypeMapping.java
- src/security-server/admin-service/application/src/main/java/org/niis/xroad/securityserver/restapi/openapi/MailApiController.java
- src/security-server/admin-service/application/src/test/java/org/niis/xroad/securityserver/restapi/openapi/MailApiControllerTest.java
- src/security-server/admin-service/ui/src/locales/en.json
- src/security-server/admin-service/ui/src/views/Diagnostics/DiagnosticsMailNotificationCard.vue
- src/security-server/openapi-model/src/main/resources/META-INF/openapi-definition.yaml
- src/security-server/system-test/src/intTest/java/org/niis/xroad/ss/test/ui/glue/DiagnosticsStepDefs.java
- src/security-server/system-test/src/intTest/java/org/niis/xroad/ss/test/ui/page/DiagnosticsPageObj.java
> feat: As a Developer I want to rework the ACME notifications display structure in the diagnostics view as it is becoming a mess

- .github/workflows/merge_develop_to_8x.yaml
fix assignee unrecognized flag
refs: XRDDEV-2875
> fix: As a Developer I want to look into automating the merge from develop to develop-8.x so that changes would automatically be included

- doc/Manuals/ug-cp_x-road_v6_configuration_proxy_manual.md
- sidecar/files/confclient-logback-service.xml
- sidecar/files/confclient-logback.xml
- sidecar/files/op-monitor-logback.xml
- sidecar/files/proxy-logback.xml
- sidecar/files/proxy-ui-api-logback.xml
- src/lib/globalconf-core/src/main/java/org/niis/xroad/globalconf/model/VersionedConfigurationDirectory.java
- src/packages/src/xroad/default-configuration/confclient-logback-service.xml
- src/packages/src/xroad/default-configuration/confclient-logback.xml
- src/packages/src/xroad/default-configuration/confproxy-logback.xml
- src/packages/src/xroad/default-configuration/signer-console-logback.xml
- src/service/configuration-client/configuration-client-core/src/main/java/org/niis/xroad/confclient/core/HttpUrlConnectionConfigurer.java
> chore: improve logging for global configuration finding

- src/security-server/admin-service/ui/src/layouts/AppToolbar.vue
> fix: security server node type is wrongly aligned

- doc/Manuals/ug-syspar_x-road_v6_system_parameters.md
- src/security-server/admin-service/application/src/main/java/org/niis/xroad/securityserver/restapi/config/CustomClientTlsSSLSocketFactory.java
- src/security-server/admin-service/application/src/main/java/org/niis/xroad/securityserver/restapi/service/InternalServerTestService.java
- src/security-server/admin-service/application/src/main/java/org/niis/xroad/securityserver/restapi/wsdl/HttpUrlConnectionConfig.java
- src/security-server/admin-service/application/src/main/resources/application.yml
- src/security-server/admin-service/application/src/test/java/org/niis/xroad/securityserver/restapi/config/CustomClientTlsSSLSocketFactoryTest.java
> fix: allow configuration of TLS protocols and ciphers in proxy-ui

- src/service/configuration-client/configuration-client-core/src/main/java/org/niis/xroad/confclient/core/ConfigurationDownloader.java
- src/service/configuration-client/configuration-client-core/src/main/java/org/niis/xroad/confclient/core/HttpUrlConnectionConfigurer.java
- src/service/configuration-client/configuration-client-core/src/main/java/org/niis/xroad/confclient/core/LocationVersionResolver.java
- src/service/configuration-client/configuration-client-core/src/main/java/org/niis/xroad/confclient/core/config/ConfigurationClientProperties.java
- src/service/configuration-client/configuration-client-core/src/test/java/org/niis/xroad/confclient/core/ConfigurationDownloaderTest.java
> chore: global conf downloader connect and read timeouts

- src/security-server/admin-service/ui/src/views/Diagnostics/Traffic/TrafficChart.vue
- src/security-server/admin-service/ui/src/views/Diagnostics/Traffic/TrafficView.vue
> feat: loading indicator for traffic chart

- doc/Manuals/LoadBalancing/ig-xlb_x-road_external_load_balancer_installation_guide.md
Fix a broken link in the documentation.
> docs: Fix a broken link

- CHANGELOG.md
- sidecar/docker-build.sh
- sidecar/kubernetes/security-server-sidecar-slim.yaml
- sidecar/kubernetes/security-server-sidecar.yaml
- src/gradle.properties
- src/packages/build-deb.sh
- src/packages/build-rpm.sh
- src/packages/src/xroad/ubuntu/generic/changelog
> chore: version bumped to 7.8.0

- .github/workflows/build.yaml
- .github/workflows/publish_images.yaml
- Docker/securityserver/Dockerfile
- Docker/xrd-dev-stack/.env
- Docker/xrd-dev-stack/.env.local
- Docker/xrd-dev-stack/compose.dev.yaml
- Docker/xrd-dev-stack/compose.e2e.yaml
- Docker/xrd-dev-stack/compose.yaml
- Docker/xrd-dev-stack/local-dev-exec-e2e.sh
- Docker/xrd-dev-stack/local-dev-prepare.sh
- Docker/xrd-dev-stack/ss1/init-token-and-run-entrypoint.sh
- development/hurl/scenarios/setup.hurl
- src/security-server/e2e-test/src/intTest/java/org/niis/xroad/e2e/container/EnvSetup.java
- src/security-server/system-test/src/intTest/resources/application-override.yml
- src/security-server/system-test/src/intTest/resources/container-files/Dockerfile
> chore: move softhsm2 initialization to docker compose

- src/security-server/admin-service/ui/src/locales/et.json
- src/shared-ui/src/locales/et.json
> chore: updated Estonian localization for 7.7.0

- doc/Manuals/ug-cs_x-road_6_central_server_user_guide.md
- Add information about trust services to the CS user guide.
> docs: Documentation updates
